// Code generated by mockery v2.53.6. DO NOT EDIT.

package mockdomain

import (
	context "context"

	domain "github.com/rekanesiads/backend-quiz/internal/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// MockCardRepository is an autogenerated mock type for the CardRepository type
type MockCardRepository struct {
	mock.Mock
}

type MockCardRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCardRepository) EXPECT() *MockCardRepository_Expecter {
	return &MockCardRepository_Expecter{mock: &_m.Mock}
}

// BulkCreate provides a mock function with given fields: ctx, cards
func (_m *MockCardRepository) BulkCreate(ctx context.Context, cards []*domain.Card) error {
	ret := _m.Called(ctx, cards)

	if len(ret) == 0 {
		panic("no return value specified for BulkCreate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*domain.Card) error); ok {
		r0 = rf(ctx, cards)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCardRepository_BulkCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkCreate'
type MockCardRepository_BulkCreate_Call struct {
	*mock.Call
}

// BulkCreate is a helper method to define mock.On call
//   - ctx context.Context
//   - cards []*domain.Card
func (_e *MockCardRepository_Expecter) BulkCreate(ctx interface{}, cards interface{}) *MockCardRepository_BulkCreate_Call {
	return &MockCardRepository_BulkCreate_Call{Call: _e.mock.On("BulkCreate", ctx, cards)}
}

func (_c *MockCardRepository_BulkCreate_Call) Run(run func(ctx context.Context, cards []*domain.Card)) *MockCardRepository_BulkCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]*domain.Card))
	})
	return _c
}

func (_c *MockCardRepository_BulkCreate_Call) Return(_a0 error) *MockCardRepository_BulkCreate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCardRepository_BulkCreate_Call) RunAndReturn(run func(context.Context, []*domain.Card) error) *MockCardRepository_BulkCreate_Call {
	_c.Call.Return(run)
	return _c
}

// CountByState provides a mock function with given fields: ctx, deckID
func (_m *MockCardRepository) CountByState(ctx context.Context, deckID uuid.UUID) (map[domain.CardState]int, error) {
	ret := _m.Called(ctx, deckID)

	if len(ret) == 0 {
		panic("no return value specified for CountByState")
	}

	var r0 map[domain.CardState]int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (map[domain.CardState]int, error)); ok {
		return rf(ctx, deckID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) map[domain.CardState]int); ok {
		r0 = rf(ctx, deckID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[domain.CardState]int)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, deckID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCardRepository_CountByState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByState'
type MockCardRepository_CountByState_Call struct {
	*mock.Call
}

// CountByState is a helper method to define mock.On call
//   - ctx context.Context
//   - deckID uuid.UUID
func (_e *MockCardRepository_Expecter) CountByState(ctx interface{}, deckID interface{}) *MockCardRepository_CountByState_Call {
	return &MockCardRepository_CountByState_Call{Call: _e.mock.On("CountByState", ctx, deckID)}
}

func (_c *MockCardRepository_CountByState_Call) Run(run func(ctx context.Context, deckID uuid.UUID)) *MockCardRepository_CountByState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockCardRepository_CountByState_Call) Return(_a0 map[domain.CardState]int, _a1 error) *MockCardRepository_CountByState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCardRepository_CountByState_Call) RunAndReturn(run func(context.Context, uuid.UUID) (map[domain.CardState]int, error)) *MockCardRepository_CountByState_Call {
	_c.Call.Return(run)
	return _c
}

// CountDue provides a mock function with given fields: ctx, deckID, now
func (_m *MockCardRepository) CountDue(ctx context.Context, deckID uuid.UUID, now time.Time) (int, error) {
	ret := _m.Called(ctx, deckID, now)

	if len(ret) == 0 {
		panic("no return value specified for CountDue")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) (int, error)); ok {
		return rf(ctx, deckID, now)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) int); ok {
		r0 = rf(ctx, deckID, now)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r1 = rf(ctx, deckID, now)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCardRepository_CountDue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountDue'
type MockCardRepository_CountDue_Call struct {
	*mock.Call
}

// CountDue is a helper method to define mock.On call
//   - ctx context.Context
//   - deckID uuid.UUID
//   - now time.Time
func (_e *MockCardRepository_Expecter) CountDue(ctx interface{}, deckID interface{}, now interface{}) *MockCardRepository_CountDue_Call {
	return &MockCardRepository_CountDue_Call{Call: _e.mock.On("CountDue", ctx, deckID, now)}
}

func (_c *MockCardRepository_CountDue_Call) Run(run func(ctx context.Context, deckID uuid.UUID, now time.Time)) *MockCardRepository_CountDue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockCardRepository_CountDue_Call) Return(_a0 int, _a1 error) *MockCardRepository_CountDue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCardRepository_CountDue_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time) (int, error)) *MockCardRepository_CountDue_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, card
func (_m *MockCardRepository) Create(ctx context.Context, card *domain.Card) error {
	ret := _m.Called(ctx, card)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Card) error); ok {
		r0 = rf(ctx, card)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCardRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCardRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - card *domain.Card
func (_e *MockCardRepository_Expecter) Create(ctx interface{}, card interface{}) *MockCardRepository_Create_Call {
	return &MockCardRepository_Create_Call{Call: _e.mock.On("Create", ctx, card)}
}

func (_c *MockCardRepository_Create_Call) Run(run func(ctx context.Context, card *domain.Card)) *MockCardRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Card))
	})
	return _c
}

func (_c *MockCardRepository_Create_Call) Return(_a0 error) *MockCardRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCardRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Card) error) *MockCardRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockCardRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCardRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCardRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockCardRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockCardRepository_Delete_Call {
	return &MockCardRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockCardRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockCardRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockCardRepository_Delete_Call) Return(_a0 error) *MockCardRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCardRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockCardRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockCardRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.Card, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Card
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Card, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Card); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Card)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCardRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockCardRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockCardRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockCardRepository_GetByID_Call {
	return &MockCardRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockCardRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockCardRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockCardRepository_GetByID_Call) Return(_a0 *domain.Card, _a1 error) *MockCardRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCardRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.Card, error)) *MockCardRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetDeckMasteryStats provides a mock function with given fields: ctx, deckID
func (_m *MockCardRepository) GetDeckMasteryStats(ctx context.Context, deckID uuid.UUID) (int, int, float64, error) {
	ret := _m.Called(ctx, deckID)

	if len(ret) == 0 {
		panic("no return value specified for GetDeckMasteryStats")
	}

	var r0 int
	var r1 int
	var r2 float64
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int, int, float64, error)); ok {
		return rf(ctx, deckID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int); ok {
		r0 = rf(ctx, deckID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) int); ok {
		r1 = rf(ctx, deckID)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID) float64); ok {
		r2 = rf(ctx, deckID)
	} else {
		r2 = ret.Get(2).(float64)
	}

	if rf, ok := ret.Get(3).(func(context.Context, uuid.UUID) error); ok {
		r3 = rf(ctx, deckID)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// MockCardRepository_GetDeckMasteryStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDeckMasteryStats'
type MockCardRepository_GetDeckMasteryStats_Call struct {
	*mock.Call
}

// GetDeckMasteryStats is a helper method to define mock.On call
//   - ctx context.Context
//   - deckID uuid.UUID
func (_e *MockCardRepository_Expecter) GetDeckMasteryStats(ctx interface{}, deckID interface{}) *MockCardRepository_GetDeckMasteryStats_Call {
	return &MockCardRepository_GetDeckMasteryStats_Call{Call: _e.mock.On("GetDeckMasteryStats", ctx, deckID)}
}

func (_c *MockCardRepository_GetDeckMasteryStats_Call) Run(run func(ctx context.Context, deckID uuid.UUID)) *MockCardRepository_GetDeckMasteryStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockCardRepository_GetDeckMasteryStats_Call) Return(totalCards int, matureCards int, avgStability float64, err error) *MockCardRepository_GetDeckMasteryStats_Call {
	_c.Call.Return(totalCards, matureCards, avgStability, err)
	return _c
}

func (_c *MockCardRepository_GetDeckMasteryStats_Call) RunAndReturn(run func(context.Context, uuid.UUID) (int, int, float64, error)) *MockCardRepository_GetDeckMasteryStats_Call {
	_c.Call.Return(run)
	return _c
}

// GetDueCards provides a mock function with given fields: ctx, deckID, now, newLimit, reviewLimit
func (_m *MockCardRepository) GetDueCards(ctx context.Context, deckID uuid.UUID, now time.Time, newLimit int, reviewLimit int) ([]domain.Card, error) {
	ret := _m.Called(ctx, deckID, now, newLimit, reviewLimit)

	if len(ret) == 0 {
		panic("no return value specified for GetDueCards")
	}

	var r0 []domain.Card
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, int, int) ([]domain.Card, error)); ok {
		return rf(ctx, deckID, now, newLimit, reviewLimit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, int, int) []domain.Card); ok {
		r0 = rf(ctx, deckID, now, newLimit, reviewLimit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Card)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time, int, int) error); ok {
		r1 = rf(ctx, deckID, now, newLimit, reviewLimit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCardRepository_GetDueCards_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDueCards'
type MockCardRepository_GetDueCards_Call struct {
	*mock.Call
}

// GetDueCards is a helper method to define mock.On call
//   - ctx context.Context
//   - deckID uuid.UUID
//   - now time.Time
//   - newLimit int
//   - reviewLimit int
func (_e *MockCardRepository_Expecter) GetDueCards(ctx interface{}, deckID interface{}, now interface{}, newLimit interface{}, reviewLimit interface{}) *MockCardRepository_GetDueCards_Call {
	return &MockCardRepository_GetDueCards_Call{Call: _e.mock.On("GetDueCards", ctx, deckID, now, newLimit, reviewLimit)}
}

func (_c *MockCardRepository_GetDueCards_Call) Run(run func(ctx context.Context, deckID uuid.UUID, now time.Time, newLimit int, reviewLimit int)) *MockCardRepository_GetDueCards_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time), args[3].(int), args[4].(int))
	})
	return _c
}

func (_c *MockCardRepository_GetDueCards_Call) Return(_a0 []domain.Card, _a1 error) *MockCardRepository_GetDueCards_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCardRepository_GetDueCards_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time, int, int) ([]domain.Card, error)) *MockCardRepository_GetDueCards_Call {
	_c.Call.Return(run)
	return _c
}

// GetNextDueAt provides a mock function with given fields: ctx, userID, now
func (_m *MockCardRepository) GetNextDueAt(ctx context.Context, userID uuid.UUID, now time.Time) (*time.Time, error) {
	ret := _m.Called(ctx, userID, now)

	if len(ret) == 0 {
		panic("no return value specified for GetNextDueAt")
	}

	var r0 *time.Time
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) (*time.Time, error)); ok {
		return rf(ctx, userID, now)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) *time.Time); ok {
		r0 = rf(ctx, userID, now)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*time.Time)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r1 = rf(ctx, userID, now)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCardRepository_GetNextDueAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNextDueAt'
type MockCardRepository_GetNextDueAt_Call struct {
	*mock.Call
}

// GetNextDueAt is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - now time.Time
func (_e *MockCardRepository_Expecter) GetNextDueAt(ctx interface{}, userID interface{}, now interface{}) *MockCardRepository_GetNextDueAt_Call {
	return &MockCardRepository_GetNextDueAt_Call{Call: _e.mock.On("GetNextDueAt", ctx, userID, now)}
}

func (_c *MockCardRepository_GetNextDueAt_Call) Run(run func(ctx context.Context, userID uuid.UUID, now time.Time)) *MockCardRepository_GetNextDueAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockCardRepository_GetNextDueAt_Call) Return(_a0 *time.Time, _a1 error) *MockCardRepository_GetNextDueAt_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCardRepository_GetNextDueAt_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time) (*time.Time, error)) *MockCardRepository_GetNextDueAt_Call {
	_c.Call.Return(run)
	return _c
}

// GetUpcomingDueSummary provides a mock function with given fields: ctx, userID, now, horizon
func (_m *MockCardRepository) GetUpcomingDueSummary(ctx context.Context, userID uuid.UUID, now time.Time, horizon time.Time) ([]domain.DeckDueSummary, error) {
	ret := _m.Called(ctx, userID, now, horizon)

	if len(ret) == 0 {
		panic("no return value specified for GetUpcomingDueSummary")
	}

	var r0 []domain.DeckDueSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time) ([]domain.DeckDueSummary, error)); ok {
		return rf(ctx, userID, now, horizon)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time) []domain.DeckDueSummary); ok {
		r0 = rf(ctx, userID, now, horizon)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.DeckDueSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time, time.Time) error); ok {
		r1 = rf(ctx, userID, now, horizon)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCardRepository_GetUpcomingDueSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUpcomingDueSummary'
type MockCardRepository_GetUpcomingDueSummary_Call struct {
	*mock.Call
}

// GetUpcomingDueSummary is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - now time.Time
//   - horizon time.Time
func (_e *MockCardRepository_Expecter) GetUpcomingDueSummary(ctx interface{}, userID interface{}, now interface{}, horizon interface{}) *MockCardRepository_GetUpcomingDueSummary_Call {
	return &MockCardRepository_GetUpcomingDueSummary_Call{Call: _e.mock.On("GetUpcomingDueSummary", ctx, userID, now, horizon)}
}

func (_c *MockCardRepository_GetUpcomingDueSummary_Call) Run(run func(ctx context.Context, userID uuid.UUID, now time.Time, horizon time.Time)) *MockCardRepository_GetUpcomingDueSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *MockCardRepository_GetUpcomingDueSummary_Call) Return(_a0 []domain.DeckDueSummary, _a1 error) *MockCardRepository_GetUpcomingDueSummary_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCardRepository_GetUpcomingDueSummary_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time, time.Time) ([]domain.DeckDueSummary, error)) *MockCardRepository_GetUpcomingDueSummary_Call {
	_c.Call.Return(run)
	return _c
}

// GetWeakCards provides a mock function with given fields: ctx, userID, limit
func (_m *MockCardRepository) GetWeakCards(ctx context.Context, userID uuid.UUID, limit int) ([]domain.Card, error) {
	ret := _m.Called(ctx, userID, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetWeakCards")
	}

	var r0 []domain.Card
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) ([]domain.Card, error)); ok {
		return rf(ctx, userID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) []domain.Card); ok {
		r0 = rf(ctx, userID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Card)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int) error); ok {
		r1 = rf(ctx, userID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCardRepository_GetWeakCards_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWeakCards'
type MockCardRepository_GetWeakCards_Call struct {
	*mock.Call
}

// GetWeakCards is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - limit int
func (_e *MockCardRepository_Expecter) GetWeakCards(ctx interface{}, userID interface{}, limit interface{}) *MockCardRepository_GetWeakCards_Call {
	return &MockCardRepository_GetWeakCards_Call{Call: _e.mock.On("GetWeakCards", ctx, userID, limit)}
}

func (_c *MockCardRepository_GetWeakCards_Call) Run(run func(ctx context.Context, userID uuid.UUID, limit int)) *MockCardRepository_GetWeakCards_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int))
	})
	return _c
}

func (_c *MockCardRepository_GetWeakCards_Call) Return(_a0 []domain.Card, _a1 error) *MockCardRepository_GetWeakCards_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCardRepository_GetWeakCards_Call) RunAndReturn(run func(context.Context, uuid.UUID, int) ([]domain.Card, error)) *MockCardRepository_GetWeakCards_Call {
	_c.Call.Return(run)
	return _c
}

// ListByDeckID provides a mock function with given fields: ctx, deckID, filter, limit, offset
func (_m *MockCardRepository) ListByDeckID(ctx context.Context, deckID uuid.UUID, filter domain.CardFilter, limit int, offset int) ([]domain.Card, int, error) {
	ret := _m.Called(ctx, deckID, filter, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListByDeckID")
	}

	var r0 []domain.Card
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.CardFilter, int, int) ([]domain.Card, int, error)); ok {
		return rf(ctx, deckID, filter, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.CardFilter, int, int) []domain.Card); ok {
		r0 = rf(ctx, deckID, filter, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Card)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, domain.CardFilter, int, int) int); ok {
		r1 = rf(ctx, deckID, filter, limit, offset)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, domain.CardFilter, int, int) error); ok {
		r2 = rf(ctx, deckID, filter, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockCardRepository_ListByDeckID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByDeckID'
type MockCardRepository_ListByDeckID_Call struct {
	*mock.Call
}

// ListByDeckID is a helper method to define mock.On call
//   - ctx context.Context
//   - deckID uuid.UUID
//   - filter domain.CardFilter
//   - limit int
//   - offset int
func (_e *MockCardRepository_Expecter) ListByDeckID(ctx interface{}, deckID interface{}, filter interface{}, limit interface{}, offset interface{}) *MockCardRepository_ListByDeckID_Call {
	return &MockCardRepository_ListByDeckID_Call{Call: _e.mock.On("ListByDeckID", ctx, deckID, filter, limit, offset)}
}

func (_c *MockCardRepository_ListByDeckID_Call) Run(run func(ctx context.Context, deckID uuid.UUID, filter domain.CardFilter, limit int, offset int)) *MockCardRepository_ListByDeckID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(domain.CardFilter), args[3].(int), args[4].(int))
	})
	return _c
}

func (_c *MockCardRepository_ListByDeckID_Call) Return(_a0 []domain.Card, _a1 int, _a2 error) *MockCardRepository_ListByDeckID_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockCardRepository_ListByDeckID_Call) RunAndReturn(run func(context.Context, uuid.UUID, domain.CardFilter, int, int) ([]domain.Card, int, error)) *MockCardRepository_ListByDeckID_Call {
	_c.Call.Return(run)
	return _c
}

// ResetFSRS provides a mock function with given fields: ctx, id
func (_m *MockCardRepository) ResetFSRS(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ResetFSRS")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCardRepository_ResetFSRS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetFSRS'
type MockCardRepository_ResetFSRS_Call struct {
	*mock.Call
}

// ResetFSRS is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockCardRepository_Expecter) ResetFSRS(ctx interface{}, id interface{}) *MockCardRepository_ResetFSRS_Call {
	return &MockCardRepository_ResetFSRS_Call{Call: _e.mock.On("ResetFSRS", ctx, id)}
}

func (_c *MockCardRepository_ResetFSRS_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockCardRepository_ResetFSRS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockCardRepository_ResetFSRS_Call) Return(_a0 error) *MockCardRepository_ResetFSRS_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCardRepository_ResetFSRS_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockCardRepository_ResetFSRS_Call {
	_c.Call.Return(run)
	return _c
}

// SetSuspended provides a mock function with given fields: ctx, id, suspended
func (_m *MockCardRepository) SetSuspended(ctx context.Context, id uuid.UUID, suspended bool) error {
	ret := _m.Called(ctx, id, suspended)

	if len(ret) == 0 {
		panic("no return value specified for SetSuspended")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) error); ok {
		r0 = rf(ctx, id, suspended)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCardRepository_SetSuspended_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetSuspended'
type MockCardRepository_SetSuspended_Call struct {
	*mock.Call
}

// SetSuspended is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - suspended bool
func (_e *MockCardRepository_Expecter) SetSuspended(ctx interface{}, id interface{}, suspended interface{}) *MockCardRepository_SetSuspended_Call {
	return &MockCardRepository_SetSuspended_Call{Call: _e.mock.On("SetSuspended", ctx, id, suspended)}
}

func (_c *MockCardRepository_SetSuspended_Call) Run(run func(ctx context.Context, id uuid.UUID, suspended bool)) *MockCardRepository_SetSuspended_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(bool))
	})
	return _c
}

func (_c *MockCardRepository_SetSuspended_Call) Return(_a0 error) *MockCardRepository_SetSuspended_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCardRepository_SetSuspended_Call) RunAndReturn(run func(context.Context, uuid.UUID, bool) error) *MockCardRepository_SetSuspended_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, card
func (_m *MockCardRepository) Update(ctx context.Context, card *domain.Card) error {
	ret := _m.Called(ctx, card)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Card) error); ok {
		r0 = rf(ctx, card)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCardRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockCardRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - card *domain.Card
func (_e *MockCardRepository_Expecter) Update(ctx interface{}, card interface{}) *MockCardRepository_Update_Call {
	return &MockCardRepository_Update_Call{Call: _e.mock.On("Update", ctx, card)}
}

func (_c *MockCardRepository_Update_Call) Run(run func(ctx context.Context, card *domain.Card)) *MockCardRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Card))
	})
	return _c
}

func (_c *MockCardRepository_Update_Call) Return(_a0 error) *MockCardRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCardRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.Card) error) *MockCardRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateFSRS provides a mock function with given fields: ctx, card
func (_m *MockCardRepository) UpdateFSRS(ctx context.Context, card *domain.Card) error {
	ret := _m.Called(ctx, card)

	if len(ret) == 0 {
		panic("no return value specified for UpdateFSRS")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Card) error); ok {
		r0 = rf(ctx, card)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCardRepository_UpdateFSRS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateFSRS'
type MockCardRepository_UpdateFSRS_Call struct {
	*mock.Call
}

// UpdateFSRS is a helper method to define mock.On call
//   - ctx context.Context
//   - card *domain.Card
func (_e *MockCardRepository_Expecter) UpdateFSRS(ctx interface{}, card interface{}) *MockCardRepository_UpdateFSRS_Call {
	return &MockCardRepository_UpdateFSRS_Call{Call: _e.mock.On("UpdateFSRS", ctx, card)}
}

func (_c *MockCardRepository_UpdateFSRS_Call) Run(run func(ctx context.Context, card *domain.Card)) *MockCardRepository_UpdateFSRS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Card))
	})
	return _c
}

func (_c *MockCardRepository_UpdateFSRS_Call) Return(_a0 error) *MockCardRepository_UpdateFSRS_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCardRepository_UpdateFSRS_Call) RunAndReturn(run func(context.Context, *domain.Card) error) *MockCardRepository_UpdateFSRS_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCardRepository creates a new instance of MockCardRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCardRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCardRepository {
	mock := &MockCardRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
