// Code generated by mockery v2.53.6. DO NOT EDIT.

package mockdomain

import (
	context "context"

	domain "github.com/rekanesiads/backend-quiz/internal/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// MockReviewRepository is an autogenerated mock type for the ReviewRepository type
type MockReviewRepository struct {
	mock.Mock
}

type MockReviewRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReviewRepository) EXPECT() *MockReviewRepository_Expecter {
	return &MockReviewRepository_Expecter{mock: &_m.Mock}
}

// CountByUserAndDate provides a mock function with given fields: ctx, userID, date
func (_m *MockReviewRepository) CountByUserAndDate(ctx context.Context, userID uuid.UUID, date time.Time) (int, error) {
	ret := _m.Called(ctx, userID, date)

	if len(ret) == 0 {
		panic("no return value specified for CountByUserAndDate")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) (int, error)); ok {
		return rf(ctx, userID, date)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) int); ok {
		r0 = rf(ctx, userID, date)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r1 = rf(ctx, userID, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReviewRepository_CountByUserAndDate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByUserAndDate'
type MockReviewRepository_CountByUserAndDate_Call struct {
	*mock.Call
}

// CountByUserAndDate is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - date time.Time
func (_e *MockReviewRepository_Expecter) CountByUserAndDate(ctx interface{}, userID interface{}, date interface{}) *MockReviewRepository_CountByUserAndDate_Call {
	return &MockReviewRepository_CountByUserAndDate_Call{Call: _e.mock.On("CountByUserAndDate", ctx, userID, date)}
}

func (_c *MockReviewRepository_CountByUserAndDate_Call) Run(run func(ctx context.Context, userID uuid.UUID, date time.Time)) *MockReviewRepository_CountByUserAndDate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockReviewRepository_CountByUserAndDate_Call) Return(_a0 int, _a1 error) *MockReviewRepository_CountByUserAndDate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReviewRepository_CountByUserAndDate_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time) (int, error)) *MockReviewRepository_CountByUserAndDate_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, log
func (_m *MockReviewRepository) Create(ctx context.Context, log *domain.ReviewLog) error {
	ret := _m.Called(ctx, log)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ReviewLog) error); ok {
		r0 = rf(ctx, log)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReviewRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockReviewRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - log *domain.ReviewLog
func (_e *MockReviewRepository_Expecter) Create(ctx interface{}, log interface{}) *MockReviewRepository_Create_Call {
	return &MockReviewRepository_Create_Call{Call: _e.mock.On("Create", ctx, log)}
}

func (_c *MockReviewRepository_Create_Call) Run(run func(ctx context.Context, log *domain.ReviewLog)) *MockReviewRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.ReviewLog))
	})
	return _c
}

func (_c *MockReviewRepository_Create_Call) Return(_a0 error) *MockReviewRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReviewRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.ReviewLog) error) *MockReviewRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetReviewCountsPerDay provides a mock function with given fields: ctx, userID, from, to
func (_m *MockReviewRepository) GetReviewCountsPerDay(ctx context.Context, userID uuid.UUID, from time.Time, to time.Time) ([]domain.DailyReviewCount, error) {
	ret := _m.Called(ctx, userID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for GetReviewCountsPerDay")
	}

	var r0 []domain.DailyReviewCount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time) ([]domain.DailyReviewCount, error)); ok {
		return rf(ctx, userID, from, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time) []domain.DailyReviewCount); ok {
		r0 = rf(ctx, userID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.DailyReviewCount)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time, time.Time) error); ok {
		r1 = rf(ctx, userID, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReviewRepository_GetReviewCountsPerDay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReviewCountsPerDay'
type MockReviewRepository_GetReviewCountsPerDay_Call struct {
	*mock.Call
}

// GetReviewCountsPerDay is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - from time.Time
//   - to time.Time
func (_e *MockReviewRepository_Expecter) GetReviewCountsPerDay(ctx interface{}, userID interface{}, from interface{}, to interface{}) *MockReviewRepository_GetReviewCountsPerDay_Call {
	return &MockReviewRepository_GetReviewCountsPerDay_Call{Call: _e.mock.On("GetReviewCountsPerDay", ctx, userID, from, to)}
}

func (_c *MockReviewRepository_GetReviewCountsPerDay_Call) Run(run func(ctx context.Context, userID uuid.UUID, from time.Time, to time.Time)) *MockReviewRepository_GetReviewCountsPerDay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *MockReviewRepository_GetReviewCountsPerDay_Call) Return(_a0 []domain.DailyReviewCount, _a1 error) *MockReviewRepository_GetReviewCountsPerDay_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReviewRepository_GetReviewCountsPerDay_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time, time.Time) ([]domain.DailyReviewCount, error)) *MockReviewRepository_GetReviewCountsPerDay_Call {
	_c.Call.Return(run)
	return _c
}

// ListByCardID provides a mock function with given fields: ctx, cardID
func (_m *MockReviewRepository) ListByCardID(ctx context.Context, cardID uuid.UUID) ([]domain.ReviewLog, error) {
	ret := _m.Called(ctx, cardID)

	if len(ret) == 0 {
		panic("no return value specified for ListByCardID")
	}

	var r0 []domain.ReviewLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]domain.ReviewLog, error)); ok {
		return rf(ctx, cardID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []domain.ReviewLog); ok {
		r0 = rf(ctx, cardID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ReviewLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, cardID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReviewRepository_ListByCardID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByCardID'
type MockReviewRepository_ListByCardID_Call struct {
	*mock.Call
}

// ListByCardID is a helper method to define mock.On call
//   - ctx context.Context
//   - cardID uuid.UUID
func (_e *MockReviewRepository_Expecter) ListByCardID(ctx interface{}, cardID interface{}) *MockReviewRepository_ListByCardID_Call {
	return &MockReviewRepository_ListByCardID_Call{Call: _e.mock.On("ListByCardID", ctx, cardID)}
}

func (_c *MockReviewRepository_ListByCardID_Call) Run(run func(ctx context.Context, cardID uuid.UUID)) *MockReviewRepository_ListByCardID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockReviewRepository_ListByCardID_Call) Return(_a0 []domain.ReviewLog, _a1 error) *MockReviewRepository_ListByCardID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReviewRepository_ListByCardID_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]domain.ReviewLog, error)) *MockReviewRepository_ListByCardID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUserID provides a mock function with given fields: ctx, userID, from, to, limit, offset
func (_m *MockReviewRepository) ListByUserID(ctx context.Context, userID uuid.UUID, from time.Time, to time.Time, limit int, offset int) ([]domain.ReviewLog, int, error) {
	ret := _m.Called(ctx, userID, from, to, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListByUserID")
	}

	var r0 []domain.ReviewLog
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time, int, int) ([]domain.ReviewLog, int, error)); ok {
		return rf(ctx, userID, from, to, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time, int, int) []domain.ReviewLog); ok {
		r0 = rf(ctx, userID, from, to, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ReviewLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time, time.Time, int, int) int); ok {
		r1 = rf(ctx, userID, from, to, limit, offset)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, time.Time, time.Time, int, int) error); ok {
		r2 = rf(ctx, userID, from, to, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockReviewRepository_ListByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUserID'
type MockReviewRepository_ListByUserID_Call struct {
	*mock.Call
}

// ListByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - from time.Time
//   - to time.Time
//   - limit int
//   - offset int
func (_e *MockReviewRepository_Expecter) ListByUserID(ctx interface{}, userID interface{}, from interface{}, to interface{}, limit interface{}, offset interface{}) *MockReviewRepository_ListByUserID_Call {
	return &MockReviewRepository_ListByUserID_Call{Call: _e.mock.On("ListByUserID", ctx, userID, from, to, limit, offset)}
}

func (_c *MockReviewRepository_ListByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID, from time.Time, to time.Time, limit int, offset int)) *MockReviewRepository_ListByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time), args[3].(time.Time), args[4].(int), args[5].(int))
	})
	return _c
}

func (_c *MockReviewRepository_ListByUserID_Call) Return(_a0 []domain.ReviewLog, _a1 int, _a2 error) *MockReviewRepository_ListByUserID_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockReviewRepository_ListByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time, time.Time, int, int) ([]domain.ReviewLog, int, error)) *MockReviewRepository_ListByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReviewRepository creates a new instance of MockReviewRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReviewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReviewRepository {
	mock := &MockReviewRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
