// Code generated by mockery v2.53.6. DO NOT EDIT.

package mockdomain

import (
	context "context"

	domain "github.com/alfariesh/backend-quiz/internal/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// MockStatsRepository is an autogenerated mock type for the StatsRepository type
type MockStatsRepository struct {
	mock.Mock
}

type MockStatsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStatsRepository) EXPECT() *MockStatsRepository_Expecter {
	return &MockStatsRepository_Expecter{mock: &_m.Mock}
}

// GetDailyStats provides a mock function with given fields: ctx, userID, from, to
func (_m *MockStatsRepository) GetDailyStats(ctx context.Context, userID uuid.UUID, from time.Time, to time.Time) ([]domain.DailyStats, error) {
	ret := _m.Called(ctx, userID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for GetDailyStats")
	}

	var r0 []domain.DailyStats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time) ([]domain.DailyStats, error)); ok {
		return rf(ctx, userID, from, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time) []domain.DailyStats); ok {
		r0 = rf(ctx, userID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.DailyStats)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time, time.Time) error); ok {
		r1 = rf(ctx, userID, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStatsRepository_GetDailyStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDailyStats'
type MockStatsRepository_GetDailyStats_Call struct {
	*mock.Call
}

// GetDailyStats is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - from time.Time
//   - to time.Time
func (_e *MockStatsRepository_Expecter) GetDailyStats(ctx interface{}, userID interface{}, from interface{}, to interface{}) *MockStatsRepository_GetDailyStats_Call {
	return &MockStatsRepository_GetDailyStats_Call{Call: _e.mock.On("GetDailyStats", ctx, userID, from, to)}
}

func (_c *MockStatsRepository_GetDailyStats_Call) Run(run func(ctx context.Context, userID uuid.UUID, from time.Time, to time.Time)) *MockStatsRepository_GetDailyStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *MockStatsRepository_GetDailyStats_Call) Return(_a0 []domain.DailyStats, _a1 error) *MockStatsRepository_GetDailyStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStatsRepository_GetDailyStats_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time, time.Time) ([]domain.DailyStats, error)) *MockStatsRepository_GetDailyStats_Call {
	_c.Call.Return(run)
	return _c
}

// GetGlobalLeaderboard provides a mock function with given fields: ctx, limit
func (_m *MockStatsRepository) GetGlobalLeaderboard(ctx context.Context, limit int) ([]domain.LeaderboardEntry, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetGlobalLeaderboard")
	}

	var r0 []domain.LeaderboardEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]domain.LeaderboardEntry, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []domain.LeaderboardEntry); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.LeaderboardEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStatsRepository_GetGlobalLeaderboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGlobalLeaderboard'
type MockStatsRepository_GetGlobalLeaderboard_Call struct {
	*mock.Call
}

// GetGlobalLeaderboard is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *MockStatsRepository_Expecter) GetGlobalLeaderboard(ctx interface{}, limit interface{}) *MockStatsRepository_GetGlobalLeaderboard_Call {
	return &MockStatsRepository_GetGlobalLeaderboard_Call{Call: _e.mock.On("GetGlobalLeaderboard", ctx, limit)}
}

func (_c *MockStatsRepository_GetGlobalLeaderboard_Call) Run(run func(ctx context.Context, limit int)) *MockStatsRepository_GetGlobalLeaderboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockStatsRepository_GetGlobalLeaderboard_Call) Return(_a0 []domain.LeaderboardEntry, _a1 error) *MockStatsRepository_GetGlobalLeaderboard_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStatsRepository_GetGlobalLeaderboard_Call) RunAndReturn(run func(context.Context, int) ([]domain.LeaderboardEntry, error)) *MockStatsRepository_GetGlobalLeaderboard_Call {
	_c.Call.Return(run)
	return _c
}

// GetStreak provides a mock function with given fields: ctx, userID
func (_m *MockStatsRepository) GetStreak(ctx context.Context, userID uuid.UUID) (int, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetStreak")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStatsRepository_GetStreak_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStreak'
type MockStatsRepository_GetStreak_Call struct {
	*mock.Call
}

// GetStreak is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockStatsRepository_Expecter) GetStreak(ctx interface{}, userID interface{}) *MockStatsRepository_GetStreak_Call {
	return &MockStatsRepository_GetStreak_Call{Call: _e.mock.On("GetStreak", ctx, userID)}
}

func (_c *MockStatsRepository_GetStreak_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockStatsRepository_GetStreak_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockStatsRepository_GetStreak_Call) Return(_a0 int, _a1 error) *MockStatsRepository_GetStreak_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStatsRepository_GetStreak_Call) RunAndReturn(run func(context.Context, uuid.UUID) (int, error)) *MockStatsRepository_GetStreak_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertDailyStats provides a mock function with given fields: ctx, stats
func (_m *MockStatsRepository) UpsertDailyStats(ctx context.Context, stats *domain.DailyStats) error {
	ret := _m.Called(ctx, stats)

	if len(ret) == 0 {
		panic("no return value specified for UpsertDailyStats")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.DailyStats) error); ok {
		r0 = rf(ctx, stats)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStatsRepository_UpsertDailyStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertDailyStats'
type MockStatsRepository_UpsertDailyStats_Call struct {
	*mock.Call
}

// UpsertDailyStats is a helper method to define mock.On call
//   - ctx context.Context
//   - stats *domain.DailyStats
func (_e *MockStatsRepository_Expecter) UpsertDailyStats(ctx interface{}, stats interface{}) *MockStatsRepository_UpsertDailyStats_Call {
	return &MockStatsRepository_UpsertDailyStats_Call{Call: _e.mock.On("UpsertDailyStats", ctx, stats)}
}

func (_c *MockStatsRepository_UpsertDailyStats_Call) Run(run func(ctx context.Context, stats *domain.DailyStats)) *MockStatsRepository_UpsertDailyStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.DailyStats))
	})
	return _c
}

func (_c *MockStatsRepository_UpsertDailyStats_Call) Return(_a0 error) *MockStatsRepository_UpsertDailyStats_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStatsRepository_UpsertDailyStats_Call) RunAndReturn(run func(context.Context, *domain.DailyStats) error) *MockStatsRepository_UpsertDailyStats_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStatsRepository creates a new instance of MockStatsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStatsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStatsRepository {
	mock := &MockStatsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
