// Code generated by mockery v2.53.6. DO NOT EDIT.

package mockdomain

import (
	context "context"

	domain "github.com/alfariesh/backend-quiz/internal/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// MockPasswordResetTokenRepository is an autogenerated mock type for the PasswordResetTokenRepository type
type MockPasswordResetTokenRepository struct {
	mock.Mock
}

type MockPasswordResetTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPasswordResetTokenRepository) EXPECT() *MockPasswordResetTokenRepository_Expecter {
	return &MockPasswordResetTokenRepository_Expecter{mock: &_m.Mock}
}

// Consume provides a mock function with given fields: ctx, id, at
func (_m *MockPasswordResetTokenRepository) Consume(ctx context.Context, id uuid.UUID, at time.Time) error {
	ret := _m.Called(ctx, id, at)

	if len(ret) == 0 {
		panic("no return value specified for Consume")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r0 = rf(ctx, id, at)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPasswordResetTokenRepository_Consume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Consume'
type MockPasswordResetTokenRepository_Consume_Call struct {
	*mock.Call
}

// Consume is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - at time.Time
func (_e *MockPasswordResetTokenRepository_Expecter) Consume(ctx interface{}, id interface{}, at interface{}) *MockPasswordResetTokenRepository_Consume_Call {
	return &MockPasswordResetTokenRepository_Consume_Call{Call: _e.mock.On("Consume", ctx, id, at)}
}

func (_c *MockPasswordResetTokenRepository_Consume_Call) Run(run func(ctx context.Context, id uuid.UUID, at time.Time)) *MockPasswordResetTokenRepository_Consume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockPasswordResetTokenRepository_Consume_Call) Return(_a0 error) *MockPasswordResetTokenRepository_Consume_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPasswordResetTokenRepository_Consume_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time) error) *MockPasswordResetTokenRepository_Consume_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, t
func (_m *MockPasswordResetTokenRepository) Create(ctx context.Context, t *domain.PasswordResetToken) error {
	ret := _m.Called(ctx, t)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.PasswordResetToken) error); ok {
		r0 = rf(ctx, t)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPasswordResetTokenRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockPasswordResetTokenRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - t *domain.PasswordResetToken
func (_e *MockPasswordResetTokenRepository_Expecter) Create(ctx interface{}, t interface{}) *MockPasswordResetTokenRepository_Create_Call {
	return &MockPasswordResetTokenRepository_Create_Call{Call: _e.mock.On("Create", ctx, t)}
}

func (_c *MockPasswordResetTokenRepository_Create_Call) Run(run func(ctx context.Context, t *domain.PasswordResetToken)) *MockPasswordResetTokenRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.PasswordResetToken))
	})
	return _c
}

func (_c *MockPasswordResetTokenRepository_Create_Call) Return(_a0 error) *MockPasswordResetTokenRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPasswordResetTokenRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.PasswordResetToken) error) *MockPasswordResetTokenRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByUserID provides a mock function with given fields: ctx, userID
func (_m *MockPasswordResetTokenRepository) DeleteByUserID(ctx context.Context, userID uuid.UUID) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByUserID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPasswordResetTokenRepository_DeleteByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByUserID'
type MockPasswordResetTokenRepository_DeleteByUserID_Call struct {
	*mock.Call
}

// DeleteByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockPasswordResetTokenRepository_Expecter) DeleteByUserID(ctx interface{}, userID interface{}) *MockPasswordResetTokenRepository_DeleteByUserID_Call {
	return &MockPasswordResetTokenRepository_DeleteByUserID_Call{Call: _e.mock.On("DeleteByUserID", ctx, userID)}
}

func (_c *MockPasswordResetTokenRepository_DeleteByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockPasswordResetTokenRepository_DeleteByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockPasswordResetTokenRepository_DeleteByUserID_Call) Return(_a0 error) *MockPasswordResetTokenRepository_DeleteByUserID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPasswordResetTokenRepository_DeleteByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockPasswordResetTokenRepository_DeleteByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByHash provides a mock function with given fields: ctx, tokenHash
func (_m *MockPasswordResetTokenRepository) GetByHash(ctx context.Context, tokenHash string) (*domain.PasswordResetToken, error) {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for GetByHash")
	}

	var r0 *domain.PasswordResetToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.PasswordResetToken, error)); ok {
		return rf(ctx, tokenHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.PasswordResetToken); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PasswordResetToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPasswordResetTokenRepository_GetByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByHash'
type MockPasswordResetTokenRepository_GetByHash_Call struct {
	*mock.Call
}

// GetByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockPasswordResetTokenRepository_Expecter) GetByHash(ctx interface{}, tokenHash interface{}) *MockPasswordResetTokenRepository_GetByHash_Call {
	return &MockPasswordResetTokenRepository_GetByHash_Call{Call: _e.mock.On("GetByHash", ctx, tokenHash)}
}

func (_c *MockPasswordResetTokenRepository_GetByHash_Call) Run(run func(ctx context.Context, tokenHash string)) *MockPasswordResetTokenRepository_GetByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPasswordResetTokenRepository_GetByHash_Call) Return(_a0 *domain.PasswordResetToken, _a1 error) *MockPasswordResetTokenRepository_GetByHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPasswordResetTokenRepository_GetByHash_Call) RunAndReturn(run func(context.Context, string) (*domain.PasswordResetToken, error)) *MockPasswordResetTokenRepository_GetByHash_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPasswordResetTokenRepository creates a new instance of MockPasswordResetTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPasswordResetTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPasswordResetTokenRepository {
	mock := &MockPasswordResetTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
