// Code generated by mockery v2.53.6. DO NOT EDIT.

package mockdomain

import (
	context "context"

	domain "github.com/alfariesh/backend-quiz/internal/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockLoginAttemptRepository is an autogenerated mock type for the LoginAttemptRepository type
type MockLoginAttemptRepository struct {
	mock.Mock
}

type MockLoginAttemptRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoginAttemptRepository) EXPECT() *MockLoginAttemptRepository_Expecter {
	return &MockLoginAttemptRepository_Expecter{mock: &_m.Mock}
}

// CountRecentFailures provides a mock function with given fields: ctx, email, since
func (_m *MockLoginAttemptRepository) CountRecentFailures(ctx context.Context, email string, since time.Time) (int, error) {
	ret := _m.Called(ctx, email, since)

	if len(ret) == 0 {
		panic("no return value specified for CountRecentFailures")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) (int, error)); ok {
		return rf(ctx, email, since)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) int); ok {
		r0 = rf(ctx, email, since)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = rf(ctx, email, since)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLoginAttemptRepository_CountRecentFailures_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountRecentFailures'
type MockLoginAttemptRepository_CountRecentFailures_Call struct {
	*mock.Call
}

// CountRecentFailures is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - since time.Time
func (_e *MockLoginAttemptRepository_Expecter) CountRecentFailures(ctx interface{}, email interface{}, since interface{}) *MockLoginAttemptRepository_CountRecentFailures_Call {
	return &MockLoginAttemptRepository_CountRecentFailures_Call{Call: _e.mock.On("CountRecentFailures", ctx, email, since)}
}

func (_c *MockLoginAttemptRepository_CountRecentFailures_Call) Run(run func(ctx context.Context, email string, since time.Time)) *MockLoginAttemptRepository_CountRecentFailures_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time))
	})
	return _c
}

func (_c *MockLoginAttemptRepository_CountRecentFailures_Call) Return(_a0 int, _a1 error) *MockLoginAttemptRepository_CountRecentFailures_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLoginAttemptRepository_CountRecentFailures_Call) RunAndReturn(run func(context.Context, string, time.Time) (int, error)) *MockLoginAttemptRepository_CountRecentFailures_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, a
func (_m *MockLoginAttemptRepository) Create(ctx context.Context, a *domain.LoginAttempt) error {
	ret := _m.Called(ctx, a)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.LoginAttempt) error); ok {
		r0 = rf(ctx, a)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLoginAttemptRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockLoginAttemptRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - a *domain.LoginAttempt
func (_e *MockLoginAttemptRepository_Expecter) Create(ctx interface{}, a interface{}) *MockLoginAttemptRepository_Create_Call {
	return &MockLoginAttemptRepository_Create_Call{Call: _e.mock.On("Create", ctx, a)}
}

func (_c *MockLoginAttemptRepository_Create_Call) Run(run func(ctx context.Context, a *domain.LoginAttempt)) *MockLoginAttemptRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.LoginAttempt))
	})
	return _c
}

func (_c *MockLoginAttemptRepository_Create_Call) Return(_a0 error) *MockLoginAttemptRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLoginAttemptRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.LoginAttempt) error) *MockLoginAttemptRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLoginAttemptRepository creates a new instance of MockLoginAttemptRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoginAttemptRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoginAttemptRepository {
	mock := &MockLoginAttemptRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
