// Code generated by mockery v2.53.6. DO NOT EDIT.

package mockdomain

import (
	context "context"

	domain "github.com/alfariesh/backend-quiz/internal/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// MockRefreshTokenRepository is an autogenerated mock type for the RefreshTokenRepository type
type MockRefreshTokenRepository struct {
	mock.Mock
}

type MockRefreshTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRefreshTokenRepository) EXPECT() *MockRefreshTokenRepository_Expecter {
	return &MockRefreshTokenRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, t
func (_m *MockRefreshTokenRepository) Create(ctx context.Context, t *domain.RefreshToken) error {
	ret := _m.Called(ctx, t)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.RefreshToken) error); ok {
		r0 = rf(ctx, t)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshTokenRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRefreshTokenRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - t *domain.RefreshToken
func (_e *MockRefreshTokenRepository_Expecter) Create(ctx interface{}, t interface{}) *MockRefreshTokenRepository_Create_Call {
	return &MockRefreshTokenRepository_Create_Call{Call: _e.mock.On("Create", ctx, t)}
}

func (_c *MockRefreshTokenRepository_Create_Call) Run(run func(ctx context.Context, t *domain.RefreshToken)) *MockRefreshTokenRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.RefreshToken))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_Create_Call) Return(_a0 error) *MockRefreshTokenRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshTokenRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.RefreshToken) error) *MockRefreshTokenRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeviceSeen provides a mock function with given fields: ctx, userID, userAgent, ipAddress
func (_m *MockRefreshTokenRepository) DeviceSeen(ctx context.Context, userID uuid.UUID, userAgent string, ipAddress string) (bool, error) {
	ret := _m.Called(ctx, userID, userAgent, ipAddress)

	if len(ret) == 0 {
		panic("no return value specified for DeviceSeen")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) (bool, error)); ok {
		return rf(ctx, userID, userAgent, ipAddress)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) bool); ok {
		r0 = rf(ctx, userID, userAgent, ipAddress)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string) error); ok {
		r1 = rf(ctx, userID, userAgent, ipAddress)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRefreshTokenRepository_DeviceSeen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeviceSeen'
type MockRefreshTokenRepository_DeviceSeen_Call struct {
	*mock.Call
}

// DeviceSeen is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - userAgent string
//   - ipAddress string
func (_e *MockRefreshTokenRepository_Expecter) DeviceSeen(ctx interface{}, userID interface{}, userAgent interface{}, ipAddress interface{}) *MockRefreshTokenRepository_DeviceSeen_Call {
	return &MockRefreshTokenRepository_DeviceSeen_Call{Call: _e.mock.On("DeviceSeen", ctx, userID, userAgent, ipAddress)}
}

func (_c *MockRefreshTokenRepository_DeviceSeen_Call) Run(run func(ctx context.Context, userID uuid.UUID, userAgent string, ipAddress string)) *MockRefreshTokenRepository_DeviceSeen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_DeviceSeen_Call) Return(_a0 bool, _a1 error) *MockRefreshTokenRepository_DeviceSeen_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRefreshTokenRepository_DeviceSeen_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, string) (bool, error)) *MockRefreshTokenRepository_DeviceSeen_Call {
	_c.Call.Return(run)
	return _c
}

// GetByHash provides a mock function with given fields: ctx, tokenHash
func (_m *MockRefreshTokenRepository) GetByHash(ctx context.Context, tokenHash string) (*domain.RefreshToken, error) {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for GetByHash")
	}

	var r0 *domain.RefreshToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.RefreshToken, error)); ok {
		return rf(ctx, tokenHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.RefreshToken); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.RefreshToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRefreshTokenRepository_GetByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByHash'
type MockRefreshTokenRepository_GetByHash_Call struct {
	*mock.Call
}

// GetByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockRefreshTokenRepository_Expecter) GetByHash(ctx interface{}, tokenHash interface{}) *MockRefreshTokenRepository_GetByHash_Call {
	return &MockRefreshTokenRepository_GetByHash_Call{Call: _e.mock.On("GetByHash", ctx, tokenHash)}
}

func (_c *MockRefreshTokenRepository_GetByHash_Call) Run(run func(ctx context.Context, tokenHash string)) *MockRefreshTokenRepository_GetByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_GetByHash_Call) Return(_a0 *domain.RefreshToken, _a1 error) *MockRefreshTokenRepository_GetByHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRefreshTokenRepository_GetByHash_Call) RunAndReturn(run func(context.Context, string) (*domain.RefreshToken, error)) *MockRefreshTokenRepository_GetByHash_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockRefreshTokenRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.RefreshToken, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.RefreshToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.RefreshToken, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.RefreshToken); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.RefreshToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRefreshTokenRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockRefreshTokenRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRefreshTokenRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockRefreshTokenRepository_GetByID_Call {
	return &MockRefreshTokenRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockRefreshTokenRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRefreshTokenRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_GetByID_Call) Return(_a0 *domain.RefreshToken, _a1 error) *MockRefreshTokenRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRefreshTokenRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.RefreshToken, error)) *MockRefreshTokenRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListActiveByUser provides a mock function with given fields: ctx, userID, now
func (_m *MockRefreshTokenRepository) ListActiveByUser(ctx context.Context, userID uuid.UUID, now time.Time) ([]*domain.RefreshToken, error) {
	ret := _m.Called(ctx, userID, now)

	if len(ret) == 0 {
		panic("no return value specified for ListActiveByUser")
	}

	var r0 []*domain.RefreshToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) ([]*domain.RefreshToken, error)); ok {
		return rf(ctx, userID, now)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) []*domain.RefreshToken); ok {
		r0 = rf(ctx, userID, now)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.RefreshToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r1 = rf(ctx, userID, now)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRefreshTokenRepository_ListActiveByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListActiveByUser'
type MockRefreshTokenRepository_ListActiveByUser_Call struct {
	*mock.Call
}

// ListActiveByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - now time.Time
func (_e *MockRefreshTokenRepository_Expecter) ListActiveByUser(ctx interface{}, userID interface{}, now interface{}) *MockRefreshTokenRepository_ListActiveByUser_Call {
	return &MockRefreshTokenRepository_ListActiveByUser_Call{Call: _e.mock.On("ListActiveByUser", ctx, userID, now)}
}

func (_c *MockRefreshTokenRepository_ListActiveByUser_Call) Run(run func(ctx context.Context, userID uuid.UUID, now time.Time)) *MockRefreshTokenRepository_ListActiveByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_ListActiveByUser_Call) Return(_a0 []*domain.RefreshToken, _a1 error) *MockRefreshTokenRepository_ListActiveByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRefreshTokenRepository_ListActiveByUser_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time) ([]*domain.RefreshToken, error)) *MockRefreshTokenRepository_ListActiveByUser_Call {
	_c.Call.Return(run)
	return _c
}

// Revoke provides a mock function with given fields: ctx, id, at
func (_m *MockRefreshTokenRepository) Revoke(ctx context.Context, id uuid.UUID, at time.Time) error {
	ret := _m.Called(ctx, id, at)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r0 = rf(ctx, id, at)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshTokenRepository_Revoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revoke'
type MockRefreshTokenRepository_Revoke_Call struct {
	*mock.Call
}

// Revoke is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - at time.Time
func (_e *MockRefreshTokenRepository_Expecter) Revoke(ctx interface{}, id interface{}, at interface{}) *MockRefreshTokenRepository_Revoke_Call {
	return &MockRefreshTokenRepository_Revoke_Call{Call: _e.mock.On("Revoke", ctx, id, at)}
}

func (_c *MockRefreshTokenRepository_Revoke_Call) Run(run func(ctx context.Context, id uuid.UUID, at time.Time)) *MockRefreshTokenRepository_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_Revoke_Call) Return(_a0 error) *MockRefreshTokenRepository_Revoke_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshTokenRepository_Revoke_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time) error) *MockRefreshTokenRepository_Revoke_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAllForUser provides a mock function with given fields: ctx, userID, at
func (_m *MockRefreshTokenRepository) RevokeAllForUser(ctx context.Context, userID uuid.UUID, at time.Time) error {
	ret := _m.Called(ctx, userID, at)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllForUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r0 = rf(ctx, userID, at)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshTokenRepository_RevokeAllForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAllForUser'
type MockRefreshTokenRepository_RevokeAllForUser_Call struct {
	*mock.Call
}

// RevokeAllForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - at time.Time
func (_e *MockRefreshTokenRepository_Expecter) RevokeAllForUser(ctx interface{}, userID interface{}, at interface{}) *MockRefreshTokenRepository_RevokeAllForUser_Call {
	return &MockRefreshTokenRepository_RevokeAllForUser_Call{Call: _e.mock.On("RevokeAllForUser", ctx, userID, at)}
}

func (_c *MockRefreshTokenRepository_RevokeAllForUser_Call) Run(run func(ctx context.Context, userID uuid.UUID, at time.Time)) *MockRefreshTokenRepository_RevokeAllForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_RevokeAllForUser_Call) Return(_a0 error) *MockRefreshTokenRepository_RevokeAllForUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshTokenRepository_RevokeAllForUser_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time) error) *MockRefreshTokenRepository_RevokeAllForUser_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeChildren provides a mock function with given fields: ctx, parentID, at
func (_m *MockRefreshTokenRepository) RevokeChildren(ctx context.Context, parentID uuid.UUID, at time.Time) error {
	ret := _m.Called(ctx, parentID, at)

	if len(ret) == 0 {
		panic("no return value specified for RevokeChildren")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r0 = rf(ctx, parentID, at)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshTokenRepository_RevokeChildren_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeChildren'
type MockRefreshTokenRepository_RevokeChildren_Call struct {
	*mock.Call
}

// RevokeChildren is a helper method to define mock.On call
//   - ctx context.Context
//   - parentID uuid.UUID
//   - at time.Time
func (_e *MockRefreshTokenRepository_Expecter) RevokeChildren(ctx interface{}, parentID interface{}, at interface{}) *MockRefreshTokenRepository_RevokeChildren_Call {
	return &MockRefreshTokenRepository_RevokeChildren_Call{Call: _e.mock.On("RevokeChildren", ctx, parentID, at)}
}

func (_c *MockRefreshTokenRepository_RevokeChildren_Call) Run(run func(ctx context.Context, parentID uuid.UUID, at time.Time)) *MockRefreshTokenRepository_RevokeChildren_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_RevokeChildren_Call) Return(_a0 error) *MockRefreshTokenRepository_RevokeChildren_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshTokenRepository_RevokeChildren_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time) error) *MockRefreshTokenRepository_RevokeChildren_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRefreshTokenRepository creates a new instance of MockRefreshTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRefreshTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRefreshTokenRepository {
	mock := &MockRefreshTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
