// Code generated by mockery v2.53.6. DO NOT EDIT.

package mockdomain

import (
	context "context"

	domain "github.com/alfariesh/backend-quiz/internal/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// MockEmailVerificationRepository is an autogenerated mock type for the EmailVerificationRepository type
type MockEmailVerificationRepository struct {
	mock.Mock
}

type MockEmailVerificationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmailVerificationRepository) EXPECT() *MockEmailVerificationRepository_Expecter {
	return &MockEmailVerificationRepository_Expecter{mock: &_m.Mock}
}

// Consume provides a mock function with given fields: ctx, id, at
func (_m *MockEmailVerificationRepository) Consume(ctx context.Context, id uuid.UUID, at time.Time) error {
	ret := _m.Called(ctx, id, at)

	if len(ret) == 0 {
		panic("no return value specified for Consume")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r0 = rf(ctx, id, at)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEmailVerificationRepository_Consume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Consume'
type MockEmailVerificationRepository_Consume_Call struct {
	*mock.Call
}

// Consume is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - at time.Time
func (_e *MockEmailVerificationRepository_Expecter) Consume(ctx interface{}, id interface{}, at interface{}) *MockEmailVerificationRepository_Consume_Call {
	return &MockEmailVerificationRepository_Consume_Call{Call: _e.mock.On("Consume", ctx, id, at)}
}

func (_c *MockEmailVerificationRepository_Consume_Call) Run(run func(ctx context.Context, id uuid.UUID, at time.Time)) *MockEmailVerificationRepository_Consume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockEmailVerificationRepository_Consume_Call) Return(_a0 error) *MockEmailVerificationRepository_Consume_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEmailVerificationRepository_Consume_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time) error) *MockEmailVerificationRepository_Consume_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, ev
func (_m *MockEmailVerificationRepository) Create(ctx context.Context, ev *domain.EmailVerification) error {
	ret := _m.Called(ctx, ev)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.EmailVerification) error); ok {
		r0 = rf(ctx, ev)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEmailVerificationRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockEmailVerificationRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - ev *domain.EmailVerification
func (_e *MockEmailVerificationRepository_Expecter) Create(ctx interface{}, ev interface{}) *MockEmailVerificationRepository_Create_Call {
	return &MockEmailVerificationRepository_Create_Call{Call: _e.mock.On("Create", ctx, ev)}
}

func (_c *MockEmailVerificationRepository_Create_Call) Run(run func(ctx context.Context, ev *domain.EmailVerification)) *MockEmailVerificationRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.EmailVerification))
	})
	return _c
}

func (_c *MockEmailVerificationRepository_Create_Call) Return(_a0 error) *MockEmailVerificationRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEmailVerificationRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.EmailVerification) error) *MockEmailVerificationRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByUserID provides a mock function with given fields: ctx, userID
func (_m *MockEmailVerificationRepository) DeleteByUserID(ctx context.Context, userID uuid.UUID) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByUserID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEmailVerificationRepository_DeleteByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByUserID'
type MockEmailVerificationRepository_DeleteByUserID_Call struct {
	*mock.Call
}

// DeleteByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockEmailVerificationRepository_Expecter) DeleteByUserID(ctx interface{}, userID interface{}) *MockEmailVerificationRepository_DeleteByUserID_Call {
	return &MockEmailVerificationRepository_DeleteByUserID_Call{Call: _e.mock.On("DeleteByUserID", ctx, userID)}
}

func (_c *MockEmailVerificationRepository_DeleteByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockEmailVerificationRepository_DeleteByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockEmailVerificationRepository_DeleteByUserID_Call) Return(_a0 error) *MockEmailVerificationRepository_DeleteByUserID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEmailVerificationRepository_DeleteByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockEmailVerificationRepository_DeleteByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveByUserID provides a mock function with given fields: ctx, userID
func (_m *MockEmailVerificationRepository) GetActiveByUserID(ctx context.Context, userID uuid.UUID) (*domain.EmailVerification, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveByUserID")
	}

	var r0 *domain.EmailVerification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.EmailVerification, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.EmailVerification); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.EmailVerification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEmailVerificationRepository_GetActiveByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveByUserID'
type MockEmailVerificationRepository_GetActiveByUserID_Call struct {
	*mock.Call
}

// GetActiveByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockEmailVerificationRepository_Expecter) GetActiveByUserID(ctx interface{}, userID interface{}) *MockEmailVerificationRepository_GetActiveByUserID_Call {
	return &MockEmailVerificationRepository_GetActiveByUserID_Call{Call: _e.mock.On("GetActiveByUserID", ctx, userID)}
}

func (_c *MockEmailVerificationRepository_GetActiveByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockEmailVerificationRepository_GetActiveByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockEmailVerificationRepository_GetActiveByUserID_Call) Return(_a0 *domain.EmailVerification, _a1 error) *MockEmailVerificationRepository_GetActiveByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEmailVerificationRepository_GetActiveByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.EmailVerification, error)) *MockEmailVerificationRepository_GetActiveByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementAttempts provides a mock function with given fields: ctx, id
func (_m *MockEmailVerificationRepository) IncrementAttempts(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for IncrementAttempts")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEmailVerificationRepository_IncrementAttempts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementAttempts'
type MockEmailVerificationRepository_IncrementAttempts_Call struct {
	*mock.Call
}

// IncrementAttempts is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockEmailVerificationRepository_Expecter) IncrementAttempts(ctx interface{}, id interface{}) *MockEmailVerificationRepository_IncrementAttempts_Call {
	return &MockEmailVerificationRepository_IncrementAttempts_Call{Call: _e.mock.On("IncrementAttempts", ctx, id)}
}

func (_c *MockEmailVerificationRepository_IncrementAttempts_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockEmailVerificationRepository_IncrementAttempts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockEmailVerificationRepository_IncrementAttempts_Call) Return(_a0 error) *MockEmailVerificationRepository_IncrementAttempts_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEmailVerificationRepository_IncrementAttempts_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockEmailVerificationRepository_IncrementAttempts_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEmailVerificationRepository creates a new instance of MockEmailVerificationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmailVerificationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmailVerificationRepository {
	mock := &MockEmailVerificationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
