// Code generated by mockery v2.53.6. DO NOT EDIT.

package mockdomain

import (
	context "context"

	domain "github.com/alfariesh/backend-quiz/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockGoalRepository is an autogenerated mock type for the GoalRepository type
type MockGoalRepository struct {
	mock.Mock
}

type MockGoalRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGoalRepository) EXPECT() *MockGoalRepository_Expecter {
	return &MockGoalRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockGoalRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGoalRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockGoalRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockGoalRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockGoalRepository_Delete_Call {
	return &MockGoalRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockGoalRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockGoalRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockGoalRepository_Delete_Call) Return(_a0 error) *MockGoalRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGoalRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockGoalRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockGoalRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.StudyGoal, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.StudyGoal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.StudyGoal, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.StudyGoal); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.StudyGoal)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoalRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockGoalRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockGoalRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockGoalRepository_GetByID_Call {
	return &MockGoalRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockGoalRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockGoalRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockGoalRepository_GetByID_Call) Return(_a0 *domain.StudyGoal, _a1 error) *MockGoalRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoalRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.StudyGoal, error)) *MockGoalRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUserID provides a mock function with given fields: ctx, userID
func (_m *MockGoalRepository) ListByUserID(ctx context.Context, userID uuid.UUID) ([]domain.StudyGoal, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUserID")
	}

	var r0 []domain.StudyGoal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]domain.StudyGoal, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []domain.StudyGoal); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.StudyGoal)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoalRepository_ListByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUserID'
type MockGoalRepository_ListByUserID_Call struct {
	*mock.Call
}

// ListByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockGoalRepository_Expecter) ListByUserID(ctx interface{}, userID interface{}) *MockGoalRepository_ListByUserID_Call {
	return &MockGoalRepository_ListByUserID_Call{Call: _e.mock.On("ListByUserID", ctx, userID)}
}

func (_c *MockGoalRepository_ListByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockGoalRepository_ListByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockGoalRepository_ListByUserID_Call) Return(_a0 []domain.StudyGoal, _a1 error) *MockGoalRepository_ListByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoalRepository_ListByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]domain.StudyGoal, error)) *MockGoalRepository_ListByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function with given fields: ctx, goal
func (_m *MockGoalRepository) Upsert(ctx context.Context, goal *domain.StudyGoal) error {
	ret := _m.Called(ctx, goal)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.StudyGoal) error); ok {
		r0 = rf(ctx, goal)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGoalRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockGoalRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - goal *domain.StudyGoal
func (_e *MockGoalRepository_Expecter) Upsert(ctx interface{}, goal interface{}) *MockGoalRepository_Upsert_Call {
	return &MockGoalRepository_Upsert_Call{Call: _e.mock.On("Upsert", ctx, goal)}
}

func (_c *MockGoalRepository_Upsert_Call) Run(run func(ctx context.Context, goal *domain.StudyGoal)) *MockGoalRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.StudyGoal))
	})
	return _c
}

func (_c *MockGoalRepository_Upsert_Call) Return(_a0 error) *MockGoalRepository_Upsert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGoalRepository_Upsert_Call) RunAndReturn(run func(context.Context, *domain.StudyGoal) error) *MockGoalRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGoalRepository creates a new instance of MockGoalRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGoalRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGoalRepository {
	mock := &MockGoalRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
