// Code generated by mockery v2.53.6. DO NOT EDIT.

package mockdomain

import (
	context "context"

	domain "github.com/alfariesh/backend-quiz/internal/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// CancelDeletion provides a mock function with given fields: ctx, userID
func (_m *MockUserRepository) CancelDeletion(ctx context.Context, userID uuid.UUID) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CancelDeletion")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_CancelDeletion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelDeletion'
type MockUserRepository_CancelDeletion_Call struct {
	*mock.Call
}

// CancelDeletion is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockUserRepository_Expecter) CancelDeletion(ctx interface{}, userID interface{}) *MockUserRepository_CancelDeletion_Call {
	return &MockUserRepository_CancelDeletion_Call{Call: _e.mock.On("CancelDeletion", ctx, userID)}
}

func (_c *MockUserRepository_CancelDeletion_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockUserRepository_CancelDeletion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUserRepository_CancelDeletion_Call) Return(_a0 error) *MockUserRepository_CancelDeletion_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_CancelDeletion_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockUserRepository_CancelDeletion_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, user
func (_m *MockUserRepository) Create(ctx context.Context, user *domain.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - user *domain.User
func (_e *MockUserRepository_Expecter) Create(ctx interface{}, user interface{}) *MockUserRepository_Create_Call {
	return &MockUserRepository_Create_Call{Call: _e.mock.On("Create", ctx, user)}
}

func (_c *MockUserRepository_Create_Call) Run(run func(ctx context.Context, user *domain.User)) *MockUserRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.User))
	})
	return _c
}

func (_c *MockUserRepository_Create_Call) Return(_a0 error) *MockUserRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.User) error) *MockUserRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOAuthAccount provides a mock function with given fields: ctx, account
func (_m *MockUserRepository) CreateOAuthAccount(ctx context.Context, account *domain.OAuthAccount) error {
	ret := _m.Called(ctx, account)

	if len(ret) == 0 {
		panic("no return value specified for CreateOAuthAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.OAuthAccount) error); ok {
		r0 = rf(ctx, account)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_CreateOAuthAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOAuthAccount'
type MockUserRepository_CreateOAuthAccount_Call struct {
	*mock.Call
}

// CreateOAuthAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - account *domain.OAuthAccount
func (_e *MockUserRepository_Expecter) CreateOAuthAccount(ctx interface{}, account interface{}) *MockUserRepository_CreateOAuthAccount_Call {
	return &MockUserRepository_CreateOAuthAccount_Call{Call: _e.mock.On("CreateOAuthAccount", ctx, account)}
}

func (_c *MockUserRepository_CreateOAuthAccount_Call) Run(run func(ctx context.Context, account *domain.OAuthAccount)) *MockUserRepository_CreateOAuthAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.OAuthAccount))
	})
	return _c
}

func (_c *MockUserRepository_CreateOAuthAccount_Call) Return(_a0 error) *MockUserRepository_CreateOAuthAccount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_CreateOAuthAccount_Call) RunAndReturn(run func(context.Context, *domain.OAuthAccount) error) *MockUserRepository_CreateOAuthAccount_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockUserRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockUserRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUserRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockUserRepository_Delete_Call {
	return &MockUserRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockUserRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUserRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUserRepository_Delete_Call) Return(_a0 error) *MockUserRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockUserRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByEmail provides a mock function with given fields: ctx, email
func (_m *MockUserRepository) GetByEmail(ctx context.Context, email string) (*domain.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type MockUserRepository_GetByEmail_Call struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserRepository_Expecter) GetByEmail(ctx interface{}, email interface{}) *MockUserRepository_GetByEmail_Call {
	return &MockUserRepository_GetByEmail_Call{Call: _e.mock.On("GetByEmail", ctx, email)}
}

func (_c *MockUserRepository_GetByEmail_Call) Run(run func(ctx context.Context, email string)) *MockUserRepository_GetByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRepository_GetByEmail_Call) Return(_a0 *domain.User, _a1 error) *MockUserRepository_GetByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_GetByEmail_Call) RunAndReturn(run func(context.Context, string) (*domain.User, error)) *MockUserRepository_GetByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockUserRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockUserRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUserRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockUserRepository_GetByID_Call {
	return &MockUserRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockUserRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUserRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUserRepository_GetByID_Call) Return(_a0 *domain.User, _a1 error) *MockUserRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.User, error)) *MockUserRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetOAuthAccount provides a mock function with given fields: ctx, provider, providerID
func (_m *MockUserRepository) GetOAuthAccount(ctx context.Context, provider string, providerID string) (*domain.OAuthAccount, error) {
	ret := _m.Called(ctx, provider, providerID)

	if len(ret) == 0 {
		panic("no return value specified for GetOAuthAccount")
	}

	var r0 *domain.OAuthAccount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.OAuthAccount, error)); ok {
		return rf(ctx, provider, providerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.OAuthAccount); ok {
		r0 = rf(ctx, provider, providerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.OAuthAccount)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, provider, providerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_GetOAuthAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOAuthAccount'
type MockUserRepository_GetOAuthAccount_Call struct {
	*mock.Call
}

// GetOAuthAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - provider string
//   - providerID string
func (_e *MockUserRepository_Expecter) GetOAuthAccount(ctx interface{}, provider interface{}, providerID interface{}) *MockUserRepository_GetOAuthAccount_Call {
	return &MockUserRepository_GetOAuthAccount_Call{Call: _e.mock.On("GetOAuthAccount", ctx, provider, providerID)}
}

func (_c *MockUserRepository_GetOAuthAccount_Call) Run(run func(ctx context.Context, provider string, providerID string)) *MockUserRepository_GetOAuthAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockUserRepository_GetOAuthAccount_Call) Return(_a0 *domain.OAuthAccount, _a1 error) *MockUserRepository_GetOAuthAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_GetOAuthAccount_Call) RunAndReturn(run func(context.Context, string, string) (*domain.OAuthAccount, error)) *MockUserRepository_GetOAuthAccount_Call {
	_c.Call.Return(run)
	return _c
}

// ListExpiredDeletions provides a mock function with given fields: ctx, before, limit
func (_m *MockUserRepository) ListExpiredDeletions(ctx context.Context, before time.Time, limit int) ([]uuid.UUID, error) {
	ret := _m.Called(ctx, before, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListExpiredDeletions")
	}

	var r0 []uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, int) ([]uuid.UUID, error)); ok {
		return rf(ctx, before, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, int) []uuid.UUID); ok {
		r0 = rf(ctx, before, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, int) error); ok {
		r1 = rf(ctx, before, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_ListExpiredDeletions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListExpiredDeletions'
type MockUserRepository_ListExpiredDeletions_Call struct {
	*mock.Call
}

// ListExpiredDeletions is a helper method to define mock.On call
//   - ctx context.Context
//   - before time.Time
//   - limit int
func (_e *MockUserRepository_Expecter) ListExpiredDeletions(ctx interface{}, before interface{}, limit interface{}) *MockUserRepository_ListExpiredDeletions_Call {
	return &MockUserRepository_ListExpiredDeletions_Call{Call: _e.mock.On("ListExpiredDeletions", ctx, before, limit)}
}

func (_c *MockUserRepository_ListExpiredDeletions_Call) Run(run func(ctx context.Context, before time.Time, limit int)) *MockUserRepository_ListExpiredDeletions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time), args[2].(int))
	})
	return _c
}

func (_c *MockUserRepository_ListExpiredDeletions_Call) Return(_a0 []uuid.UUID, _a1 error) *MockUserRepository_ListExpiredDeletions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_ListExpiredDeletions_Call) RunAndReturn(run func(context.Context, time.Time, int) ([]uuid.UUID, error)) *MockUserRepository_ListExpiredDeletions_Call {
	_c.Call.Return(run)
	return _c
}

// ListOAuthAccountsByUser provides a mock function with given fields: ctx, userID
func (_m *MockUserRepository) ListOAuthAccountsByUser(ctx context.Context, userID uuid.UUID) ([]domain.OAuthAccount, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListOAuthAccountsByUser")
	}

	var r0 []domain.OAuthAccount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]domain.OAuthAccount, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []domain.OAuthAccount); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.OAuthAccount)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_ListOAuthAccountsByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListOAuthAccountsByUser'
type MockUserRepository_ListOAuthAccountsByUser_Call struct {
	*mock.Call
}

// ListOAuthAccountsByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockUserRepository_Expecter) ListOAuthAccountsByUser(ctx interface{}, userID interface{}) *MockUserRepository_ListOAuthAccountsByUser_Call {
	return &MockUserRepository_ListOAuthAccountsByUser_Call{Call: _e.mock.On("ListOAuthAccountsByUser", ctx, userID)}
}

func (_c *MockUserRepository_ListOAuthAccountsByUser_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockUserRepository_ListOAuthAccountsByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUserRepository_ListOAuthAccountsByUser_Call) Return(_a0 []domain.OAuthAccount, _a1 error) *MockUserRepository_ListOAuthAccountsByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_ListOAuthAccountsByUser_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]domain.OAuthAccount, error)) *MockUserRepository_ListOAuthAccountsByUser_Call {
	_c.Call.Return(run)
	return _c
}

// MarkEmailVerified provides a mock function with given fields: ctx, userID, at
func (_m *MockUserRepository) MarkEmailVerified(ctx context.Context, userID uuid.UUID, at time.Time) error {
	ret := _m.Called(ctx, userID, at)

	if len(ret) == 0 {
		panic("no return value specified for MarkEmailVerified")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r0 = rf(ctx, userID, at)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_MarkEmailVerified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkEmailVerified'
type MockUserRepository_MarkEmailVerified_Call struct {
	*mock.Call
}

// MarkEmailVerified is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - at time.Time
func (_e *MockUserRepository_Expecter) MarkEmailVerified(ctx interface{}, userID interface{}, at interface{}) *MockUserRepository_MarkEmailVerified_Call {
	return &MockUserRepository_MarkEmailVerified_Call{Call: _e.mock.On("MarkEmailVerified", ctx, userID, at)}
}

func (_c *MockUserRepository_MarkEmailVerified_Call) Run(run func(ctx context.Context, userID uuid.UUID, at time.Time)) *MockUserRepository_MarkEmailVerified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockUserRepository_MarkEmailVerified_Call) Return(_a0 error) *MockUserRepository_MarkEmailVerified_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_MarkEmailVerified_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time) error) *MockUserRepository_MarkEmailVerified_Call {
	_c.Call.Return(run)
	return _c
}

// RequestDeletion provides a mock function with given fields: ctx, userID, at
func (_m *MockUserRepository) RequestDeletion(ctx context.Context, userID uuid.UUID, at time.Time) error {
	ret := _m.Called(ctx, userID, at)

	if len(ret) == 0 {
		panic("no return value specified for RequestDeletion")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r0 = rf(ctx, userID, at)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_RequestDeletion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestDeletion'
type MockUserRepository_RequestDeletion_Call struct {
	*mock.Call
}

// RequestDeletion is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - at time.Time
func (_e *MockUserRepository_Expecter) RequestDeletion(ctx interface{}, userID interface{}, at interface{}) *MockUserRepository_RequestDeletion_Call {
	return &MockUserRepository_RequestDeletion_Call{Call: _e.mock.On("RequestDeletion", ctx, userID, at)}
}

func (_c *MockUserRepository_RequestDeletion_Call) Run(run func(ctx context.Context, userID uuid.UUID, at time.Time)) *MockUserRepository_RequestDeletion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockUserRepository_RequestDeletion_Call) Return(_a0 error) *MockUserRepository_RequestDeletion_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_RequestDeletion_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time) error) *MockUserRepository_RequestDeletion_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, user
func (_m *MockUserRepository) Update(ctx context.Context, user *domain.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUserRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - user *domain.User
func (_e *MockUserRepository_Expecter) Update(ctx interface{}, user interface{}) *MockUserRepository_Update_Call {
	return &MockUserRepository_Update_Call{Call: _e.mock.On("Update", ctx, user)}
}

func (_c *MockUserRepository_Update_Call) Run(run func(ctx context.Context, user *domain.User)) *MockUserRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.User))
	})
	return _c
}

func (_c *MockUserRepository_Update_Call) Return(_a0 error) *MockUserRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.User) error) *MockUserRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePassword provides a mock function with given fields: ctx, userID, passwordHash
func (_m *MockUserRepository) UpdatePassword(ctx context.Context, userID uuid.UUID, passwordHash string) error {
	ret := _m.Called(ctx, userID, passwordHash)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, userID, passwordHash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_UpdatePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePassword'
type MockUserRepository_UpdatePassword_Call struct {
	*mock.Call
}

// UpdatePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - passwordHash string
func (_e *MockUserRepository_Expecter) UpdatePassword(ctx interface{}, userID interface{}, passwordHash interface{}) *MockUserRepository_UpdatePassword_Call {
	return &MockUserRepository_UpdatePassword_Call{Call: _e.mock.On("UpdatePassword", ctx, userID, passwordHash)}
}

func (_c *MockUserRepository_UpdatePassword_Call) Run(run func(ctx context.Context, userID uuid.UUID, passwordHash string)) *MockUserRepository_UpdatePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockUserRepository_UpdatePassword_Call) Return(_a0 error) *MockUserRepository_UpdatePassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_UpdatePassword_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) error) *MockUserRepository_UpdatePassword_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
