// Code generated by mockery v2.53.6. DO NOT EDIT.

package mockdomain

import (
	context "context"

	io "io"

	mock "github.com/stretchr/testify/mock"
)

// MockObjectStore is an autogenerated mock type for the ObjectStore type
type MockObjectStore struct {
	mock.Mock
}

type MockObjectStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockObjectStore) EXPECT() *MockObjectStore_Expecter {
	return &MockObjectStore_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, key
func (_m *MockObjectStore) Delete(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockObjectStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockObjectStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockObjectStore_Expecter) Delete(ctx interface{}, key interface{}) *MockObjectStore_Delete_Call {
	return &MockObjectStore_Delete_Call{Call: _e.mock.On("Delete", ctx, key)}
}

func (_c *MockObjectStore_Delete_Call) Run(run func(ctx context.Context, key string)) *MockObjectStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockObjectStore_Delete_Call) Return(_a0 error) *MockObjectStore_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockObjectStore_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockObjectStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Upload provides a mock function with given fields: ctx, key, body, contentType
func (_m *MockObjectStore) Upload(ctx context.Context, key string, body io.Reader, contentType string) (string, error) {
	ret := _m.Called(ctx, key, body, contentType)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader, string) (string, error)); ok {
		return rf(ctx, key, body, contentType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader, string) string); ok {
		r0 = rf(ctx, key, body, contentType)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, io.Reader, string) error); ok {
		r1 = rf(ctx, key, body, contentType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockObjectStore_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockObjectStore_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - body io.Reader
//   - contentType string
func (_e *MockObjectStore_Expecter) Upload(ctx interface{}, key interface{}, body interface{}, contentType interface{}) *MockObjectStore_Upload_Call {
	return &MockObjectStore_Upload_Call{Call: _e.mock.On("Upload", ctx, key, body, contentType)}
}

func (_c *MockObjectStore_Upload_Call) Run(run func(ctx context.Context, key string, body io.Reader, contentType string)) *MockObjectStore_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(io.Reader), args[3].(string))
	})
	return _c
}

func (_c *MockObjectStore_Upload_Call) Return(url string, err error) *MockObjectStore_Upload_Call {
	_c.Call.Return(url, err)
	return _c
}

func (_c *MockObjectStore_Upload_Call) RunAndReturn(run func(context.Context, string, io.Reader, string) (string, error)) *MockObjectStore_Upload_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockObjectStore creates a new instance of MockObjectStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockObjectStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockObjectStore {
	mock := &MockObjectStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
