// Code generated by mockery v2.53.6. DO NOT EDIT.

package mockdomain

import (
	context "context"

	domain "github.com/alfariesh/backend-quiz/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockStudySessionRepository is an autogenerated mock type for the StudySessionRepository type
type MockStudySessionRepository struct {
	mock.Mock
}

type MockStudySessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStudySessionRepository) EXPECT() *MockStudySessionRepository_Expecter {
	return &MockStudySessionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, session
func (_m *MockStudySessionRepository) Create(ctx context.Context, session *domain.StudySession) error {
	ret := _m.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.StudySession) error); ok {
		r0 = rf(ctx, session)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStudySessionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockStudySessionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - session *domain.StudySession
func (_e *MockStudySessionRepository_Expecter) Create(ctx interface{}, session interface{}) *MockStudySessionRepository_Create_Call {
	return &MockStudySessionRepository_Create_Call{Call: _e.mock.On("Create", ctx, session)}
}

func (_c *MockStudySessionRepository_Create_Call) Run(run func(ctx context.Context, session *domain.StudySession)) *MockStudySessionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.StudySession))
	})
	return _c
}

func (_c *MockStudySessionRepository_Create_Call) Return(_a0 error) *MockStudySessionRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStudySessionRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.StudySession) error) *MockStudySessionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockStudySessionRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.StudySession, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.StudySession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.StudySession, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.StudySession); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.StudySession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStudySessionRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockStudySessionRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockStudySessionRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockStudySessionRepository_GetByID_Call {
	return &MockStudySessionRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockStudySessionRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockStudySessionRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockStudySessionRepository_GetByID_Call) Return(_a0 *domain.StudySession, _a1 error) *MockStudySessionRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStudySessionRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.StudySession, error)) *MockStudySessionRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUserID provides a mock function with given fields: ctx, userID, limit, offset
func (_m *MockStudySessionRepository) ListByUserID(ctx context.Context, userID uuid.UUID, limit int, offset int) ([]domain.StudySession, int, error) {
	ret := _m.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListByUserID")
	}

	var r0 []domain.StudySession
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]domain.StudySession, int, error)); ok {
		return rf(ctx, userID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []domain.StudySession); ok {
		r0 = rf(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.StudySession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) int); ok {
		r1 = rf(ctx, userID, limit, offset)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, int, int) error); ok {
		r2 = rf(ctx, userID, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockStudySessionRepository_ListByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUserID'
type MockStudySessionRepository_ListByUserID_Call struct {
	*mock.Call
}

// ListByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - limit int
//   - offset int
func (_e *MockStudySessionRepository_Expecter) ListByUserID(ctx interface{}, userID interface{}, limit interface{}, offset interface{}) *MockStudySessionRepository_ListByUserID_Call {
	return &MockStudySessionRepository_ListByUserID_Call{Call: _e.mock.On("ListByUserID", ctx, userID, limit, offset)}
}

func (_c *MockStudySessionRepository_ListByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID, limit int, offset int)) *MockStudySessionRepository_ListByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockStudySessionRepository_ListByUserID_Call) Return(_a0 []domain.StudySession, _a1 int, _a2 error) *MockStudySessionRepository_ListByUserID_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockStudySessionRepository_ListByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, int) ([]domain.StudySession, int, error)) *MockStudySessionRepository_ListByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, session
func (_m *MockStudySessionRepository) Update(ctx context.Context, session *domain.StudySession) error {
	ret := _m.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.StudySession) error); ok {
		r0 = rf(ctx, session)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStudySessionRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockStudySessionRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - session *domain.StudySession
func (_e *MockStudySessionRepository_Expecter) Update(ctx interface{}, session interface{}) *MockStudySessionRepository_Update_Call {
	return &MockStudySessionRepository_Update_Call{Call: _e.mock.On("Update", ctx, session)}
}

func (_c *MockStudySessionRepository_Update_Call) Run(run func(ctx context.Context, session *domain.StudySession)) *MockStudySessionRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.StudySession))
	})
	return _c
}

func (_c *MockStudySessionRepository_Update_Call) Return(_a0 error) *MockStudySessionRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStudySessionRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.StudySession) error) *MockStudySessionRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStudySessionRepository creates a new instance of MockStudySessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStudySessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStudySessionRepository {
	mock := &MockStudySessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
