// Code generated by mockery v2.53.6. DO NOT EDIT.

package mockdomain

import (
	context "context"

	domain "github.com/rekanesiads/backend-quiz/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockQuizRepository is an autogenerated mock type for the QuizRepository type
type MockQuizRepository struct {
	mock.Mock
}

type MockQuizRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQuizRepository) EXPECT() *MockQuizRepository_Expecter {
	return &MockQuizRepository_Expecter{mock: &_m.Mock}
}

// BulkCreateQuestions provides a mock function with given fields: ctx, questions
func (_m *MockQuizRepository) BulkCreateQuestions(ctx context.Context, questions []*domain.QuizQuestion) error {
	ret := _m.Called(ctx, questions)

	if len(ret) == 0 {
		panic("no return value specified for BulkCreateQuestions")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*domain.QuizQuestion) error); ok {
		r0 = rf(ctx, questions)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuizRepository_BulkCreateQuestions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkCreateQuestions'
type MockQuizRepository_BulkCreateQuestions_Call struct {
	*mock.Call
}

// BulkCreateQuestions is a helper method to define mock.On call
//   - ctx context.Context
//   - questions []*domain.QuizQuestion
func (_e *MockQuizRepository_Expecter) BulkCreateQuestions(ctx interface{}, questions interface{}) *MockQuizRepository_BulkCreateQuestions_Call {
	return &MockQuizRepository_BulkCreateQuestions_Call{Call: _e.mock.On("BulkCreateQuestions", ctx, questions)}
}

func (_c *MockQuizRepository_BulkCreateQuestions_Call) Run(run func(ctx context.Context, questions []*domain.QuizQuestion)) *MockQuizRepository_BulkCreateQuestions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]*domain.QuizQuestion))
	})
	return _c
}

func (_c *MockQuizRepository_BulkCreateQuestions_Call) Return(_a0 error) *MockQuizRepository_BulkCreateQuestions_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuizRepository_BulkCreateQuestions_Call) RunAndReturn(run func(context.Context, []*domain.QuizQuestion) error) *MockQuizRepository_BulkCreateQuestions_Call {
	_c.Call.Return(run)
	return _c
}

// CountQuestionsByQuizID provides a mock function with given fields: ctx, quizID
func (_m *MockQuizRepository) CountQuestionsByQuizID(ctx context.Context, quizID uuid.UUID) (int, error) {
	ret := _m.Called(ctx, quizID)

	if len(ret) == 0 {
		panic("no return value specified for CountQuestionsByQuizID")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int, error)); ok {
		return rf(ctx, quizID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int); ok {
		r0 = rf(ctx, quizID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, quizID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuizRepository_CountQuestionsByQuizID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountQuestionsByQuizID'
type MockQuizRepository_CountQuestionsByQuizID_Call struct {
	*mock.Call
}

// CountQuestionsByQuizID is a helper method to define mock.On call
//   - ctx context.Context
//   - quizID uuid.UUID
func (_e *MockQuizRepository_Expecter) CountQuestionsByQuizID(ctx interface{}, quizID interface{}) *MockQuizRepository_CountQuestionsByQuizID_Call {
	return &MockQuizRepository_CountQuestionsByQuizID_Call{Call: _e.mock.On("CountQuestionsByQuizID", ctx, quizID)}
}

func (_c *MockQuizRepository_CountQuestionsByQuizID_Call) Run(run func(ctx context.Context, quizID uuid.UUID)) *MockQuizRepository_CountQuestionsByQuizID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockQuizRepository_CountQuestionsByQuizID_Call) Return(_a0 int, _a1 error) *MockQuizRepository_CountQuestionsByQuizID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuizRepository_CountQuestionsByQuizID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (int, error)) *MockQuizRepository_CountQuestionsByQuizID_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, quiz
func (_m *MockQuizRepository) Create(ctx context.Context, quiz *domain.Quiz) error {
	ret := _m.Called(ctx, quiz)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Quiz) error); ok {
		r0 = rf(ctx, quiz)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuizRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockQuizRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - quiz *domain.Quiz
func (_e *MockQuizRepository_Expecter) Create(ctx interface{}, quiz interface{}) *MockQuizRepository_Create_Call {
	return &MockQuizRepository_Create_Call{Call: _e.mock.On("Create", ctx, quiz)}
}

func (_c *MockQuizRepository_Create_Call) Run(run func(ctx context.Context, quiz *domain.Quiz)) *MockQuizRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Quiz))
	})
	return _c
}

func (_c *MockQuizRepository_Create_Call) Return(_a0 error) *MockQuizRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuizRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Quiz) error) *MockQuizRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateQuestion provides a mock function with given fields: ctx, q
func (_m *MockQuizRepository) CreateQuestion(ctx context.Context, q *domain.QuizQuestion) error {
	ret := _m.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for CreateQuestion")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.QuizQuestion) error); ok {
		r0 = rf(ctx, q)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuizRepository_CreateQuestion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateQuestion'
type MockQuizRepository_CreateQuestion_Call struct {
	*mock.Call
}

// CreateQuestion is a helper method to define mock.On call
//   - ctx context.Context
//   - q *domain.QuizQuestion
func (_e *MockQuizRepository_Expecter) CreateQuestion(ctx interface{}, q interface{}) *MockQuizRepository_CreateQuestion_Call {
	return &MockQuizRepository_CreateQuestion_Call{Call: _e.mock.On("CreateQuestion", ctx, q)}
}

func (_c *MockQuizRepository_CreateQuestion_Call) Run(run func(ctx context.Context, q *domain.QuizQuestion)) *MockQuizRepository_CreateQuestion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.QuizQuestion))
	})
	return _c
}

func (_c *MockQuizRepository_CreateQuestion_Call) Return(_a0 error) *MockQuizRepository_CreateQuestion_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuizRepository_CreateQuestion_Call) RunAndReturn(run func(context.Context, *domain.QuizQuestion) error) *MockQuizRepository_CreateQuestion_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockQuizRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuizRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockQuizRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockQuizRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockQuizRepository_Delete_Call {
	return &MockQuizRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockQuizRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockQuizRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockQuizRepository_Delete_Call) Return(_a0 error) *MockQuizRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuizRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockQuizRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteQuestion provides a mock function with given fields: ctx, id
func (_m *MockQuizRepository) DeleteQuestion(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteQuestion")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuizRepository_DeleteQuestion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteQuestion'
type MockQuizRepository_DeleteQuestion_Call struct {
	*mock.Call
}

// DeleteQuestion is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockQuizRepository_Expecter) DeleteQuestion(ctx interface{}, id interface{}) *MockQuizRepository_DeleteQuestion_Call {
	return &MockQuizRepository_DeleteQuestion_Call{Call: _e.mock.On("DeleteQuestion", ctx, id)}
}

func (_c *MockQuizRepository_DeleteQuestion_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockQuizRepository_DeleteQuestion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockQuizRepository_DeleteQuestion_Call) Return(_a0 error) *MockQuizRepository_DeleteQuestion_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuizRepository_DeleteQuestion_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockQuizRepository_DeleteQuestion_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockQuizRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.Quiz, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Quiz
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Quiz, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Quiz); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Quiz)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuizRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockQuizRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockQuizRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockQuizRepository_GetByID_Call {
	return &MockQuizRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockQuizRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockQuizRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockQuizRepository_GetByID_Call) Return(_a0 *domain.Quiz, _a1 error) *MockQuizRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuizRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.Quiz, error)) *MockQuizRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetQuestionByID provides a mock function with given fields: ctx, id
func (_m *MockQuizRepository) GetQuestionByID(ctx context.Context, id uuid.UUID) (*domain.QuizQuestion, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetQuestionByID")
	}

	var r0 *domain.QuizQuestion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.QuizQuestion, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.QuizQuestion); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.QuizQuestion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuizRepository_GetQuestionByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQuestionByID'
type MockQuizRepository_GetQuestionByID_Call struct {
	*mock.Call
}

// GetQuestionByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockQuizRepository_Expecter) GetQuestionByID(ctx interface{}, id interface{}) *MockQuizRepository_GetQuestionByID_Call {
	return &MockQuizRepository_GetQuestionByID_Call{Call: _e.mock.On("GetQuestionByID", ctx, id)}
}

func (_c *MockQuizRepository_GetQuestionByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockQuizRepository_GetQuestionByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockQuizRepository_GetQuestionByID_Call) Return(_a0 *domain.QuizQuestion, _a1 error) *MockQuizRepository_GetQuestionByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuizRepository_GetQuestionByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.QuizQuestion, error)) *MockQuizRepository_GetQuestionByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByDeckAndType provides a mock function with given fields: ctx, deckID, quizType
func (_m *MockQuizRepository) ListByDeckAndType(ctx context.Context, deckID uuid.UUID, quizType string) ([]domain.Quiz, error) {
	ret := _m.Called(ctx, deckID, quizType)

	if len(ret) == 0 {
		panic("no return value specified for ListByDeckAndType")
	}

	var r0 []domain.Quiz
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) ([]domain.Quiz, error)); ok {
		return rf(ctx, deckID, quizType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) []domain.Quiz); ok {
		r0 = rf(ctx, deckID, quizType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Quiz)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, deckID, quizType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuizRepository_ListByDeckAndType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByDeckAndType'
type MockQuizRepository_ListByDeckAndType_Call struct {
	*mock.Call
}

// ListByDeckAndType is a helper method to define mock.On call
//   - ctx context.Context
//   - deckID uuid.UUID
//   - quizType string
func (_e *MockQuizRepository_Expecter) ListByDeckAndType(ctx interface{}, deckID interface{}, quizType interface{}) *MockQuizRepository_ListByDeckAndType_Call {
	return &MockQuizRepository_ListByDeckAndType_Call{Call: _e.mock.On("ListByDeckAndType", ctx, deckID, quizType)}
}

func (_c *MockQuizRepository_ListByDeckAndType_Call) Run(run func(ctx context.Context, deckID uuid.UUID, quizType string)) *MockQuizRepository_ListByDeckAndType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockQuizRepository_ListByDeckAndType_Call) Return(_a0 []domain.Quiz, _a1 error) *MockQuizRepository_ListByDeckAndType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuizRepository_ListByDeckAndType_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) ([]domain.Quiz, error)) *MockQuizRepository_ListByDeckAndType_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUserID provides a mock function with given fields: ctx, userID, limit, offset
func (_m *MockQuizRepository) ListByUserID(ctx context.Context, userID uuid.UUID, limit int, offset int) ([]domain.QuizWithCounts, int, error) {
	ret := _m.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListByUserID")
	}

	var r0 []domain.QuizWithCounts
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]domain.QuizWithCounts, int, error)); ok {
		return rf(ctx, userID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []domain.QuizWithCounts); ok {
		r0 = rf(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.QuizWithCounts)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) int); ok {
		r1 = rf(ctx, userID, limit, offset)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, int, int) error); ok {
		r2 = rf(ctx, userID, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockQuizRepository_ListByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUserID'
type MockQuizRepository_ListByUserID_Call struct {
	*mock.Call
}

// ListByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - limit int
//   - offset int
func (_e *MockQuizRepository_Expecter) ListByUserID(ctx interface{}, userID interface{}, limit interface{}, offset interface{}) *MockQuizRepository_ListByUserID_Call {
	return &MockQuizRepository_ListByUserID_Call{Call: _e.mock.On("ListByUserID", ctx, userID, limit, offset)}
}

func (_c *MockQuizRepository_ListByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID, limit int, offset int)) *MockQuizRepository_ListByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockQuizRepository_ListByUserID_Call) Return(_a0 []domain.QuizWithCounts, _a1 int, _a2 error) *MockQuizRepository_ListByUserID_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockQuizRepository_ListByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, int) ([]domain.QuizWithCounts, int, error)) *MockQuizRepository_ListByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// ListQuestionsByQuizID provides a mock function with given fields: ctx, quizID
func (_m *MockQuizRepository) ListQuestionsByQuizID(ctx context.Context, quizID uuid.UUID) ([]domain.QuizQuestion, error) {
	ret := _m.Called(ctx, quizID)

	if len(ret) == 0 {
		panic("no return value specified for ListQuestionsByQuizID")
	}

	var r0 []domain.QuizQuestion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]domain.QuizQuestion, error)); ok {
		return rf(ctx, quizID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []domain.QuizQuestion); ok {
		r0 = rf(ctx, quizID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.QuizQuestion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, quizID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuizRepository_ListQuestionsByQuizID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListQuestionsByQuizID'
type MockQuizRepository_ListQuestionsByQuizID_Call struct {
	*mock.Call
}

// ListQuestionsByQuizID is a helper method to define mock.On call
//   - ctx context.Context
//   - quizID uuid.UUID
func (_e *MockQuizRepository_Expecter) ListQuestionsByQuizID(ctx interface{}, quizID interface{}) *MockQuizRepository_ListQuestionsByQuizID_Call {
	return &MockQuizRepository_ListQuestionsByQuizID_Call{Call: _e.mock.On("ListQuestionsByQuizID", ctx, quizID)}
}

func (_c *MockQuizRepository_ListQuestionsByQuizID_Call) Run(run func(ctx context.Context, quizID uuid.UUID)) *MockQuizRepository_ListQuestionsByQuizID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockQuizRepository_ListQuestionsByQuizID_Call) Return(_a0 []domain.QuizQuestion, _a1 error) *MockQuizRepository_ListQuestionsByQuizID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuizRepository_ListQuestionsByQuizID_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]domain.QuizQuestion, error)) *MockQuizRepository_ListQuestionsByQuizID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, quiz
func (_m *MockQuizRepository) Update(ctx context.Context, quiz *domain.Quiz) error {
	ret := _m.Called(ctx, quiz)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Quiz) error); ok {
		r0 = rf(ctx, quiz)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuizRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockQuizRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - quiz *domain.Quiz
func (_e *MockQuizRepository_Expecter) Update(ctx interface{}, quiz interface{}) *MockQuizRepository_Update_Call {
	return &MockQuizRepository_Update_Call{Call: _e.mock.On("Update", ctx, quiz)}
}

func (_c *MockQuizRepository_Update_Call) Run(run func(ctx context.Context, quiz *domain.Quiz)) *MockQuizRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Quiz))
	})
	return _c
}

func (_c *MockQuizRepository_Update_Call) Return(_a0 error) *MockQuizRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuizRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.Quiz) error) *MockQuizRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateQuestion provides a mock function with given fields: ctx, q
func (_m *MockQuizRepository) UpdateQuestion(ctx context.Context, q *domain.QuizQuestion) error {
	ret := _m.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for UpdateQuestion")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.QuizQuestion) error); ok {
		r0 = rf(ctx, q)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuizRepository_UpdateQuestion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateQuestion'
type MockQuizRepository_UpdateQuestion_Call struct {
	*mock.Call
}

// UpdateQuestion is a helper method to define mock.On call
//   - ctx context.Context
//   - q *domain.QuizQuestion
func (_e *MockQuizRepository_Expecter) UpdateQuestion(ctx interface{}, q interface{}) *MockQuizRepository_UpdateQuestion_Call {
	return &MockQuizRepository_UpdateQuestion_Call{Call: _e.mock.On("UpdateQuestion", ctx, q)}
}

func (_c *MockQuizRepository_UpdateQuestion_Call) Run(run func(ctx context.Context, q *domain.QuizQuestion)) *MockQuizRepository_UpdateQuestion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.QuizQuestion))
	})
	return _c
}

func (_c *MockQuizRepository_UpdateQuestion_Call) Return(_a0 error) *MockQuizRepository_UpdateQuestion_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuizRepository_UpdateQuestion_Call) RunAndReturn(run func(context.Context, *domain.QuizQuestion) error) *MockQuizRepository_UpdateQuestion_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQuizRepository creates a new instance of MockQuizRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuizRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuizRepository {
	mock := &MockQuizRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
