// Code generated by mockery v2.53.6. DO NOT EDIT.

package mockdomain

import (
	context "context"

	domain "github.com/rekanesiads/backend-quiz/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockDeckRepository is an autogenerated mock type for the DeckRepository type
type MockDeckRepository struct {
	mock.Mock
}

type MockDeckRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeckRepository) EXPECT() *MockDeckRepository_Expecter {
	return &MockDeckRepository_Expecter{mock: &_m.Mock}
}

// CloneDeck provides a mock function with given fields: ctx, sourceDeckID, targetUserID, name
func (_m *MockDeckRepository) CloneDeck(ctx context.Context, sourceDeckID uuid.UUID, targetUserID uuid.UUID, name string) (*domain.Deck, error) {
	ret := _m.Called(ctx, sourceDeckID, targetUserID, name)

	if len(ret) == 0 {
		panic("no return value specified for CloneDeck")
	}

	var r0 *domain.Deck
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) (*domain.Deck, error)); ok {
		return rf(ctx, sourceDeckID, targetUserID, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) *domain.Deck); ok {
		r0 = rf(ctx, sourceDeckID, targetUserID, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Deck)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r1 = rf(ctx, sourceDeckID, targetUserID, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDeckRepository_CloneDeck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloneDeck'
type MockDeckRepository_CloneDeck_Call struct {
	*mock.Call
}

// CloneDeck is a helper method to define mock.On call
//   - ctx context.Context
//   - sourceDeckID uuid.UUID
//   - targetUserID uuid.UUID
//   - name string
func (_e *MockDeckRepository_Expecter) CloneDeck(ctx interface{}, sourceDeckID interface{}, targetUserID interface{}, name interface{}) *MockDeckRepository_CloneDeck_Call {
	return &MockDeckRepository_CloneDeck_Call{Call: _e.mock.On("CloneDeck", ctx, sourceDeckID, targetUserID, name)}
}

func (_c *MockDeckRepository_CloneDeck_Call) Run(run func(ctx context.Context, sourceDeckID uuid.UUID, targetUserID uuid.UUID, name string)) *MockDeckRepository_CloneDeck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string))
	})
	return _c
}

func (_c *MockDeckRepository_CloneDeck_Call) Return(_a0 *domain.Deck, _a1 error) *MockDeckRepository_CloneDeck_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDeckRepository_CloneDeck_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, string) (*domain.Deck, error)) *MockDeckRepository_CloneDeck_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, deck
func (_m *MockDeckRepository) Create(ctx context.Context, deck *domain.Deck) error {
	ret := _m.Called(ctx, deck)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Deck) error); ok {
		r0 = rf(ctx, deck)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDeckRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockDeckRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - deck *domain.Deck
func (_e *MockDeckRepository_Expecter) Create(ctx interface{}, deck interface{}) *MockDeckRepository_Create_Call {
	return &MockDeckRepository_Create_Call{Call: _e.mock.On("Create", ctx, deck)}
}

func (_c *MockDeckRepository_Create_Call) Run(run func(ctx context.Context, deck *domain.Deck)) *MockDeckRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Deck))
	})
	return _c
}

func (_c *MockDeckRepository_Create_Call) Return(_a0 error) *MockDeckRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDeckRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Deck) error) *MockDeckRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateShare provides a mock function with given fields: ctx, share
func (_m *MockDeckRepository) CreateShare(ctx context.Context, share *domain.DeckShare) error {
	ret := _m.Called(ctx, share)

	if len(ret) == 0 {
		panic("no return value specified for CreateShare")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.DeckShare) error); ok {
		r0 = rf(ctx, share)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDeckRepository_CreateShare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateShare'
type MockDeckRepository_CreateShare_Call struct {
	*mock.Call
}

// CreateShare is a helper method to define mock.On call
//   - ctx context.Context
//   - share *domain.DeckShare
func (_e *MockDeckRepository_Expecter) CreateShare(ctx interface{}, share interface{}) *MockDeckRepository_CreateShare_Call {
	return &MockDeckRepository_CreateShare_Call{Call: _e.mock.On("CreateShare", ctx, share)}
}

func (_c *MockDeckRepository_CreateShare_Call) Run(run func(ctx context.Context, share *domain.DeckShare)) *MockDeckRepository_CreateShare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.DeckShare))
	})
	return _c
}

func (_c *MockDeckRepository_CreateShare_Call) Return(_a0 error) *MockDeckRepository_CreateShare_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDeckRepository_CreateShare_Call) RunAndReturn(run func(context.Context, *domain.DeckShare) error) *MockDeckRepository_CreateShare_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockDeckRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDeckRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockDeckRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockDeckRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockDeckRepository_Delete_Call {
	return &MockDeckRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockDeckRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockDeckRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockDeckRepository_Delete_Call) Return(_a0 error) *MockDeckRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDeckRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockDeckRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteShare provides a mock function with given fields: ctx, deckID
func (_m *MockDeckRepository) DeleteShare(ctx context.Context, deckID uuid.UUID) error {
	ret := _m.Called(ctx, deckID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteShare")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, deckID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDeckRepository_DeleteShare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteShare'
type MockDeckRepository_DeleteShare_Call struct {
	*mock.Call
}

// DeleteShare is a helper method to define mock.On call
//   - ctx context.Context
//   - deckID uuid.UUID
func (_e *MockDeckRepository_Expecter) DeleteShare(ctx interface{}, deckID interface{}) *MockDeckRepository_DeleteShare_Call {
	return &MockDeckRepository_DeleteShare_Call{Call: _e.mock.On("DeleteShare", ctx, deckID)}
}

func (_c *MockDeckRepository_DeleteShare_Call) Run(run func(ctx context.Context, deckID uuid.UUID)) *MockDeckRepository_DeleteShare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockDeckRepository_DeleteShare_Call) Return(_a0 error) *MockDeckRepository_DeleteShare_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDeckRepository_DeleteShare_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockDeckRepository_DeleteShare_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockDeckRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.Deck, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Deck
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Deck, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Deck); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Deck)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDeckRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockDeckRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockDeckRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockDeckRepository_GetByID_Call {
	return &MockDeckRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockDeckRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockDeckRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockDeckRepository_GetByID_Call) Return(_a0 *domain.Deck, _a1 error) *MockDeckRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDeckRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.Deck, error)) *MockDeckRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetShareByCode provides a mock function with given fields: ctx, code
func (_m *MockDeckRepository) GetShareByCode(ctx context.Context, code string) (*domain.DeckShare, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for GetShareByCode")
	}

	var r0 *domain.DeckShare
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.DeckShare, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.DeckShare); ok {
		r0 = rf(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.DeckShare)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDeckRepository_GetShareByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetShareByCode'
type MockDeckRepository_GetShareByCode_Call struct {
	*mock.Call
}

// GetShareByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *MockDeckRepository_Expecter) GetShareByCode(ctx interface{}, code interface{}) *MockDeckRepository_GetShareByCode_Call {
	return &MockDeckRepository_GetShareByCode_Call{Call: _e.mock.On("GetShareByCode", ctx, code)}
}

func (_c *MockDeckRepository_GetShareByCode_Call) Run(run func(ctx context.Context, code string)) *MockDeckRepository_GetShareByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDeckRepository_GetShareByCode_Call) Return(_a0 *domain.DeckShare, _a1 error) *MockDeckRepository_GetShareByCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDeckRepository_GetShareByCode_Call) RunAndReturn(run func(context.Context, string) (*domain.DeckShare, error)) *MockDeckRepository_GetShareByCode_Call {
	_c.Call.Return(run)
	return _c
}

// GetShareByDeckID provides a mock function with given fields: ctx, deckID
func (_m *MockDeckRepository) GetShareByDeckID(ctx context.Context, deckID uuid.UUID) (*domain.DeckShare, error) {
	ret := _m.Called(ctx, deckID)

	if len(ret) == 0 {
		panic("no return value specified for GetShareByDeckID")
	}

	var r0 *domain.DeckShare
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.DeckShare, error)); ok {
		return rf(ctx, deckID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.DeckShare); ok {
		r0 = rf(ctx, deckID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.DeckShare)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, deckID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDeckRepository_GetShareByDeckID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetShareByDeckID'
type MockDeckRepository_GetShareByDeckID_Call struct {
	*mock.Call
}

// GetShareByDeckID is a helper method to define mock.On call
//   - ctx context.Context
//   - deckID uuid.UUID
func (_e *MockDeckRepository_Expecter) GetShareByDeckID(ctx interface{}, deckID interface{}) *MockDeckRepository_GetShareByDeckID_Call {
	return &MockDeckRepository_GetShareByDeckID_Call{Call: _e.mock.On("GetShareByDeckID", ctx, deckID)}
}

func (_c *MockDeckRepository_GetShareByDeckID_Call) Run(run func(ctx context.Context, deckID uuid.UUID)) *MockDeckRepository_GetShareByDeckID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockDeckRepository_GetShareByDeckID_Call) Return(_a0 *domain.DeckShare, _a1 error) *MockDeckRepository_GetShareByDeckID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDeckRepository_GetShareByDeckID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.DeckShare, error)) *MockDeckRepository_GetShareByDeckID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUserID provides a mock function with given fields: ctx, userID, limit, offset
func (_m *MockDeckRepository) ListByUserID(ctx context.Context, userID uuid.UUID, limit int, offset int) ([]domain.DeckWithCounts, int, error) {
	ret := _m.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListByUserID")
	}

	var r0 []domain.DeckWithCounts
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]domain.DeckWithCounts, int, error)); ok {
		return rf(ctx, userID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []domain.DeckWithCounts); ok {
		r0 = rf(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.DeckWithCounts)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) int); ok {
		r1 = rf(ctx, userID, limit, offset)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, int, int) error); ok {
		r2 = rf(ctx, userID, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockDeckRepository_ListByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUserID'
type MockDeckRepository_ListByUserID_Call struct {
	*mock.Call
}

// ListByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - limit int
//   - offset int
func (_e *MockDeckRepository_Expecter) ListByUserID(ctx interface{}, userID interface{}, limit interface{}, offset interface{}) *MockDeckRepository_ListByUserID_Call {
	return &MockDeckRepository_ListByUserID_Call{Call: _e.mock.On("ListByUserID", ctx, userID, limit, offset)}
}

func (_c *MockDeckRepository_ListByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID, limit int, offset int)) *MockDeckRepository_ListByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockDeckRepository_ListByUserID_Call) Return(_a0 []domain.DeckWithCounts, _a1 int, _a2 error) *MockDeckRepository_ListByUserID_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockDeckRepository_ListByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, int) ([]domain.DeckWithCounts, int, error)) *MockDeckRepository_ListByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// ListPublicDecks provides a mock function with given fields: ctx, search, limit, offset
func (_m *MockDeckRepository) ListPublicDecks(ctx context.Context, search string, limit int, offset int) ([]domain.DeckWithCounts, int, error) {
	ret := _m.Called(ctx, search, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListPublicDecks")
	}

	var r0 []domain.DeckWithCounts
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]domain.DeckWithCounts, int, error)); ok {
		return rf(ctx, search, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []domain.DeckWithCounts); ok {
		r0 = rf(ctx, search, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.DeckWithCounts)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) int); ok {
		r1 = rf(ctx, search, limit, offset)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int) error); ok {
		r2 = rf(ctx, search, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockDeckRepository_ListPublicDecks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPublicDecks'
type MockDeckRepository_ListPublicDecks_Call struct {
	*mock.Call
}

// ListPublicDecks is a helper method to define mock.On call
//   - ctx context.Context
//   - search string
//   - limit int
//   - offset int
func (_e *MockDeckRepository_Expecter) ListPublicDecks(ctx interface{}, search interface{}, limit interface{}, offset interface{}) *MockDeckRepository_ListPublicDecks_Call {
	return &MockDeckRepository_ListPublicDecks_Call{Call: _e.mock.On("ListPublicDecks", ctx, search, limit, offset)}
}

func (_c *MockDeckRepository_ListPublicDecks_Call) Run(run func(ctx context.Context, search string, limit int, offset int)) *MockDeckRepository_ListPublicDecks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockDeckRepository_ListPublicDecks_Call) Return(_a0 []domain.DeckWithCounts, _a1 int, _a2 error) *MockDeckRepository_ListPublicDecks_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockDeckRepository_ListPublicDecks_Call) RunAndReturn(run func(context.Context, string, int, int) ([]domain.DeckWithCounts, int, error)) *MockDeckRepository_ListPublicDecks_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, deck
func (_m *MockDeckRepository) Update(ctx context.Context, deck *domain.Deck) error {
	ret := _m.Called(ctx, deck)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Deck) error); ok {
		r0 = rf(ctx, deck)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDeckRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockDeckRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - deck *domain.Deck
func (_e *MockDeckRepository_Expecter) Update(ctx interface{}, deck interface{}) *MockDeckRepository_Update_Call {
	return &MockDeckRepository_Update_Call{Call: _e.mock.On("Update", ctx, deck)}
}

func (_c *MockDeckRepository_Update_Call) Run(run func(ctx context.Context, deck *domain.Deck)) *MockDeckRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Deck))
	})
	return _c
}

func (_c *MockDeckRepository_Update_Call) Return(_a0 error) *MockDeckRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDeckRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.Deck) error) *MockDeckRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDeckRepository creates a new instance of MockDeckRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeckRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeckRepository {
	mock := &MockDeckRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
