// Code generated by mockery v2.53.6. DO NOT EDIT.

package mockdomain

import (
	context "context"

	domain "github.com/rekanesiads/backend-quiz/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockMediaRepository is an autogenerated mock type for the MediaRepository type
type MockMediaRepository struct {
	mock.Mock
}

type MockMediaRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMediaRepository) EXPECT() *MockMediaRepository_Expecter {
	return &MockMediaRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, media
func (_m *MockMediaRepository) Create(ctx context.Context, media *domain.Media) error {
	ret := _m.Called(ctx, media)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Media) error); ok {
		r0 = rf(ctx, media)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMediaRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockMediaRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - media *domain.Media
func (_e *MockMediaRepository_Expecter) Create(ctx interface{}, media interface{}) *MockMediaRepository_Create_Call {
	return &MockMediaRepository_Create_Call{Call: _e.mock.On("Create", ctx, media)}
}

func (_c *MockMediaRepository_Create_Call) Run(run func(ctx context.Context, media *domain.Media)) *MockMediaRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Media))
	})
	return _c
}

func (_c *MockMediaRepository_Create_Call) Return(_a0 error) *MockMediaRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMediaRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Media) error) *MockMediaRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockMediaRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMediaRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockMediaRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockMediaRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockMediaRepository_Delete_Call {
	return &MockMediaRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockMediaRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockMediaRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockMediaRepository_Delete_Call) Return(_a0 error) *MockMediaRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMediaRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockMediaRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockMediaRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.Media, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Media
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Media, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Media); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Media)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMediaRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockMediaRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockMediaRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockMediaRepository_GetByID_Call {
	return &MockMediaRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockMediaRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockMediaRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockMediaRepository_GetByID_Call) Return(_a0 *domain.Media, _a1 error) *MockMediaRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMediaRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.Media, error)) *MockMediaRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByCardID provides a mock function with given fields: ctx, cardID
func (_m *MockMediaRepository) ListByCardID(ctx context.Context, cardID uuid.UUID) ([]domain.Media, error) {
	ret := _m.Called(ctx, cardID)

	if len(ret) == 0 {
		panic("no return value specified for ListByCardID")
	}

	var r0 []domain.Media
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]domain.Media, error)); ok {
		return rf(ctx, cardID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []domain.Media); ok {
		r0 = rf(ctx, cardID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Media)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, cardID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMediaRepository_ListByCardID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByCardID'
type MockMediaRepository_ListByCardID_Call struct {
	*mock.Call
}

// ListByCardID is a helper method to define mock.On call
//   - ctx context.Context
//   - cardID uuid.UUID
func (_e *MockMediaRepository_Expecter) ListByCardID(ctx interface{}, cardID interface{}) *MockMediaRepository_ListByCardID_Call {
	return &MockMediaRepository_ListByCardID_Call{Call: _e.mock.On("ListByCardID", ctx, cardID)}
}

func (_c *MockMediaRepository_ListByCardID_Call) Run(run func(ctx context.Context, cardID uuid.UUID)) *MockMediaRepository_ListByCardID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockMediaRepository_ListByCardID_Call) Return(_a0 []domain.Media, _a1 error) *MockMediaRepository_ListByCardID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMediaRepository_ListByCardID_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]domain.Media, error)) *MockMediaRepository_ListByCardID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMediaRepository creates a new instance of MockMediaRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMediaRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMediaRepository {
	mock := &MockMediaRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
