// Code generated by mockery v2.53.6. DO NOT EDIT.

package mockdomain

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockUserDataExportRepository is an autogenerated mock type for the UserDataExportRepository type
type MockUserDataExportRepository struct {
	mock.Mock
}

type MockUserDataExportRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserDataExportRepository) EXPECT() *MockUserDataExportRepository_Expecter {
	return &MockUserDataExportRepository_Expecter{mock: &_m.Mock}
}

// Dump provides a mock function with given fields: ctx, userID
func (_m *MockUserDataExportRepository) Dump(ctx context.Context, userID uuid.UUID) (map[string]interface{}, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Dump")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (map[string]interface{}, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) map[string]interface{}); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserDataExportRepository_Dump_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dump'
type MockUserDataExportRepository_Dump_Call struct {
	*mock.Call
}

// Dump is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockUserDataExportRepository_Expecter) Dump(ctx interface{}, userID interface{}) *MockUserDataExportRepository_Dump_Call {
	return &MockUserDataExportRepository_Dump_Call{Call: _e.mock.On("Dump", ctx, userID)}
}

func (_c *MockUserDataExportRepository_Dump_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockUserDataExportRepository_Dump_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUserDataExportRepository_Dump_Call) Return(_a0 map[string]interface{}, _a1 error) *MockUserDataExportRepository_Dump_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserDataExportRepository_Dump_Call) RunAndReturn(run func(context.Context, uuid.UUID) (map[string]interface{}, error)) *MockUserDataExportRepository_Dump_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserDataExportRepository creates a new instance of MockUserDataExportRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserDataExportRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserDataExportRepository {
	mock := &MockUserDataExportRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
