// Code generated by mockery v2.53.6. DO NOT EDIT.

package mockdomain

import (
	context "context"

	domain "github.com/alfariesh/backend-quiz/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockAuthAuditLogRepository is an autogenerated mock type for the AuthAuditLogRepository type
type MockAuthAuditLogRepository struct {
	mock.Mock
}

type MockAuthAuditLogRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthAuditLogRepository) EXPECT() *MockAuthAuditLogRepository_Expecter {
	return &MockAuthAuditLogRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, log
func (_m *MockAuthAuditLogRepository) Create(ctx context.Context, log *domain.AuthAuditLog) error {
	ret := _m.Called(ctx, log)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.AuthAuditLog) error); ok {
		r0 = rf(ctx, log)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthAuditLogRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAuthAuditLogRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - log *domain.AuthAuditLog
func (_e *MockAuthAuditLogRepository_Expecter) Create(ctx interface{}, log interface{}) *MockAuthAuditLogRepository_Create_Call {
	return &MockAuthAuditLogRepository_Create_Call{Call: _e.mock.On("Create", ctx, log)}
}

func (_c *MockAuthAuditLogRepository_Create_Call) Run(run func(ctx context.Context, log *domain.AuthAuditLog)) *MockAuthAuditLogRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.AuthAuditLog))
	})
	return _c
}

func (_c *MockAuthAuditLogRepository_Create_Call) Return(_a0 error) *MockAuthAuditLogRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthAuditLogRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.AuthAuditLog) error) *MockAuthAuditLogRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthAuditLogRepository creates a new instance of MockAuthAuditLogRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthAuditLogRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthAuditLogRepository {
	mock := &MockAuthAuditLogRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
