// Code generated by mockery v2.53.6. DO NOT EDIT.

package mockport

import (
	context "context"

	domain "github.com/rekanesiads/backend-quiz/internal/domain"
	dto "github.com/rekanesiads/backend-quiz/internal/dto"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockStatsServicer is an autogenerated mock type for the StatsServicer type
type MockStatsServicer struct {
	mock.Mock
}

type MockStatsServicer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStatsServicer) EXPECT() *MockStatsServicer_Expecter {
	return &MockStatsServicer_Expecter{mock: &_m.Mock}
}

// DeckStats provides a mock function with given fields: ctx, userID, deckID
func (_m *MockStatsServicer) DeckStats(ctx context.Context, userID uuid.UUID, deckID uuid.UUID) (map[string]interface{}, error) {
	ret := _m.Called(ctx, userID, deckID)

	if len(ret) == 0 {
		panic("no return value specified for DeckStats")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (map[string]interface{}, error)); ok {
		return rf(ctx, userID, deckID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) map[string]interface{}); ok {
		r0 = rf(ctx, userID, deckID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, userID, deckID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStatsServicer_DeckStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeckStats'
type MockStatsServicer_DeckStats_Call struct {
	*mock.Call
}

// DeckStats is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - deckID uuid.UUID
func (_e *MockStatsServicer_Expecter) DeckStats(ctx interface{}, userID interface{}, deckID interface{}) *MockStatsServicer_DeckStats_Call {
	return &MockStatsServicer_DeckStats_Call{Call: _e.mock.On("DeckStats", ctx, userID, deckID)}
}

func (_c *MockStatsServicer_DeckStats_Call) Run(run func(ctx context.Context, userID uuid.UUID, deckID uuid.UUID)) *MockStatsServicer_DeckStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockStatsServicer_DeckStats_Call) Return(_a0 map[string]interface{}, _a1 error) *MockStatsServicer_DeckStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStatsServicer_DeckStats_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (map[string]interface{}, error)) *MockStatsServicer_DeckStats_Call {
	_c.Call.Return(run)
	return _c
}

// Forecast provides a mock function with given fields: ctx, userID
func (_m *MockStatsServicer) Forecast(ctx context.Context, userID uuid.UUID) ([]dto.ForecastDay, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Forecast")
	}

	var r0 []dto.ForecastDay
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]dto.ForecastDay, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []dto.ForecastDay); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.ForecastDay)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStatsServicer_Forecast_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Forecast'
type MockStatsServicer_Forecast_Call struct {
	*mock.Call
}

// Forecast is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockStatsServicer_Expecter) Forecast(ctx interface{}, userID interface{}) *MockStatsServicer_Forecast_Call {
	return &MockStatsServicer_Forecast_Call{Call: _e.mock.On("Forecast", ctx, userID)}
}

func (_c *MockStatsServicer_Forecast_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockStatsServicer_Forecast_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockStatsServicer_Forecast_Call) Return(_a0 []dto.ForecastDay, _a1 error) *MockStatsServicer_Forecast_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStatsServicer_Forecast_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]dto.ForecastDay, error)) *MockStatsServicer_Forecast_Call {
	_c.Call.Return(run)
	return _c
}

// Heatmap provides a mock function with given fields: ctx, userID
func (_m *MockStatsServicer) Heatmap(ctx context.Context, userID uuid.UUID) ([]dto.HeatmapEntry, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Heatmap")
	}

	var r0 []dto.HeatmapEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]dto.HeatmapEntry, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []dto.HeatmapEntry); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.HeatmapEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStatsServicer_Heatmap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Heatmap'
type MockStatsServicer_Heatmap_Call struct {
	*mock.Call
}

// Heatmap is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockStatsServicer_Expecter) Heatmap(ctx interface{}, userID interface{}) *MockStatsServicer_Heatmap_Call {
	return &MockStatsServicer_Heatmap_Call{Call: _e.mock.On("Heatmap", ctx, userID)}
}

func (_c *MockStatsServicer_Heatmap_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockStatsServicer_Heatmap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockStatsServicer_Heatmap_Call) Return(_a0 []dto.HeatmapEntry, _a1 error) *MockStatsServicer_Heatmap_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStatsServicer_Heatmap_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]dto.HeatmapEntry, error)) *MockStatsServicer_Heatmap_Call {
	_c.Call.Return(run)
	return _c
}

// Leaderboard provides a mock function with given fields: ctx, limit
func (_m *MockStatsServicer) Leaderboard(ctx context.Context, limit int) ([]domain.LeaderboardEntry, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for Leaderboard")
	}

	var r0 []domain.LeaderboardEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]domain.LeaderboardEntry, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []domain.LeaderboardEntry); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.LeaderboardEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStatsServicer_Leaderboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Leaderboard'
type MockStatsServicer_Leaderboard_Call struct {
	*mock.Call
}

// Leaderboard is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *MockStatsServicer_Expecter) Leaderboard(ctx interface{}, limit interface{}) *MockStatsServicer_Leaderboard_Call {
	return &MockStatsServicer_Leaderboard_Call{Call: _e.mock.On("Leaderboard", ctx, limit)}
}

func (_c *MockStatsServicer_Leaderboard_Call) Run(run func(ctx context.Context, limit int)) *MockStatsServicer_Leaderboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockStatsServicer_Leaderboard_Call) Return(_a0 []domain.LeaderboardEntry, _a1 error) *MockStatsServicer_Leaderboard_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStatsServicer_Leaderboard_Call) RunAndReturn(run func(context.Context, int) ([]domain.LeaderboardEntry, error)) *MockStatsServicer_Leaderboard_Call {
	_c.Call.Return(run)
	return _c
}

// Mastery provides a mock function with given fields: ctx, userID
func (_m *MockStatsServicer) Mastery(ctx context.Context, userID uuid.UUID) ([]dto.DeckMastery, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Mastery")
	}

	var r0 []dto.DeckMastery
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]dto.DeckMastery, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []dto.DeckMastery); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.DeckMastery)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStatsServicer_Mastery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Mastery'
type MockStatsServicer_Mastery_Call struct {
	*mock.Call
}

// Mastery is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockStatsServicer_Expecter) Mastery(ctx interface{}, userID interface{}) *MockStatsServicer_Mastery_Call {
	return &MockStatsServicer_Mastery_Call{Call: _e.mock.On("Mastery", ctx, userID)}
}

func (_c *MockStatsServicer_Mastery_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockStatsServicer_Mastery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockStatsServicer_Mastery_Call) Return(_a0 []dto.DeckMastery, _a1 error) *MockStatsServicer_Mastery_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStatsServicer_Mastery_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]dto.DeckMastery, error)) *MockStatsServicer_Mastery_Call {
	_c.Call.Return(run)
	return _c
}

// Overview provides a mock function with given fields: ctx, userID
func (_m *MockStatsServicer) Overview(ctx context.Context, userID uuid.UUID) (*dto.OverviewStats, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Overview")
	}

	var r0 *dto.OverviewStats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*dto.OverviewStats, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *dto.OverviewStats); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.OverviewStats)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStatsServicer_Overview_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Overview'
type MockStatsServicer_Overview_Call struct {
	*mock.Call
}

// Overview is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockStatsServicer_Expecter) Overview(ctx interface{}, userID interface{}) *MockStatsServicer_Overview_Call {
	return &MockStatsServicer_Overview_Call{Call: _e.mock.On("Overview", ctx, userID)}
}

func (_c *MockStatsServicer_Overview_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockStatsServicer_Overview_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockStatsServicer_Overview_Call) Return(_a0 *dto.OverviewStats, _a1 error) *MockStatsServicer_Overview_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStatsServicer_Overview_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*dto.OverviewStats, error)) *MockStatsServicer_Overview_Call {
	_c.Call.Return(run)
	return _c
}

// TestComparison provides a mock function with given fields: ctx, userID, deckID
func (_m *MockStatsServicer) TestComparison(ctx context.Context, userID uuid.UUID, deckID uuid.UUID) (*dto.TestComparison, error) {
	ret := _m.Called(ctx, userID, deckID)

	if len(ret) == 0 {
		panic("no return value specified for TestComparison")
	}

	var r0 *dto.TestComparison
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*dto.TestComparison, error)); ok {
		return rf(ctx, userID, deckID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *dto.TestComparison); ok {
		r0 = rf(ctx, userID, deckID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.TestComparison)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, userID, deckID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStatsServicer_TestComparison_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TestComparison'
type MockStatsServicer_TestComparison_Call struct {
	*mock.Call
}

// TestComparison is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - deckID uuid.UUID
func (_e *MockStatsServicer_Expecter) TestComparison(ctx interface{}, userID interface{}, deckID interface{}) *MockStatsServicer_TestComparison_Call {
	return &MockStatsServicer_TestComparison_Call{Call: _e.mock.On("TestComparison", ctx, userID, deckID)}
}

func (_c *MockStatsServicer_TestComparison_Call) Run(run func(ctx context.Context, userID uuid.UUID, deckID uuid.UUID)) *MockStatsServicer_TestComparison_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockStatsServicer_TestComparison_Call) Return(_a0 *dto.TestComparison, _a1 error) *MockStatsServicer_TestComparison_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStatsServicer_TestComparison_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*dto.TestComparison, error)) *MockStatsServicer_TestComparison_Call {
	_c.Call.Return(run)
	return _c
}

// WeakAreas provides a mock function with given fields: ctx, userID
func (_m *MockStatsServicer) WeakAreas(ctx context.Context, userID uuid.UUID) (*dto.WeakAreasResponse, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for WeakAreas")
	}

	var r0 *dto.WeakAreasResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*dto.WeakAreasResponse, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *dto.WeakAreasResponse); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.WeakAreasResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStatsServicer_WeakAreas_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WeakAreas'
type MockStatsServicer_WeakAreas_Call struct {
	*mock.Call
}

// WeakAreas is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockStatsServicer_Expecter) WeakAreas(ctx interface{}, userID interface{}) *MockStatsServicer_WeakAreas_Call {
	return &MockStatsServicer_WeakAreas_Call{Call: _e.mock.On("WeakAreas", ctx, userID)}
}

func (_c *MockStatsServicer_WeakAreas_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockStatsServicer_WeakAreas_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockStatsServicer_WeakAreas_Call) Return(_a0 *dto.WeakAreasResponse, _a1 error) *MockStatsServicer_WeakAreas_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStatsServicer_WeakAreas_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*dto.WeakAreasResponse, error)) *MockStatsServicer_WeakAreas_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStatsServicer creates a new instance of MockStatsServicer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStatsServicer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStatsServicer {
	mock := &MockStatsServicer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
