// Code generated by mockery v2.53.6. DO NOT EDIT.

package mockport

import (
	context "context"

	domain "github.com/rekanesiads/backend-quiz/internal/domain"
	dto "github.com/rekanesiads/backend-quiz/internal/dto"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockMediaServicer is an autogenerated mock type for the MediaServicer type
type MockMediaServicer struct {
	mock.Mock
}

type MockMediaServicer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMediaServicer) EXPECT() *MockMediaServicer_Expecter {
	return &MockMediaServicer_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, userID, mediaID
func (_m *MockMediaServicer) Delete(ctx context.Context, userID uuid.UUID, mediaID uuid.UUID) error {
	ret := _m.Called(ctx, userID, mediaID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, userID, mediaID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMediaServicer_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockMediaServicer_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - mediaID uuid.UUID
func (_e *MockMediaServicer_Expecter) Delete(ctx interface{}, userID interface{}, mediaID interface{}) *MockMediaServicer_Delete_Call {
	return &MockMediaServicer_Delete_Call{Call: _e.mock.On("Delete", ctx, userID, mediaID)}
}

func (_c *MockMediaServicer_Delete_Call) Run(run func(ctx context.Context, userID uuid.UUID, mediaID uuid.UUID)) *MockMediaServicer_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockMediaServicer_Delete_Call) Return(_a0 error) *MockMediaServicer_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMediaServicer_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockMediaServicer_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// ListByCard provides a mock function with given fields: ctx, userID, cardID
func (_m *MockMediaServicer) ListByCard(ctx context.Context, userID uuid.UUID, cardID uuid.UUID) ([]domain.Media, error) {
	ret := _m.Called(ctx, userID, cardID)

	if len(ret) == 0 {
		panic("no return value specified for ListByCard")
	}

	var r0 []domain.Media
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]domain.Media, error)); ok {
		return rf(ctx, userID, cardID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []domain.Media); ok {
		r0 = rf(ctx, userID, cardID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Media)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, userID, cardID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMediaServicer_ListByCard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByCard'
type MockMediaServicer_ListByCard_Call struct {
	*mock.Call
}

// ListByCard is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - cardID uuid.UUID
func (_e *MockMediaServicer_Expecter) ListByCard(ctx interface{}, userID interface{}, cardID interface{}) *MockMediaServicer_ListByCard_Call {
	return &MockMediaServicer_ListByCard_Call{Call: _e.mock.On("ListByCard", ctx, userID, cardID)}
}

func (_c *MockMediaServicer_ListByCard_Call) Run(run func(ctx context.Context, userID uuid.UUID, cardID uuid.UUID)) *MockMediaServicer_ListByCard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockMediaServicer_ListByCard_Call) Return(_a0 []domain.Media, _a1 error) *MockMediaServicer_ListByCard_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMediaServicer_ListByCard_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) ([]domain.Media, error)) *MockMediaServicer_ListByCard_Call {
	_c.Call.Return(run)
	return _c
}

// Upload provides a mock function with given fields: ctx, userID, cardID, req
func (_m *MockMediaServicer) Upload(ctx context.Context, userID uuid.UUID, cardID uuid.UUID, req dto.UploadMediaRequest) (*domain.Media, error) {
	ret := _m.Called(ctx, userID, cardID, req)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 *domain.Media
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, dto.UploadMediaRequest) (*domain.Media, error)); ok {
		return rf(ctx, userID, cardID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, dto.UploadMediaRequest) *domain.Media); ok {
		r0 = rf(ctx, userID, cardID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Media)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, dto.UploadMediaRequest) error); ok {
		r1 = rf(ctx, userID, cardID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMediaServicer_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockMediaServicer_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - cardID uuid.UUID
//   - req dto.UploadMediaRequest
func (_e *MockMediaServicer_Expecter) Upload(ctx interface{}, userID interface{}, cardID interface{}, req interface{}) *MockMediaServicer_Upload_Call {
	return &MockMediaServicer_Upload_Call{Call: _e.mock.On("Upload", ctx, userID, cardID, req)}
}

func (_c *MockMediaServicer_Upload_Call) Run(run func(ctx context.Context, userID uuid.UUID, cardID uuid.UUID, req dto.UploadMediaRequest)) *MockMediaServicer_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(dto.UploadMediaRequest))
	})
	return _c
}

func (_c *MockMediaServicer_Upload_Call) Return(_a0 *domain.Media, _a1 error) *MockMediaServicer_Upload_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMediaServicer_Upload_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, dto.UploadMediaRequest) (*domain.Media, error)) *MockMediaServicer_Upload_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMediaServicer creates a new instance of MockMediaServicer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMediaServicer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMediaServicer {
	mock := &MockMediaServicer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
