// Code generated by mockery v2.53.6. DO NOT EDIT.

package mockport

import (
	context "context"

	domain "github.com/alfariesh/backend-quiz/internal/domain"
	dto "github.com/alfariesh/backend-quiz/internal/dto"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockStudyServicer is an autogenerated mock type for the StudyServicer type
type MockStudyServicer struct {
	mock.Mock
}

type MockStudyServicer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStudyServicer) EXPECT() *MockStudyServicer_Expecter {
	return &MockStudyServicer_Expecter{mock: &_m.Mock}
}

// BatchReview provides a mock function with given fields: ctx, userID, sessionID, req
func (_m *MockStudyServicer) BatchReview(ctx context.Context, userID uuid.UUID, sessionID uuid.UUID, req dto.BatchReviewRequest) (*dto.BatchReviewResult, error) {
	ret := _m.Called(ctx, userID, sessionID, req)

	if len(ret) == 0 {
		panic("no return value specified for BatchReview")
	}

	var r0 *dto.BatchReviewResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, dto.BatchReviewRequest) (*dto.BatchReviewResult, error)); ok {
		return rf(ctx, userID, sessionID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, dto.BatchReviewRequest) *dto.BatchReviewResult); ok {
		r0 = rf(ctx, userID, sessionID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.BatchReviewResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, dto.BatchReviewRequest) error); ok {
		r1 = rf(ctx, userID, sessionID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStudyServicer_BatchReview_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchReview'
type MockStudyServicer_BatchReview_Call struct {
	*mock.Call
}

// BatchReview is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - sessionID uuid.UUID
//   - req dto.BatchReviewRequest
func (_e *MockStudyServicer_Expecter) BatchReview(ctx interface{}, userID interface{}, sessionID interface{}, req interface{}) *MockStudyServicer_BatchReview_Call {
	return &MockStudyServicer_BatchReview_Call{Call: _e.mock.On("BatchReview", ctx, userID, sessionID, req)}
}

func (_c *MockStudyServicer_BatchReview_Call) Run(run func(ctx context.Context, userID uuid.UUID, sessionID uuid.UUID, req dto.BatchReviewRequest)) *MockStudyServicer_BatchReview_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(dto.BatchReviewRequest))
	})
	return _c
}

func (_c *MockStudyServicer_BatchReview_Call) Return(_a0 *dto.BatchReviewResult, _a1 error) *MockStudyServicer_BatchReview_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStudyServicer_BatchReview_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, dto.BatchReviewRequest) (*dto.BatchReviewResult, error)) *MockStudyServicer_BatchReview_Call {
	_c.Call.Return(run)
	return _c
}

// EndSession provides a mock function with given fields: ctx, userID, sessionID
func (_m *MockStudyServicer) EndSession(ctx context.Context, userID uuid.UUID, sessionID uuid.UUID) (*domain.StudySession, error) {
	ret := _m.Called(ctx, userID, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for EndSession")
	}

	var r0 *domain.StudySession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*domain.StudySession, error)); ok {
		return rf(ctx, userID, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *domain.StudySession); ok {
		r0 = rf(ctx, userID, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.StudySession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, userID, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStudyServicer_EndSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EndSession'
type MockStudyServicer_EndSession_Call struct {
	*mock.Call
}

// EndSession is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - sessionID uuid.UUID
func (_e *MockStudyServicer_Expecter) EndSession(ctx interface{}, userID interface{}, sessionID interface{}) *MockStudyServicer_EndSession_Call {
	return &MockStudyServicer_EndSession_Call{Call: _e.mock.On("EndSession", ctx, userID, sessionID)}
}

func (_c *MockStudyServicer_EndSession_Call) Run(run func(ctx context.Context, userID uuid.UUID, sessionID uuid.UUID)) *MockStudyServicer_EndSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockStudyServicer_EndSession_Call) Return(_a0 *domain.StudySession, _a1 error) *MockStudyServicer_EndSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStudyServicer_EndSession_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*domain.StudySession, error)) *MockStudyServicer_EndSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetReminders provides a mock function with given fields: ctx, userID, hoursAhead
func (_m *MockStudyServicer) GetReminders(ctx context.Context, userID uuid.UUID, hoursAhead int) (*dto.ReminderResponse, error) {
	ret := _m.Called(ctx, userID, hoursAhead)

	if len(ret) == 0 {
		panic("no return value specified for GetReminders")
	}

	var r0 *dto.ReminderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) (*dto.ReminderResponse, error)); ok {
		return rf(ctx, userID, hoursAhead)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) *dto.ReminderResponse); ok {
		r0 = rf(ctx, userID, hoursAhead)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ReminderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int) error); ok {
		r1 = rf(ctx, userID, hoursAhead)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStudyServicer_GetReminders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReminders'
type MockStudyServicer_GetReminders_Call struct {
	*mock.Call
}

// GetReminders is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - hoursAhead int
func (_e *MockStudyServicer_Expecter) GetReminders(ctx interface{}, userID interface{}, hoursAhead interface{}) *MockStudyServicer_GetReminders_Call {
	return &MockStudyServicer_GetReminders_Call{Call: _e.mock.On("GetReminders", ctx, userID, hoursAhead)}
}

func (_c *MockStudyServicer_GetReminders_Call) Run(run func(ctx context.Context, userID uuid.UUID, hoursAhead int)) *MockStudyServicer_GetReminders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int))
	})
	return _c
}

func (_c *MockStudyServicer_GetReminders_Call) Return(_a0 *dto.ReminderResponse, _a1 error) *MockStudyServicer_GetReminders_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStudyServicer_GetReminders_Call) RunAndReturn(run func(context.Context, uuid.UUID, int) (*dto.ReminderResponse, error)) *MockStudyServicer_GetReminders_Call {
	_c.Call.Return(run)
	return _c
}

// GetSession provides a mock function with given fields: ctx, userID, sessionID
func (_m *MockStudyServicer) GetSession(ctx context.Context, userID uuid.UUID, sessionID uuid.UUID) (*domain.StudySession, error) {
	ret := _m.Called(ctx, userID, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetSession")
	}

	var r0 *domain.StudySession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*domain.StudySession, error)); ok {
		return rf(ctx, userID, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *domain.StudySession); ok {
		r0 = rf(ctx, userID, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.StudySession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, userID, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStudyServicer_GetSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSession'
type MockStudyServicer_GetSession_Call struct {
	*mock.Call
}

// GetSession is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - sessionID uuid.UUID
func (_e *MockStudyServicer_Expecter) GetSession(ctx interface{}, userID interface{}, sessionID interface{}) *MockStudyServicer_GetSession_Call {
	return &MockStudyServicer_GetSession_Call{Call: _e.mock.On("GetSession", ctx, userID, sessionID)}
}

func (_c *MockStudyServicer_GetSession_Call) Run(run func(ctx context.Context, userID uuid.UUID, sessionID uuid.UUID)) *MockStudyServicer_GetSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockStudyServicer_GetSession_Call) Return(_a0 *domain.StudySession, _a1 error) *MockStudyServicer_GetSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStudyServicer_GetSession_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*domain.StudySession, error)) *MockStudyServicer_GetSession_Call {
	_c.Call.Return(run)
	return _c
}

// StartSession provides a mock function with given fields: ctx, userID, req
func (_m *MockStudyServicer) StartSession(ctx context.Context, userID uuid.UUID, req dto.StartSessionRequest) (*dto.StartSessionResponse, error) {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for StartSession")
	}

	var r0 *dto.StartSessionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.StartSessionRequest) (*dto.StartSessionResponse, error)); ok {
		return rf(ctx, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.StartSessionRequest) *dto.StartSessionResponse); ok {
		r0 = rf(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.StartSessionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, dto.StartSessionRequest) error); ok {
		r1 = rf(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStudyServicer_StartSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartSession'
type MockStudyServicer_StartSession_Call struct {
	*mock.Call
}

// StartSession is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - req dto.StartSessionRequest
func (_e *MockStudyServicer_Expecter) StartSession(ctx interface{}, userID interface{}, req interface{}) *MockStudyServicer_StartSession_Call {
	return &MockStudyServicer_StartSession_Call{Call: _e.mock.On("StartSession", ctx, userID, req)}
}

func (_c *MockStudyServicer_StartSession_Call) Run(run func(ctx context.Context, userID uuid.UUID, req dto.StartSessionRequest)) *MockStudyServicer_StartSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(dto.StartSessionRequest))
	})
	return _c
}

func (_c *MockStudyServicer_StartSession_Call) Return(_a0 *dto.StartSessionResponse, _a1 error) *MockStudyServicer_StartSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStudyServicer_StartSession_Call) RunAndReturn(run func(context.Context, uuid.UUID, dto.StartSessionRequest) (*dto.StartSessionResponse, error)) *MockStudyServicer_StartSession_Call {
	_c.Call.Return(run)
	return _c
}

// SubmitReview provides a mock function with given fields: ctx, userID, sessionID, req
func (_m *MockStudyServicer) SubmitReview(ctx context.Context, userID uuid.UUID, sessionID uuid.UUID, req dto.SubmitReviewRequest) (*dto.ReviewResult, error) {
	ret := _m.Called(ctx, userID, sessionID, req)

	if len(ret) == 0 {
		panic("no return value specified for SubmitReview")
	}

	var r0 *dto.ReviewResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, dto.SubmitReviewRequest) (*dto.ReviewResult, error)); ok {
		return rf(ctx, userID, sessionID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, dto.SubmitReviewRequest) *dto.ReviewResult); ok {
		r0 = rf(ctx, userID, sessionID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ReviewResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, dto.SubmitReviewRequest) error); ok {
		r1 = rf(ctx, userID, sessionID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStudyServicer_SubmitReview_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubmitReview'
type MockStudyServicer_SubmitReview_Call struct {
	*mock.Call
}

// SubmitReview is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - sessionID uuid.UUID
//   - req dto.SubmitReviewRequest
func (_e *MockStudyServicer_Expecter) SubmitReview(ctx interface{}, userID interface{}, sessionID interface{}, req interface{}) *MockStudyServicer_SubmitReview_Call {
	return &MockStudyServicer_SubmitReview_Call{Call: _e.mock.On("SubmitReview", ctx, userID, sessionID, req)}
}

func (_c *MockStudyServicer_SubmitReview_Call) Run(run func(ctx context.Context, userID uuid.UUID, sessionID uuid.UUID, req dto.SubmitReviewRequest)) *MockStudyServicer_SubmitReview_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(dto.SubmitReviewRequest))
	})
	return _c
}

func (_c *MockStudyServicer_SubmitReview_Call) Return(_a0 *dto.ReviewResult, _a1 error) *MockStudyServicer_SubmitReview_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStudyServicer_SubmitReview_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, dto.SubmitReviewRequest) (*dto.ReviewResult, error)) *MockStudyServicer_SubmitReview_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStudyServicer creates a new instance of MockStudyServicer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStudyServicer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStudyServicer {
	mock := &MockStudyServicer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
