// Code generated by mockery v2.53.6. DO NOT EDIT.

package mockport

import (
	context "context"

	domain "github.com/alfariesh/backend-quiz/internal/domain"
	dto "github.com/alfariesh/backend-quiz/internal/dto"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockQuizServicer is an autogenerated mock type for the QuizServicer type
type MockQuizServicer struct {
	mock.Mock
}

type MockQuizServicer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQuizServicer) EXPECT() *MockQuizServicer_Expecter {
	return &MockQuizServicer_Expecter{mock: &_m.Mock}
}

// AddQuestion provides a mock function with given fields: ctx, userID, quizID, req
func (_m *MockQuizServicer) AddQuestion(ctx context.Context, userID uuid.UUID, quizID uuid.UUID, req dto.AddQuestionRequest) (*domain.QuizQuestion, error) {
	ret := _m.Called(ctx, userID, quizID, req)

	if len(ret) == 0 {
		panic("no return value specified for AddQuestion")
	}

	var r0 *domain.QuizQuestion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, dto.AddQuestionRequest) (*domain.QuizQuestion, error)); ok {
		return rf(ctx, userID, quizID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, dto.AddQuestionRequest) *domain.QuizQuestion); ok {
		r0 = rf(ctx, userID, quizID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.QuizQuestion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, dto.AddQuestionRequest) error); ok {
		r1 = rf(ctx, userID, quizID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuizServicer_AddQuestion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddQuestion'
type MockQuizServicer_AddQuestion_Call struct {
	*mock.Call
}

// AddQuestion is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - quizID uuid.UUID
//   - req dto.AddQuestionRequest
func (_e *MockQuizServicer_Expecter) AddQuestion(ctx interface{}, userID interface{}, quizID interface{}, req interface{}) *MockQuizServicer_AddQuestion_Call {
	return &MockQuizServicer_AddQuestion_Call{Call: _e.mock.On("AddQuestion", ctx, userID, quizID, req)}
}

func (_c *MockQuizServicer_AddQuestion_Call) Run(run func(ctx context.Context, userID uuid.UUID, quizID uuid.UUID, req dto.AddQuestionRequest)) *MockQuizServicer_AddQuestion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(dto.AddQuestionRequest))
	})
	return _c
}

func (_c *MockQuizServicer_AddQuestion_Call) Return(_a0 *domain.QuizQuestion, _a1 error) *MockQuizServicer_AddQuestion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuizServicer_AddQuestion_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, dto.AddQuestionRequest) (*domain.QuizQuestion, error)) *MockQuizServicer_AddQuestion_Call {
	_c.Call.Return(run)
	return _c
}

// BatchAddQuestions provides a mock function with given fields: ctx, userID, quizID, req
func (_m *MockQuizServicer) BatchAddQuestions(ctx context.Context, userID uuid.UUID, quizID uuid.UUID, req dto.BatchAddQuestionsRequest) ([]*domain.QuizQuestion, error) {
	ret := _m.Called(ctx, userID, quizID, req)

	if len(ret) == 0 {
		panic("no return value specified for BatchAddQuestions")
	}

	var r0 []*domain.QuizQuestion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, dto.BatchAddQuestionsRequest) ([]*domain.QuizQuestion, error)); ok {
		return rf(ctx, userID, quizID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, dto.BatchAddQuestionsRequest) []*domain.QuizQuestion); ok {
		r0 = rf(ctx, userID, quizID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.QuizQuestion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, dto.BatchAddQuestionsRequest) error); ok {
		r1 = rf(ctx, userID, quizID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuizServicer_BatchAddQuestions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchAddQuestions'
type MockQuizServicer_BatchAddQuestions_Call struct {
	*mock.Call
}

// BatchAddQuestions is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - quizID uuid.UUID
//   - req dto.BatchAddQuestionsRequest
func (_e *MockQuizServicer_Expecter) BatchAddQuestions(ctx interface{}, userID interface{}, quizID interface{}, req interface{}) *MockQuizServicer_BatchAddQuestions_Call {
	return &MockQuizServicer_BatchAddQuestions_Call{Call: _e.mock.On("BatchAddQuestions", ctx, userID, quizID, req)}
}

func (_c *MockQuizServicer_BatchAddQuestions_Call) Run(run func(ctx context.Context, userID uuid.UUID, quizID uuid.UUID, req dto.BatchAddQuestionsRequest)) *MockQuizServicer_BatchAddQuestions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(dto.BatchAddQuestionsRequest))
	})
	return _c
}

func (_c *MockQuizServicer_BatchAddQuestions_Call) Return(_a0 []*domain.QuizQuestion, _a1 error) *MockQuizServicer_BatchAddQuestions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuizServicer_BatchAddQuestions_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, dto.BatchAddQuestionsRequest) ([]*domain.QuizQuestion, error)) *MockQuizServicer_BatchAddQuestions_Call {
	_c.Call.Return(run)
	return _c
}

// CompleteAttempt provides a mock function with given fields: ctx, userID, attemptID
func (_m *MockQuizServicer) CompleteAttempt(ctx context.Context, userID uuid.UUID, attemptID uuid.UUID) (*domain.QuizAttempt, error) {
	ret := _m.Called(ctx, userID, attemptID)

	if len(ret) == 0 {
		panic("no return value specified for CompleteAttempt")
	}

	var r0 *domain.QuizAttempt
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*domain.QuizAttempt, error)); ok {
		return rf(ctx, userID, attemptID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *domain.QuizAttempt); ok {
		r0 = rf(ctx, userID, attemptID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.QuizAttempt)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, userID, attemptID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuizServicer_CompleteAttempt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteAttempt'
type MockQuizServicer_CompleteAttempt_Call struct {
	*mock.Call
}

// CompleteAttempt is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - attemptID uuid.UUID
func (_e *MockQuizServicer_Expecter) CompleteAttempt(ctx interface{}, userID interface{}, attemptID interface{}) *MockQuizServicer_CompleteAttempt_Call {
	return &MockQuizServicer_CompleteAttempt_Call{Call: _e.mock.On("CompleteAttempt", ctx, userID, attemptID)}
}

func (_c *MockQuizServicer_CompleteAttempt_Call) Run(run func(ctx context.Context, userID uuid.UUID, attemptID uuid.UUID)) *MockQuizServicer_CompleteAttempt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockQuizServicer_CompleteAttempt_Call) Return(_a0 *domain.QuizAttempt, _a1 error) *MockQuizServicer_CompleteAttempt_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuizServicer_CompleteAttempt_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*domain.QuizAttempt, error)) *MockQuizServicer_CompleteAttempt_Call {
	_c.Call.Return(run)
	return _c
}

// CreateQuiz provides a mock function with given fields: ctx, userID, req
func (_m *MockQuizServicer) CreateQuiz(ctx context.Context, userID uuid.UUID, req dto.CreateQuizRequest) (*domain.Quiz, error) {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateQuiz")
	}

	var r0 *domain.Quiz
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.CreateQuizRequest) (*domain.Quiz, error)); ok {
		return rf(ctx, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.CreateQuizRequest) *domain.Quiz); ok {
		r0 = rf(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Quiz)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, dto.CreateQuizRequest) error); ok {
		r1 = rf(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuizServicer_CreateQuiz_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateQuiz'
type MockQuizServicer_CreateQuiz_Call struct {
	*mock.Call
}

// CreateQuiz is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - req dto.CreateQuizRequest
func (_e *MockQuizServicer_Expecter) CreateQuiz(ctx interface{}, userID interface{}, req interface{}) *MockQuizServicer_CreateQuiz_Call {
	return &MockQuizServicer_CreateQuiz_Call{Call: _e.mock.On("CreateQuiz", ctx, userID, req)}
}

func (_c *MockQuizServicer_CreateQuiz_Call) Run(run func(ctx context.Context, userID uuid.UUID, req dto.CreateQuizRequest)) *MockQuizServicer_CreateQuiz_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(dto.CreateQuizRequest))
	})
	return _c
}

func (_c *MockQuizServicer_CreateQuiz_Call) Return(_a0 *domain.Quiz, _a1 error) *MockQuizServicer_CreateQuiz_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuizServicer_CreateQuiz_Call) RunAndReturn(run func(context.Context, uuid.UUID, dto.CreateQuizRequest) (*domain.Quiz, error)) *MockQuizServicer_CreateQuiz_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteQuestion provides a mock function with given fields: ctx, userID, quizID, questionID
func (_m *MockQuizServicer) DeleteQuestion(ctx context.Context, userID uuid.UUID, quizID uuid.UUID, questionID uuid.UUID) error {
	ret := _m.Called(ctx, userID, quizID, questionID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteQuestion")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, userID, quizID, questionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuizServicer_DeleteQuestion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteQuestion'
type MockQuizServicer_DeleteQuestion_Call struct {
	*mock.Call
}

// DeleteQuestion is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - quizID uuid.UUID
//   - questionID uuid.UUID
func (_e *MockQuizServicer_Expecter) DeleteQuestion(ctx interface{}, userID interface{}, quizID interface{}, questionID interface{}) *MockQuizServicer_DeleteQuestion_Call {
	return &MockQuizServicer_DeleteQuestion_Call{Call: _e.mock.On("DeleteQuestion", ctx, userID, quizID, questionID)}
}

func (_c *MockQuizServicer_DeleteQuestion_Call) Run(run func(ctx context.Context, userID uuid.UUID, quizID uuid.UUID, questionID uuid.UUID)) *MockQuizServicer_DeleteQuestion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *MockQuizServicer_DeleteQuestion_Call) Return(_a0 error) *MockQuizServicer_DeleteQuestion_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuizServicer_DeleteQuestion_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error) *MockQuizServicer_DeleteQuestion_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteQuiz provides a mock function with given fields: ctx, userID, quizID
func (_m *MockQuizServicer) DeleteQuiz(ctx context.Context, userID uuid.UUID, quizID uuid.UUID) error {
	ret := _m.Called(ctx, userID, quizID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteQuiz")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, userID, quizID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuizServicer_DeleteQuiz_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteQuiz'
type MockQuizServicer_DeleteQuiz_Call struct {
	*mock.Call
}

// DeleteQuiz is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - quizID uuid.UUID
func (_e *MockQuizServicer_Expecter) DeleteQuiz(ctx interface{}, userID interface{}, quizID interface{}) *MockQuizServicer_DeleteQuiz_Call {
	return &MockQuizServicer_DeleteQuiz_Call{Call: _e.mock.On("DeleteQuiz", ctx, userID, quizID)}
}

func (_c *MockQuizServicer_DeleteQuiz_Call) Run(run func(ctx context.Context, userID uuid.UUID, quizID uuid.UUID)) *MockQuizServicer_DeleteQuiz_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockQuizServicer_DeleteQuiz_Call) Return(_a0 error) *MockQuizServicer_DeleteQuiz_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuizServicer_DeleteQuiz_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockQuizServicer_DeleteQuiz_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateAyatQuiz provides a mock function with given fields: ctx, userID, quizID, req
func (_m *MockQuizServicer) GenerateAyatQuiz(ctx context.Context, userID uuid.UUID, quizID uuid.UUID, req dto.GenerateAyatQuizRequest) ([]*domain.QuizQuestion, error) {
	ret := _m.Called(ctx, userID, quizID, req)

	if len(ret) == 0 {
		panic("no return value specified for GenerateAyatQuiz")
	}

	var r0 []*domain.QuizQuestion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, dto.GenerateAyatQuizRequest) ([]*domain.QuizQuestion, error)); ok {
		return rf(ctx, userID, quizID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, dto.GenerateAyatQuizRequest) []*domain.QuizQuestion); ok {
		r0 = rf(ctx, userID, quizID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.QuizQuestion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, dto.GenerateAyatQuizRequest) error); ok {
		r1 = rf(ctx, userID, quizID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuizServicer_GenerateAyatQuiz_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateAyatQuiz'
type MockQuizServicer_GenerateAyatQuiz_Call struct {
	*mock.Call
}

// GenerateAyatQuiz is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - quizID uuid.UUID
//   - req dto.GenerateAyatQuizRequest
func (_e *MockQuizServicer_Expecter) GenerateAyatQuiz(ctx interface{}, userID interface{}, quizID interface{}, req interface{}) *MockQuizServicer_GenerateAyatQuiz_Call {
	return &MockQuizServicer_GenerateAyatQuiz_Call{Call: _e.mock.On("GenerateAyatQuiz", ctx, userID, quizID, req)}
}

func (_c *MockQuizServicer_GenerateAyatQuiz_Call) Run(run func(ctx context.Context, userID uuid.UUID, quizID uuid.UUID, req dto.GenerateAyatQuizRequest)) *MockQuizServicer_GenerateAyatQuiz_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(dto.GenerateAyatQuizRequest))
	})
	return _c
}

func (_c *MockQuizServicer_GenerateAyatQuiz_Call) Return(_a0 []*domain.QuizQuestion, _a1 error) *MockQuizServicer_GenerateAyatQuiz_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuizServicer_GenerateAyatQuiz_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, dto.GenerateAyatQuizRequest) ([]*domain.QuizQuestion, error)) *MockQuizServicer_GenerateAyatQuiz_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateFromDeck provides a mock function with given fields: ctx, userID, quizID, req
func (_m *MockQuizServicer) GenerateFromDeck(ctx context.Context, userID uuid.UUID, quizID uuid.UUID, req dto.GenerateFromDeckRequest) ([]*domain.QuizQuestion, error) {
	ret := _m.Called(ctx, userID, quizID, req)

	if len(ret) == 0 {
		panic("no return value specified for GenerateFromDeck")
	}

	var r0 []*domain.QuizQuestion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, dto.GenerateFromDeckRequest) ([]*domain.QuizQuestion, error)); ok {
		return rf(ctx, userID, quizID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, dto.GenerateFromDeckRequest) []*domain.QuizQuestion); ok {
		r0 = rf(ctx, userID, quizID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.QuizQuestion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, dto.GenerateFromDeckRequest) error); ok {
		r1 = rf(ctx, userID, quizID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuizServicer_GenerateFromDeck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateFromDeck'
type MockQuizServicer_GenerateFromDeck_Call struct {
	*mock.Call
}

// GenerateFromDeck is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - quizID uuid.UUID
//   - req dto.GenerateFromDeckRequest
func (_e *MockQuizServicer_Expecter) GenerateFromDeck(ctx interface{}, userID interface{}, quizID interface{}, req interface{}) *MockQuizServicer_GenerateFromDeck_Call {
	return &MockQuizServicer_GenerateFromDeck_Call{Call: _e.mock.On("GenerateFromDeck", ctx, userID, quizID, req)}
}

func (_c *MockQuizServicer_GenerateFromDeck_Call) Run(run func(ctx context.Context, userID uuid.UUID, quizID uuid.UUID, req dto.GenerateFromDeckRequest)) *MockQuizServicer_GenerateFromDeck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(dto.GenerateFromDeckRequest))
	})
	return _c
}

func (_c *MockQuizServicer_GenerateFromDeck_Call) Return(_a0 []*domain.QuizQuestion, _a1 error) *MockQuizServicer_GenerateFromDeck_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuizServicer_GenerateFromDeck_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, dto.GenerateFromDeckRequest) ([]*domain.QuizQuestion, error)) *MockQuizServicer_GenerateFromDeck_Call {
	_c.Call.Return(run)
	return _c
}

// GetAttempt provides a mock function with given fields: ctx, userID, attemptID
func (_m *MockQuizServicer) GetAttempt(ctx context.Context, userID uuid.UUID, attemptID uuid.UUID) (*dto.AttemptDetail, error) {
	ret := _m.Called(ctx, userID, attemptID)

	if len(ret) == 0 {
		panic("no return value specified for GetAttempt")
	}

	var r0 *dto.AttemptDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*dto.AttemptDetail, error)); ok {
		return rf(ctx, userID, attemptID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *dto.AttemptDetail); ok {
		r0 = rf(ctx, userID, attemptID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.AttemptDetail)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, userID, attemptID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuizServicer_GetAttempt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAttempt'
type MockQuizServicer_GetAttempt_Call struct {
	*mock.Call
}

// GetAttempt is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - attemptID uuid.UUID
func (_e *MockQuizServicer_Expecter) GetAttempt(ctx interface{}, userID interface{}, attemptID interface{}) *MockQuizServicer_GetAttempt_Call {
	return &MockQuizServicer_GetAttempt_Call{Call: _e.mock.On("GetAttempt", ctx, userID, attemptID)}
}

func (_c *MockQuizServicer_GetAttempt_Call) Run(run func(ctx context.Context, userID uuid.UUID, attemptID uuid.UUID)) *MockQuizServicer_GetAttempt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockQuizServicer_GetAttempt_Call) Return(_a0 *dto.AttemptDetail, _a1 error) *MockQuizServicer_GetAttempt_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuizServicer_GetAttempt_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*dto.AttemptDetail, error)) *MockQuizServicer_GetAttempt_Call {
	_c.Call.Return(run)
	return _c
}

// GetQuiz provides a mock function with given fields: ctx, userID, quizID
func (_m *MockQuizServicer) GetQuiz(ctx context.Context, userID uuid.UUID, quizID uuid.UUID) (*dto.QuizDetail, error) {
	ret := _m.Called(ctx, userID, quizID)

	if len(ret) == 0 {
		panic("no return value specified for GetQuiz")
	}

	var r0 *dto.QuizDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*dto.QuizDetail, error)); ok {
		return rf(ctx, userID, quizID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *dto.QuizDetail); ok {
		r0 = rf(ctx, userID, quizID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.QuizDetail)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, userID, quizID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuizServicer_GetQuiz_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQuiz'
type MockQuizServicer_GetQuiz_Call struct {
	*mock.Call
}

// GetQuiz is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - quizID uuid.UUID
func (_e *MockQuizServicer_Expecter) GetQuiz(ctx interface{}, userID interface{}, quizID interface{}) *MockQuizServicer_GetQuiz_Call {
	return &MockQuizServicer_GetQuiz_Call{Call: _e.mock.On("GetQuiz", ctx, userID, quizID)}
}

func (_c *MockQuizServicer_GetQuiz_Call) Run(run func(ctx context.Context, userID uuid.UUID, quizID uuid.UUID)) *MockQuizServicer_GetQuiz_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockQuizServicer_GetQuiz_Call) Return(_a0 *dto.QuizDetail, _a1 error) *MockQuizServicer_GetQuiz_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuizServicer_GetQuiz_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*dto.QuizDetail, error)) *MockQuizServicer_GetQuiz_Call {
	_c.Call.Return(run)
	return _c
}

// ListAttempts provides a mock function with given fields: ctx, userID, quizID, limit, offset
func (_m *MockQuizServicer) ListAttempts(ctx context.Context, userID uuid.UUID, quizID uuid.UUID, limit int, offset int) ([]domain.QuizAttempt, int, error) {
	ret := _m.Called(ctx, userID, quizID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListAttempts")
	}

	var r0 []domain.QuizAttempt
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int, int) ([]domain.QuizAttempt, int, error)); ok {
		return rf(ctx, userID, quizID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int, int) []domain.QuizAttempt); ok {
		r0 = rf(ctx, userID, quizID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.QuizAttempt)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, int, int) int); ok {
		r1 = rf(ctx, userID, quizID, limit, offset)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, uuid.UUID, int, int) error); ok {
		r2 = rf(ctx, userID, quizID, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockQuizServicer_ListAttempts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAttempts'
type MockQuizServicer_ListAttempts_Call struct {
	*mock.Call
}

// ListAttempts is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - quizID uuid.UUID
//   - limit int
//   - offset int
func (_e *MockQuizServicer_Expecter) ListAttempts(ctx interface{}, userID interface{}, quizID interface{}, limit interface{}, offset interface{}) *MockQuizServicer_ListAttempts_Call {
	return &MockQuizServicer_ListAttempts_Call{Call: _e.mock.On("ListAttempts", ctx, userID, quizID, limit, offset)}
}

func (_c *MockQuizServicer_ListAttempts_Call) Run(run func(ctx context.Context, userID uuid.UUID, quizID uuid.UUID, limit int, offset int)) *MockQuizServicer_ListAttempts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(int), args[4].(int))
	})
	return _c
}

func (_c *MockQuizServicer_ListAttempts_Call) Return(_a0 []domain.QuizAttempt, _a1 int, _a2 error) *MockQuizServicer_ListAttempts_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockQuizServicer_ListAttempts_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, int, int) ([]domain.QuizAttempt, int, error)) *MockQuizServicer_ListAttempts_Call {
	_c.Call.Return(run)
	return _c
}

// ListQuizzes provides a mock function with given fields: ctx, userID, limit, offset
func (_m *MockQuizServicer) ListQuizzes(ctx context.Context, userID uuid.UUID, limit int, offset int) ([]domain.QuizWithCounts, int, error) {
	ret := _m.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListQuizzes")
	}

	var r0 []domain.QuizWithCounts
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]domain.QuizWithCounts, int, error)); ok {
		return rf(ctx, userID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []domain.QuizWithCounts); ok {
		r0 = rf(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.QuizWithCounts)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) int); ok {
		r1 = rf(ctx, userID, limit, offset)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, int, int) error); ok {
		r2 = rf(ctx, userID, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockQuizServicer_ListQuizzes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListQuizzes'
type MockQuizServicer_ListQuizzes_Call struct {
	*mock.Call
}

// ListQuizzes is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - limit int
//   - offset int
func (_e *MockQuizServicer_Expecter) ListQuizzes(ctx interface{}, userID interface{}, limit interface{}, offset interface{}) *MockQuizServicer_ListQuizzes_Call {
	return &MockQuizServicer_ListQuizzes_Call{Call: _e.mock.On("ListQuizzes", ctx, userID, limit, offset)}
}

func (_c *MockQuizServicer_ListQuizzes_Call) Run(run func(ctx context.Context, userID uuid.UUID, limit int, offset int)) *MockQuizServicer_ListQuizzes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockQuizServicer_ListQuizzes_Call) Return(_a0 []domain.QuizWithCounts, _a1 int, _a2 error) *MockQuizServicer_ListQuizzes_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockQuizServicer_ListQuizzes_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, int) ([]domain.QuizWithCounts, int, error)) *MockQuizServicer_ListQuizzes_Call {
	_c.Call.Return(run)
	return _c
}

// StartAttempt provides a mock function with given fields: ctx, userID, quizID
func (_m *MockQuizServicer) StartAttempt(ctx context.Context, userID uuid.UUID, quizID uuid.UUID) (*dto.StartAttemptResponse, error) {
	ret := _m.Called(ctx, userID, quizID)

	if len(ret) == 0 {
		panic("no return value specified for StartAttempt")
	}

	var r0 *dto.StartAttemptResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*dto.StartAttemptResponse, error)); ok {
		return rf(ctx, userID, quizID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *dto.StartAttemptResponse); ok {
		r0 = rf(ctx, userID, quizID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.StartAttemptResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, userID, quizID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuizServicer_StartAttempt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartAttempt'
type MockQuizServicer_StartAttempt_Call struct {
	*mock.Call
}

// StartAttempt is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - quizID uuid.UUID
func (_e *MockQuizServicer_Expecter) StartAttempt(ctx interface{}, userID interface{}, quizID interface{}) *MockQuizServicer_StartAttempt_Call {
	return &MockQuizServicer_StartAttempt_Call{Call: _e.mock.On("StartAttempt", ctx, userID, quizID)}
}

func (_c *MockQuizServicer_StartAttempt_Call) Run(run func(ctx context.Context, userID uuid.UUID, quizID uuid.UUID)) *MockQuizServicer_StartAttempt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockQuizServicer_StartAttempt_Call) Return(_a0 *dto.StartAttemptResponse, _a1 error) *MockQuizServicer_StartAttempt_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuizServicer_StartAttempt_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*dto.StartAttemptResponse, error)) *MockQuizServicer_StartAttempt_Call {
	_c.Call.Return(run)
	return _c
}

// SubmitAnswer provides a mock function with given fields: ctx, userID, attemptID, req
func (_m *MockQuizServicer) SubmitAnswer(ctx context.Context, userID uuid.UUID, attemptID uuid.UUID, req dto.SubmitAnswerRequest) (*dto.AnswerResult, error) {
	ret := _m.Called(ctx, userID, attemptID, req)

	if len(ret) == 0 {
		panic("no return value specified for SubmitAnswer")
	}

	var r0 *dto.AnswerResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, dto.SubmitAnswerRequest) (*dto.AnswerResult, error)); ok {
		return rf(ctx, userID, attemptID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, dto.SubmitAnswerRequest) *dto.AnswerResult); ok {
		r0 = rf(ctx, userID, attemptID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.AnswerResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, dto.SubmitAnswerRequest) error); ok {
		r1 = rf(ctx, userID, attemptID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuizServicer_SubmitAnswer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubmitAnswer'
type MockQuizServicer_SubmitAnswer_Call struct {
	*mock.Call
}

// SubmitAnswer is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - attemptID uuid.UUID
//   - req dto.SubmitAnswerRequest
func (_e *MockQuizServicer_Expecter) SubmitAnswer(ctx interface{}, userID interface{}, attemptID interface{}, req interface{}) *MockQuizServicer_SubmitAnswer_Call {
	return &MockQuizServicer_SubmitAnswer_Call{Call: _e.mock.On("SubmitAnswer", ctx, userID, attemptID, req)}
}

func (_c *MockQuizServicer_SubmitAnswer_Call) Run(run func(ctx context.Context, userID uuid.UUID, attemptID uuid.UUID, req dto.SubmitAnswerRequest)) *MockQuizServicer_SubmitAnswer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(dto.SubmitAnswerRequest))
	})
	return _c
}

func (_c *MockQuizServicer_SubmitAnswer_Call) Return(_a0 *dto.AnswerResult, _a1 error) *MockQuizServicer_SubmitAnswer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuizServicer_SubmitAnswer_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, dto.SubmitAnswerRequest) (*dto.AnswerResult, error)) *MockQuizServicer_SubmitAnswer_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateQuestion provides a mock function with given fields: ctx, userID, quizID, questionID, req
func (_m *MockQuizServicer) UpdateQuestion(ctx context.Context, userID uuid.UUID, quizID uuid.UUID, questionID uuid.UUID, req dto.UpdateQuestionRequest) (*domain.QuizQuestion, error) {
	ret := _m.Called(ctx, userID, quizID, questionID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateQuestion")
	}

	var r0 *domain.QuizQuestion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, dto.UpdateQuestionRequest) (*domain.QuizQuestion, error)); ok {
		return rf(ctx, userID, quizID, questionID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, dto.UpdateQuestionRequest) *domain.QuizQuestion); ok {
		r0 = rf(ctx, userID, quizID, questionID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.QuizQuestion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, dto.UpdateQuestionRequest) error); ok {
		r1 = rf(ctx, userID, quizID, questionID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuizServicer_UpdateQuestion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateQuestion'
type MockQuizServicer_UpdateQuestion_Call struct {
	*mock.Call
}

// UpdateQuestion is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - quizID uuid.UUID
//   - questionID uuid.UUID
//   - req dto.UpdateQuestionRequest
func (_e *MockQuizServicer_Expecter) UpdateQuestion(ctx interface{}, userID interface{}, quizID interface{}, questionID interface{}, req interface{}) *MockQuizServicer_UpdateQuestion_Call {
	return &MockQuizServicer_UpdateQuestion_Call{Call: _e.mock.On("UpdateQuestion", ctx, userID, quizID, questionID, req)}
}

func (_c *MockQuizServicer_UpdateQuestion_Call) Run(run func(ctx context.Context, userID uuid.UUID, quizID uuid.UUID, questionID uuid.UUID, req dto.UpdateQuestionRequest)) *MockQuizServicer_UpdateQuestion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(uuid.UUID), args[4].(dto.UpdateQuestionRequest))
	})
	return _c
}

func (_c *MockQuizServicer_UpdateQuestion_Call) Return(_a0 *domain.QuizQuestion, _a1 error) *MockQuizServicer_UpdateQuestion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuizServicer_UpdateQuestion_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, dto.UpdateQuestionRequest) (*domain.QuizQuestion, error)) *MockQuizServicer_UpdateQuestion_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateQuiz provides a mock function with given fields: ctx, userID, quizID, req
func (_m *MockQuizServicer) UpdateQuiz(ctx context.Context, userID uuid.UUID, quizID uuid.UUID, req dto.UpdateQuizRequest) (*domain.Quiz, error) {
	ret := _m.Called(ctx, userID, quizID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateQuiz")
	}

	var r0 *domain.Quiz
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, dto.UpdateQuizRequest) (*domain.Quiz, error)); ok {
		return rf(ctx, userID, quizID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, dto.UpdateQuizRequest) *domain.Quiz); ok {
		r0 = rf(ctx, userID, quizID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Quiz)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, dto.UpdateQuizRequest) error); ok {
		r1 = rf(ctx, userID, quizID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuizServicer_UpdateQuiz_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateQuiz'
type MockQuizServicer_UpdateQuiz_Call struct {
	*mock.Call
}

// UpdateQuiz is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - quizID uuid.UUID
//   - req dto.UpdateQuizRequest
func (_e *MockQuizServicer_Expecter) UpdateQuiz(ctx interface{}, userID interface{}, quizID interface{}, req interface{}) *MockQuizServicer_UpdateQuiz_Call {
	return &MockQuizServicer_UpdateQuiz_Call{Call: _e.mock.On("UpdateQuiz", ctx, userID, quizID, req)}
}

func (_c *MockQuizServicer_UpdateQuiz_Call) Run(run func(ctx context.Context, userID uuid.UUID, quizID uuid.UUID, req dto.UpdateQuizRequest)) *MockQuizServicer_UpdateQuiz_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(dto.UpdateQuizRequest))
	})
	return _c
}

func (_c *MockQuizServicer_UpdateQuiz_Call) Return(_a0 *domain.Quiz, _a1 error) *MockQuizServicer_UpdateQuiz_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuizServicer_UpdateQuiz_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, dto.UpdateQuizRequest) (*domain.Quiz, error)) *MockQuizServicer_UpdateQuiz_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQuizServicer creates a new instance of MockQuizServicer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuizServicer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuizServicer {
	mock := &MockQuizServicer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
