// Code generated by mockery v2.53.6. DO NOT EDIT.

package mockport

import (
	context "context"

	domain "github.com/alfariesh/backend-quiz/internal/domain"
	dto "github.com/alfariesh/backend-quiz/internal/dto"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockAuthServicer is an autogenerated mock type for the AuthServicer type
type MockAuthServicer struct {
	mock.Mock
}

type MockAuthServicer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthServicer) EXPECT() *MockAuthServicer_Expecter {
	return &MockAuthServicer_Expecter{mock: &_m.Mock}
}

// CancelAccountDeletionBasic provides a mock function with given fields: ctx, userID
func (_m *MockAuthServicer) CancelAccountDeletionBasic(ctx context.Context, userID uuid.UUID) (*domain.User, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CancelAccountDeletionBasic")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.User, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.User); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthServicer_CancelAccountDeletionBasic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelAccountDeletionBasic'
type MockAuthServicer_CancelAccountDeletionBasic_Call struct {
	*mock.Call
}

// CancelAccountDeletionBasic is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockAuthServicer_Expecter) CancelAccountDeletionBasic(ctx interface{}, userID interface{}) *MockAuthServicer_CancelAccountDeletionBasic_Call {
	return &MockAuthServicer_CancelAccountDeletionBasic_Call{Call: _e.mock.On("CancelAccountDeletionBasic", ctx, userID)}
}

func (_c *MockAuthServicer_CancelAccountDeletionBasic_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockAuthServicer_CancelAccountDeletionBasic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockAuthServicer_CancelAccountDeletionBasic_Call) Return(_a0 *domain.User, _a1 error) *MockAuthServicer_CancelAccountDeletionBasic_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthServicer_CancelAccountDeletionBasic_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.User, error)) *MockAuthServicer_CancelAccountDeletionBasic_Call {
	_c.Call.Return(run)
	return _c
}

// ChangePassword provides a mock function with given fields: ctx, userID, req
func (_m *MockAuthServicer) ChangePassword(ctx context.Context, userID uuid.UUID, req dto.ChangePasswordRequest) error {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for ChangePassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.ChangePasswordRequest) error); ok {
		r0 = rf(ctx, userID, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthServicer_ChangePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangePassword'
type MockAuthServicer_ChangePassword_Call struct {
	*mock.Call
}

// ChangePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - req dto.ChangePasswordRequest
func (_e *MockAuthServicer_Expecter) ChangePassword(ctx interface{}, userID interface{}, req interface{}) *MockAuthServicer_ChangePassword_Call {
	return &MockAuthServicer_ChangePassword_Call{Call: _e.mock.On("ChangePassword", ctx, userID, req)}
}

func (_c *MockAuthServicer_ChangePassword_Call) Run(run func(ctx context.Context, userID uuid.UUID, req dto.ChangePasswordRequest)) *MockAuthServicer_ChangePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(dto.ChangePasswordRequest))
	})
	return _c
}

func (_c *MockAuthServicer_ChangePassword_Call) Return(_a0 error) *MockAuthServicer_ChangePassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthServicer_ChangePassword_Call) RunAndReturn(run func(context.Context, uuid.UUID, dto.ChangePasswordRequest) error) *MockAuthServicer_ChangePassword_Call {
	_c.Call.Return(run)
	return _c
}

// ExportAccountDataBasic provides a mock function with given fields: ctx, userID
func (_m *MockAuthServicer) ExportAccountDataBasic(ctx context.Context, userID uuid.UUID) (map[string]interface{}, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ExportAccountDataBasic")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (map[string]interface{}, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) map[string]interface{}); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthServicer_ExportAccountDataBasic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExportAccountDataBasic'
type MockAuthServicer_ExportAccountDataBasic_Call struct {
	*mock.Call
}

// ExportAccountDataBasic is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockAuthServicer_Expecter) ExportAccountDataBasic(ctx interface{}, userID interface{}) *MockAuthServicer_ExportAccountDataBasic_Call {
	return &MockAuthServicer_ExportAccountDataBasic_Call{Call: _e.mock.On("ExportAccountDataBasic", ctx, userID)}
}

func (_c *MockAuthServicer_ExportAccountDataBasic_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockAuthServicer_ExportAccountDataBasic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockAuthServicer_ExportAccountDataBasic_Call) Return(_a0 map[string]interface{}, _a1 error) *MockAuthServicer_ExportAccountDataBasic_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthServicer_ExportAccountDataBasic_Call) RunAndReturn(run func(context.Context, uuid.UUID) (map[string]interface{}, error)) *MockAuthServicer_ExportAccountDataBasic_Call {
	_c.Call.Return(run)
	return _c
}

// FindOrCreateOAuthUser provides a mock function with given fields: ctx, provider, providerID, email, displayName, avatarURL
func (_m *MockAuthServicer) FindOrCreateOAuthUser(ctx context.Context, provider string, providerID string, email string, displayName string, avatarURL *string) (*dto.TokenPair, *domain.User, error) {
	ret := _m.Called(ctx, provider, providerID, email, displayName, avatarURL)

	if len(ret) == 0 {
		panic("no return value specified for FindOrCreateOAuthUser")
	}

	var r0 *dto.TokenPair
	var r1 *domain.User
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, *string) (*dto.TokenPair, *domain.User, error)); ok {
		return rf(ctx, provider, providerID, email, displayName, avatarURL)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, *string) *dto.TokenPair); ok {
		r0 = rf(ctx, provider, providerID, email, displayName, avatarURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.TokenPair)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, *string) *domain.User); ok {
		r1 = rf(ctx, provider, providerID, email, displayName, avatarURL)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*domain.User)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, string, string, *string) error); ok {
		r2 = rf(ctx, provider, providerID, email, displayName, avatarURL)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAuthServicer_FindOrCreateOAuthUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOrCreateOAuthUser'
type MockAuthServicer_FindOrCreateOAuthUser_Call struct {
	*mock.Call
}

// FindOrCreateOAuthUser is a helper method to define mock.On call
//   - ctx context.Context
//   - provider string
//   - providerID string
//   - email string
//   - displayName string
//   - avatarURL *string
func (_e *MockAuthServicer_Expecter) FindOrCreateOAuthUser(ctx interface{}, provider interface{}, providerID interface{}, email interface{}, displayName interface{}, avatarURL interface{}) *MockAuthServicer_FindOrCreateOAuthUser_Call {
	return &MockAuthServicer_FindOrCreateOAuthUser_Call{Call: _e.mock.On("FindOrCreateOAuthUser", ctx, provider, providerID, email, displayName, avatarURL)}
}

func (_c *MockAuthServicer_FindOrCreateOAuthUser_Call) Run(run func(ctx context.Context, provider string, providerID string, email string, displayName string, avatarURL *string)) *MockAuthServicer_FindOrCreateOAuthUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].(*string))
	})
	return _c
}

func (_c *MockAuthServicer_FindOrCreateOAuthUser_Call) Return(_a0 *dto.TokenPair, _a1 *domain.User, _a2 error) *MockAuthServicer_FindOrCreateOAuthUser_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockAuthServicer_FindOrCreateOAuthUser_Call) RunAndReturn(run func(context.Context, string, string, string, string, *string) (*dto.TokenPair, *domain.User, error)) *MockAuthServicer_FindOrCreateOAuthUser_Call {
	_c.Call.Return(run)
	return _c
}

// ForgotPassword provides a mock function with given fields: ctx, email
func (_m *MockAuthServicer) ForgotPassword(ctx context.Context, email string) error {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for ForgotPassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthServicer_ForgotPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ForgotPassword'
type MockAuthServicer_ForgotPassword_Call struct {
	*mock.Call
}

// ForgotPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockAuthServicer_Expecter) ForgotPassword(ctx interface{}, email interface{}) *MockAuthServicer_ForgotPassword_Call {
	return &MockAuthServicer_ForgotPassword_Call{Call: _e.mock.On("ForgotPassword", ctx, email)}
}

func (_c *MockAuthServicer_ForgotPassword_Call) Run(run func(ctx context.Context, email string)) *MockAuthServicer_ForgotPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthServicer_ForgotPassword_Call) Return(_a0 error) *MockAuthServicer_ForgotPassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthServicer_ForgotPassword_Call) RunAndReturn(run func(context.Context, string) error) *MockAuthServicer_ForgotPassword_Call {
	_c.Call.Return(run)
	return _c
}

// GetProfile provides a mock function with given fields: ctx, userID
func (_m *MockAuthServicer) GetProfile(ctx context.Context, userID uuid.UUID) (*domain.User, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetProfile")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.User, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.User); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthServicer_GetProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfile'
type MockAuthServicer_GetProfile_Call struct {
	*mock.Call
}

// GetProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockAuthServicer_Expecter) GetProfile(ctx interface{}, userID interface{}) *MockAuthServicer_GetProfile_Call {
	return &MockAuthServicer_GetProfile_Call{Call: _e.mock.On("GetProfile", ctx, userID)}
}

func (_c *MockAuthServicer_GetProfile_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockAuthServicer_GetProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockAuthServicer_GetProfile_Call) Return(_a0 *domain.User, _a1 error) *MockAuthServicer_GetProfile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthServicer_GetProfile_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.User, error)) *MockAuthServicer_GetProfile_Call {
	_c.Call.Return(run)
	return _c
}

// ListSessions provides a mock function with given fields: ctx, userID
func (_m *MockAuthServicer) ListSessions(ctx context.Context, userID uuid.UUID) ([]*domain.RefreshToken, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListSessions")
	}

	var r0 []*domain.RefreshToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*domain.RefreshToken, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*domain.RefreshToken); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.RefreshToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthServicer_ListSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSessions'
type MockAuthServicer_ListSessions_Call struct {
	*mock.Call
}

// ListSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockAuthServicer_Expecter) ListSessions(ctx interface{}, userID interface{}) *MockAuthServicer_ListSessions_Call {
	return &MockAuthServicer_ListSessions_Call{Call: _e.mock.On("ListSessions", ctx, userID)}
}

func (_c *MockAuthServicer_ListSessions_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockAuthServicer_ListSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockAuthServicer_ListSessions_Call) Return(_a0 []*domain.RefreshToken, _a1 error) *MockAuthServicer_ListSessions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthServicer_ListSessions_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*domain.RefreshToken, error)) *MockAuthServicer_ListSessions_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function with given fields: ctx, req
func (_m *MockAuthServicer) Login(ctx context.Context, req dto.LoginRequest) (*dto.TokenPair, *domain.User, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *dto.TokenPair
	var r1 *domain.User
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.LoginRequest) (*dto.TokenPair, *domain.User, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.LoginRequest) *dto.TokenPair); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.TokenPair)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.LoginRequest) *domain.User); ok {
		r1 = rf(ctx, req)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*domain.User)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, dto.LoginRequest) error); ok {
		r2 = rf(ctx, req)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAuthServicer_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthServicer_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - req dto.LoginRequest
func (_e *MockAuthServicer_Expecter) Login(ctx interface{}, req interface{}) *MockAuthServicer_Login_Call {
	return &MockAuthServicer_Login_Call{Call: _e.mock.On("Login", ctx, req)}
}

func (_c *MockAuthServicer_Login_Call) Run(run func(ctx context.Context, req dto.LoginRequest)) *MockAuthServicer_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.LoginRequest))
	})
	return _c
}

func (_c *MockAuthServicer_Login_Call) Return(_a0 *dto.TokenPair, _a1 *domain.User, _a2 error) *MockAuthServicer_Login_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockAuthServicer_Login_Call) RunAndReturn(run func(context.Context, dto.LoginRequest) (*dto.TokenPair, *domain.User, error)) *MockAuthServicer_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function with given fields: ctx, refreshToken
func (_m *MockAuthServicer) Logout(ctx context.Context, refreshToken string) error {
	ret := _m.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, refreshToken)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthServicer_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockAuthServicer_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *MockAuthServicer_Expecter) Logout(ctx interface{}, refreshToken interface{}) *MockAuthServicer_Logout_Call {
	return &MockAuthServicer_Logout_Call{Call: _e.mock.On("Logout", ctx, refreshToken)}
}

func (_c *MockAuthServicer_Logout_Call) Run(run func(ctx context.Context, refreshToken string)) *MockAuthServicer_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthServicer_Logout_Call) Return(_a0 error) *MockAuthServicer_Logout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthServicer_Logout_Call) RunAndReturn(run func(context.Context, string) error) *MockAuthServicer_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// LogoutAll provides a mock function with given fields: ctx, userID
func (_m *MockAuthServicer) LogoutAll(ctx context.Context, userID uuid.UUID) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for LogoutAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthServicer_LogoutAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogoutAll'
type MockAuthServicer_LogoutAll_Call struct {
	*mock.Call
}

// LogoutAll is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockAuthServicer_Expecter) LogoutAll(ctx interface{}, userID interface{}) *MockAuthServicer_LogoutAll_Call {
	return &MockAuthServicer_LogoutAll_Call{Call: _e.mock.On("LogoutAll", ctx, userID)}
}

func (_c *MockAuthServicer_LogoutAll_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockAuthServicer_LogoutAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockAuthServicer_LogoutAll_Call) Return(_a0 error) *MockAuthServicer_LogoutAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthServicer_LogoutAll_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockAuthServicer_LogoutAll_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshToken provides a mock function with given fields: ctx, refreshToken
func (_m *MockAuthServicer) RefreshToken(ctx context.Context, refreshToken string) (*dto.TokenPair, error) {
	ret := _m.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 *dto.TokenPair
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*dto.TokenPair, error)); ok {
		return rf(ctx, refreshToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *dto.TokenPair); ok {
		r0 = rf(ctx, refreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.TokenPair)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthServicer_RefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshToken'
type MockAuthServicer_RefreshToken_Call struct {
	*mock.Call
}

// RefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *MockAuthServicer_Expecter) RefreshToken(ctx interface{}, refreshToken interface{}) *MockAuthServicer_RefreshToken_Call {
	return &MockAuthServicer_RefreshToken_Call{Call: _e.mock.On("RefreshToken", ctx, refreshToken)}
}

func (_c *MockAuthServicer_RefreshToken_Call) Run(run func(ctx context.Context, refreshToken string)) *MockAuthServicer_RefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthServicer_RefreshToken_Call) Return(_a0 *dto.TokenPair, _a1 error) *MockAuthServicer_RefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthServicer_RefreshToken_Call) RunAndReturn(run func(context.Context, string) (*dto.TokenPair, error)) *MockAuthServicer_RefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, req
func (_m *MockAuthServicer) Register(ctx context.Context, req dto.RegisterRequest) (*dto.TokenPair, *domain.User, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *dto.TokenPair
	var r1 *domain.User
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.RegisterRequest) (*dto.TokenPair, *domain.User, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.RegisterRequest) *dto.TokenPair); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.TokenPair)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.RegisterRequest) *domain.User); ok {
		r1 = rf(ctx, req)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*domain.User)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, dto.RegisterRequest) error); ok {
		r2 = rf(ctx, req)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAuthServicer_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockAuthServicer_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - req dto.RegisterRequest
func (_e *MockAuthServicer_Expecter) Register(ctx interface{}, req interface{}) *MockAuthServicer_Register_Call {
	return &MockAuthServicer_Register_Call{Call: _e.mock.On("Register", ctx, req)}
}

func (_c *MockAuthServicer_Register_Call) Run(run func(ctx context.Context, req dto.RegisterRequest)) *MockAuthServicer_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.RegisterRequest))
	})
	return _c
}

func (_c *MockAuthServicer_Register_Call) Return(_a0 *dto.TokenPair, _a1 *domain.User, _a2 error) *MockAuthServicer_Register_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockAuthServicer_Register_Call) RunAndReturn(run func(context.Context, dto.RegisterRequest) (*dto.TokenPair, *domain.User, error)) *MockAuthServicer_Register_Call {
	_c.Call.Return(run)
	return _c
}

// RequestAccountDeletionBasic provides a mock function with given fields: ctx, userID
func (_m *MockAuthServicer) RequestAccountDeletionBasic(ctx context.Context, userID uuid.UUID) (*domain.User, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for RequestAccountDeletionBasic")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.User, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.User); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthServicer_RequestAccountDeletionBasic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestAccountDeletionBasic'
type MockAuthServicer_RequestAccountDeletionBasic_Call struct {
	*mock.Call
}

// RequestAccountDeletionBasic is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockAuthServicer_Expecter) RequestAccountDeletionBasic(ctx interface{}, userID interface{}) *MockAuthServicer_RequestAccountDeletionBasic_Call {
	return &MockAuthServicer_RequestAccountDeletionBasic_Call{Call: _e.mock.On("RequestAccountDeletionBasic", ctx, userID)}
}

func (_c *MockAuthServicer_RequestAccountDeletionBasic_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockAuthServicer_RequestAccountDeletionBasic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockAuthServicer_RequestAccountDeletionBasic_Call) Return(_a0 *domain.User, _a1 error) *MockAuthServicer_RequestAccountDeletionBasic_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthServicer_RequestAccountDeletionBasic_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.User, error)) *MockAuthServicer_RequestAccountDeletionBasic_Call {
	_c.Call.Return(run)
	return _c
}

// ResendVerification provides a mock function with given fields: ctx, email
func (_m *MockAuthServicer) ResendVerification(ctx context.Context, email string) error {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for ResendVerification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthServicer_ResendVerification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResendVerification'
type MockAuthServicer_ResendVerification_Call struct {
	*mock.Call
}

// ResendVerification is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockAuthServicer_Expecter) ResendVerification(ctx interface{}, email interface{}) *MockAuthServicer_ResendVerification_Call {
	return &MockAuthServicer_ResendVerification_Call{Call: _e.mock.On("ResendVerification", ctx, email)}
}

func (_c *MockAuthServicer_ResendVerification_Call) Run(run func(ctx context.Context, email string)) *MockAuthServicer_ResendVerification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthServicer_ResendVerification_Call) Return(_a0 error) *MockAuthServicer_ResendVerification_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthServicer_ResendVerification_Call) RunAndReturn(run func(context.Context, string) error) *MockAuthServicer_ResendVerification_Call {
	_c.Call.Return(run)
	return _c
}

// ResetPassword provides a mock function with given fields: ctx, req
func (_m *MockAuthServicer) ResetPassword(ctx context.Context, req dto.ResetPasswordRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ResetPassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.ResetPasswordRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthServicer_ResetPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetPassword'
type MockAuthServicer_ResetPassword_Call struct {
	*mock.Call
}

// ResetPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - req dto.ResetPasswordRequest
func (_e *MockAuthServicer_Expecter) ResetPassword(ctx interface{}, req interface{}) *MockAuthServicer_ResetPassword_Call {
	return &MockAuthServicer_ResetPassword_Call{Call: _e.mock.On("ResetPassword", ctx, req)}
}

func (_c *MockAuthServicer_ResetPassword_Call) Run(run func(ctx context.Context, req dto.ResetPasswordRequest)) *MockAuthServicer_ResetPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.ResetPasswordRequest))
	})
	return _c
}

func (_c *MockAuthServicer_ResetPassword_Call) Return(_a0 error) *MockAuthServicer_ResetPassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthServicer_ResetPassword_Call) RunAndReturn(run func(context.Context, dto.ResetPasswordRequest) error) *MockAuthServicer_ResetPassword_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeSession provides a mock function with given fields: ctx, userID, sessionID
func (_m *MockAuthServicer) RevokeSession(ctx context.Context, userID uuid.UUID, sessionID uuid.UUID) error {
	ret := _m.Called(ctx, userID, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, userID, sessionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthServicer_RevokeSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeSession'
type MockAuthServicer_RevokeSession_Call struct {
	*mock.Call
}

// RevokeSession is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - sessionID uuid.UUID
func (_e *MockAuthServicer_Expecter) RevokeSession(ctx interface{}, userID interface{}, sessionID interface{}) *MockAuthServicer_RevokeSession_Call {
	return &MockAuthServicer_RevokeSession_Call{Call: _e.mock.On("RevokeSession", ctx, userID, sessionID)}
}

func (_c *MockAuthServicer_RevokeSession_Call) Run(run func(ctx context.Context, userID uuid.UUID, sessionID uuid.UUID)) *MockAuthServicer_RevokeSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockAuthServicer_RevokeSession_Call) Return(_a0 error) *MockAuthServicer_RevokeSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthServicer_RevokeSession_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockAuthServicer_RevokeSession_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProfile provides a mock function with given fields: ctx, userID, req
func (_m *MockAuthServicer) UpdateProfile(ctx context.Context, userID uuid.UUID, req dto.UpdateProfileRequest) (*domain.User, error) {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.UpdateProfileRequest) (*domain.User, error)); ok {
		return rf(ctx, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.UpdateProfileRequest) *domain.User); ok {
		r0 = rf(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, dto.UpdateProfileRequest) error); ok {
		r1 = rf(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthServicer_UpdateProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProfile'
type MockAuthServicer_UpdateProfile_Call struct {
	*mock.Call
}

// UpdateProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - req dto.UpdateProfileRequest
func (_e *MockAuthServicer_Expecter) UpdateProfile(ctx interface{}, userID interface{}, req interface{}) *MockAuthServicer_UpdateProfile_Call {
	return &MockAuthServicer_UpdateProfile_Call{Call: _e.mock.On("UpdateProfile", ctx, userID, req)}
}

func (_c *MockAuthServicer_UpdateProfile_Call) Run(run func(ctx context.Context, userID uuid.UUID, req dto.UpdateProfileRequest)) *MockAuthServicer_UpdateProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(dto.UpdateProfileRequest))
	})
	return _c
}

func (_c *MockAuthServicer_UpdateProfile_Call) Return(_a0 *domain.User, _a1 error) *MockAuthServicer_UpdateProfile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthServicer_UpdateProfile_Call) RunAndReturn(run func(context.Context, uuid.UUID, dto.UpdateProfileRequest) (*domain.User, error)) *MockAuthServicer_UpdateProfile_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyEmail provides a mock function with given fields: ctx, req
func (_m *MockAuthServicer) VerifyEmail(ctx context.Context, req dto.VerifyEmailRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for VerifyEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.VerifyEmailRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthServicer_VerifyEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyEmail'
type MockAuthServicer_VerifyEmail_Call struct {
	*mock.Call
}

// VerifyEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - req dto.VerifyEmailRequest
func (_e *MockAuthServicer_Expecter) VerifyEmail(ctx interface{}, req interface{}) *MockAuthServicer_VerifyEmail_Call {
	return &MockAuthServicer_VerifyEmail_Call{Call: _e.mock.On("VerifyEmail", ctx, req)}
}

func (_c *MockAuthServicer_VerifyEmail_Call) Run(run func(ctx context.Context, req dto.VerifyEmailRequest)) *MockAuthServicer_VerifyEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.VerifyEmailRequest))
	})
	return _c
}

func (_c *MockAuthServicer_VerifyEmail_Call) Return(_a0 error) *MockAuthServicer_VerifyEmail_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthServicer_VerifyEmail_Call) RunAndReturn(run func(context.Context, dto.VerifyEmailRequest) error) *MockAuthServicer_VerifyEmail_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthServicer creates a new instance of MockAuthServicer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthServicer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthServicer {
	mock := &MockAuthServicer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
