// Code generated by mockery v2.53.6. DO NOT EDIT.

package mockport

import (
	context "context"

	domain "github.com/alfariesh/backend-quiz/internal/domain"
	dto "github.com/alfariesh/backend-quiz/internal/dto"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockDeckServicer is an autogenerated mock type for the DeckServicer type
type MockDeckServicer struct {
	mock.Mock
}

type MockDeckServicer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeckServicer) EXPECT() *MockDeckServicer_Expecter {
	return &MockDeckServicer_Expecter{mock: &_m.Mock}
}

// Clone provides a mock function with given fields: ctx, userID, shareCode
func (_m *MockDeckServicer) Clone(ctx context.Context, userID uuid.UUID, shareCode string) (*domain.Deck, error) {
	ret := _m.Called(ctx, userID, shareCode)

	if len(ret) == 0 {
		panic("no return value specified for Clone")
	}

	var r0 *domain.Deck
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (*domain.Deck, error)); ok {
		return rf(ctx, userID, shareCode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) *domain.Deck); ok {
		r0 = rf(ctx, userID, shareCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Deck)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, userID, shareCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDeckServicer_Clone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clone'
type MockDeckServicer_Clone_Call struct {
	*mock.Call
}

// Clone is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - shareCode string
func (_e *MockDeckServicer_Expecter) Clone(ctx interface{}, userID interface{}, shareCode interface{}) *MockDeckServicer_Clone_Call {
	return &MockDeckServicer_Clone_Call{Call: _e.mock.On("Clone", ctx, userID, shareCode)}
}

func (_c *MockDeckServicer_Clone_Call) Run(run func(ctx context.Context, userID uuid.UUID, shareCode string)) *MockDeckServicer_Clone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockDeckServicer_Clone_Call) Return(_a0 *domain.Deck, _a1 error) *MockDeckServicer_Clone_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDeckServicer_Clone_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) (*domain.Deck, error)) *MockDeckServicer_Clone_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, userID, req
func (_m *MockDeckServicer) Create(ctx context.Context, userID uuid.UUID, req dto.CreateDeckRequest) (*domain.Deck, error) {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Deck
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.CreateDeckRequest) (*domain.Deck, error)); ok {
		return rf(ctx, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.CreateDeckRequest) *domain.Deck); ok {
		r0 = rf(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Deck)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, dto.CreateDeckRequest) error); ok {
		r1 = rf(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDeckServicer_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockDeckServicer_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - req dto.CreateDeckRequest
func (_e *MockDeckServicer_Expecter) Create(ctx interface{}, userID interface{}, req interface{}) *MockDeckServicer_Create_Call {
	return &MockDeckServicer_Create_Call{Call: _e.mock.On("Create", ctx, userID, req)}
}

func (_c *MockDeckServicer_Create_Call) Run(run func(ctx context.Context, userID uuid.UUID, req dto.CreateDeckRequest)) *MockDeckServicer_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(dto.CreateDeckRequest))
	})
	return _c
}

func (_c *MockDeckServicer_Create_Call) Return(_a0 *domain.Deck, _a1 error) *MockDeckServicer_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDeckServicer_Create_Call) RunAndReturn(run func(context.Context, uuid.UUID, dto.CreateDeckRequest) (*domain.Deck, error)) *MockDeckServicer_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, userID, deckID
func (_m *MockDeckServicer) Delete(ctx context.Context, userID uuid.UUID, deckID uuid.UUID) error {
	ret := _m.Called(ctx, userID, deckID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, userID, deckID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDeckServicer_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockDeckServicer_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - deckID uuid.UUID
func (_e *MockDeckServicer_Expecter) Delete(ctx interface{}, userID interface{}, deckID interface{}) *MockDeckServicer_Delete_Call {
	return &MockDeckServicer_Delete_Call{Call: _e.mock.On("Delete", ctx, userID, deckID)}
}

func (_c *MockDeckServicer_Delete_Call) Run(run func(ctx context.Context, userID uuid.UUID, deckID uuid.UUID)) *MockDeckServicer_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockDeckServicer_Delete_Call) Return(_a0 error) *MockDeckServicer_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDeckServicer_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockDeckServicer_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Export provides a mock function with given fields: ctx, userID, deckID
func (_m *MockDeckServicer) Export(ctx context.Context, userID uuid.UUID, deckID uuid.UUID) ([]byte, error) {
	ret := _m.Called(ctx, userID, deckID)

	if len(ret) == 0 {
		panic("no return value specified for Export")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]byte, error)); ok {
		return rf(ctx, userID, deckID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []byte); ok {
		r0 = rf(ctx, userID, deckID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, userID, deckID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDeckServicer_Export_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Export'
type MockDeckServicer_Export_Call struct {
	*mock.Call
}

// Export is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - deckID uuid.UUID
func (_e *MockDeckServicer_Expecter) Export(ctx interface{}, userID interface{}, deckID interface{}) *MockDeckServicer_Export_Call {
	return &MockDeckServicer_Export_Call{Call: _e.mock.On("Export", ctx, userID, deckID)}
}

func (_c *MockDeckServicer_Export_Call) Run(run func(ctx context.Context, userID uuid.UUID, deckID uuid.UUID)) *MockDeckServicer_Export_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockDeckServicer_Export_Call) Return(_a0 []byte, _a1 error) *MockDeckServicer_Export_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDeckServicer_Export_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) ([]byte, error)) *MockDeckServicer_Export_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, userID, deckID
func (_m *MockDeckServicer) Get(ctx context.Context, userID uuid.UUID, deckID uuid.UUID) (*domain.Deck, error) {
	ret := _m.Called(ctx, userID, deckID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.Deck
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*domain.Deck, error)); ok {
		return rf(ctx, userID, deckID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *domain.Deck); ok {
		r0 = rf(ctx, userID, deckID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Deck)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, userID, deckID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDeckServicer_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockDeckServicer_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - deckID uuid.UUID
func (_e *MockDeckServicer_Expecter) Get(ctx interface{}, userID interface{}, deckID interface{}) *MockDeckServicer_Get_Call {
	return &MockDeckServicer_Get_Call{Call: _e.mock.On("Get", ctx, userID, deckID)}
}

func (_c *MockDeckServicer_Get_Call) Run(run func(ctx context.Context, userID uuid.UUID, deckID uuid.UUID)) *MockDeckServicer_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockDeckServicer_Get_Call) Return(_a0 *domain.Deck, _a1 error) *MockDeckServicer_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDeckServicer_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*domain.Deck, error)) *MockDeckServicer_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Import provides a mock function with given fields: ctx, userID, req
func (_m *MockDeckServicer) Import(ctx context.Context, userID uuid.UUID, req dto.ImportDeckRequest) (*domain.Deck, error) {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for Import")
	}

	var r0 *domain.Deck
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.ImportDeckRequest) (*domain.Deck, error)); ok {
		return rf(ctx, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.ImportDeckRequest) *domain.Deck); ok {
		r0 = rf(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Deck)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, dto.ImportDeckRequest) error); ok {
		r1 = rf(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDeckServicer_Import_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Import'
type MockDeckServicer_Import_Call struct {
	*mock.Call
}

// Import is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - req dto.ImportDeckRequest
func (_e *MockDeckServicer_Expecter) Import(ctx interface{}, userID interface{}, req interface{}) *MockDeckServicer_Import_Call {
	return &MockDeckServicer_Import_Call{Call: _e.mock.On("Import", ctx, userID, req)}
}

func (_c *MockDeckServicer_Import_Call) Run(run func(ctx context.Context, userID uuid.UUID, req dto.ImportDeckRequest)) *MockDeckServicer_Import_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(dto.ImportDeckRequest))
	})
	return _c
}

func (_c *MockDeckServicer_Import_Call) Return(_a0 *domain.Deck, _a1 error) *MockDeckServicer_Import_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDeckServicer_Import_Call) RunAndReturn(run func(context.Context, uuid.UUID, dto.ImportDeckRequest) (*domain.Deck, error)) *MockDeckServicer_Import_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, userID, limit, offset
func (_m *MockDeckServicer) List(ctx context.Context, userID uuid.UUID, limit int, offset int) ([]domain.DeckWithCounts, int, error) {
	ret := _m.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.DeckWithCounts
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]domain.DeckWithCounts, int, error)); ok {
		return rf(ctx, userID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []domain.DeckWithCounts); ok {
		r0 = rf(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.DeckWithCounts)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) int); ok {
		r1 = rf(ctx, userID, limit, offset)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, int, int) error); ok {
		r2 = rf(ctx, userID, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockDeckServicer_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockDeckServicer_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - limit int
//   - offset int
func (_e *MockDeckServicer_Expecter) List(ctx interface{}, userID interface{}, limit interface{}, offset interface{}) *MockDeckServicer_List_Call {
	return &MockDeckServicer_List_Call{Call: _e.mock.On("List", ctx, userID, limit, offset)}
}

func (_c *MockDeckServicer_List_Call) Run(run func(ctx context.Context, userID uuid.UUID, limit int, offset int)) *MockDeckServicer_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockDeckServicer_List_Call) Return(_a0 []domain.DeckWithCounts, _a1 int, _a2 error) *MockDeckServicer_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockDeckServicer_List_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, int) ([]domain.DeckWithCounts, int, error)) *MockDeckServicer_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListPublic provides a mock function with given fields: ctx, search, limit, offset
func (_m *MockDeckServicer) ListPublic(ctx context.Context, search string, limit int, offset int) ([]domain.DeckWithCounts, int, error) {
	ret := _m.Called(ctx, search, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListPublic")
	}

	var r0 []domain.DeckWithCounts
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]domain.DeckWithCounts, int, error)); ok {
		return rf(ctx, search, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []domain.DeckWithCounts); ok {
		r0 = rf(ctx, search, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.DeckWithCounts)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) int); ok {
		r1 = rf(ctx, search, limit, offset)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int) error); ok {
		r2 = rf(ctx, search, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockDeckServicer_ListPublic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPublic'
type MockDeckServicer_ListPublic_Call struct {
	*mock.Call
}

// ListPublic is a helper method to define mock.On call
//   - ctx context.Context
//   - search string
//   - limit int
//   - offset int
func (_e *MockDeckServicer_Expecter) ListPublic(ctx interface{}, search interface{}, limit interface{}, offset interface{}) *MockDeckServicer_ListPublic_Call {
	return &MockDeckServicer_ListPublic_Call{Call: _e.mock.On("ListPublic", ctx, search, limit, offset)}
}

func (_c *MockDeckServicer_ListPublic_Call) Run(run func(ctx context.Context, search string, limit int, offset int)) *MockDeckServicer_ListPublic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockDeckServicer_ListPublic_Call) Return(_a0 []domain.DeckWithCounts, _a1 int, _a2 error) *MockDeckServicer_ListPublic_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockDeckServicer_ListPublic_Call) RunAndReturn(run func(context.Context, string, int, int) ([]domain.DeckWithCounts, int, error)) *MockDeckServicer_ListPublic_Call {
	_c.Call.Return(run)
	return _c
}

// Share provides a mock function with given fields: ctx, userID, deckID, req
func (_m *MockDeckServicer) Share(ctx context.Context, userID uuid.UUID, deckID uuid.UUID, req dto.ShareDeckRequest) (*domain.DeckShare, error) {
	ret := _m.Called(ctx, userID, deckID, req)

	if len(ret) == 0 {
		panic("no return value specified for Share")
	}

	var r0 *domain.DeckShare
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, dto.ShareDeckRequest) (*domain.DeckShare, error)); ok {
		return rf(ctx, userID, deckID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, dto.ShareDeckRequest) *domain.DeckShare); ok {
		r0 = rf(ctx, userID, deckID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.DeckShare)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, dto.ShareDeckRequest) error); ok {
		r1 = rf(ctx, userID, deckID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDeckServicer_Share_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Share'
type MockDeckServicer_Share_Call struct {
	*mock.Call
}

// Share is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - deckID uuid.UUID
//   - req dto.ShareDeckRequest
func (_e *MockDeckServicer_Expecter) Share(ctx interface{}, userID interface{}, deckID interface{}, req interface{}) *MockDeckServicer_Share_Call {
	return &MockDeckServicer_Share_Call{Call: _e.mock.On("Share", ctx, userID, deckID, req)}
}

func (_c *MockDeckServicer_Share_Call) Run(run func(ctx context.Context, userID uuid.UUID, deckID uuid.UUID, req dto.ShareDeckRequest)) *MockDeckServicer_Share_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(dto.ShareDeckRequest))
	})
	return _c
}

func (_c *MockDeckServicer_Share_Call) Return(_a0 *domain.DeckShare, _a1 error) *MockDeckServicer_Share_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDeckServicer_Share_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, dto.ShareDeckRequest) (*domain.DeckShare, error)) *MockDeckServicer_Share_Call {
	_c.Call.Return(run)
	return _c
}

// Unshare provides a mock function with given fields: ctx, userID, deckID
func (_m *MockDeckServicer) Unshare(ctx context.Context, userID uuid.UUID, deckID uuid.UUID) error {
	ret := _m.Called(ctx, userID, deckID)

	if len(ret) == 0 {
		panic("no return value specified for Unshare")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, userID, deckID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDeckServicer_Unshare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unshare'
type MockDeckServicer_Unshare_Call struct {
	*mock.Call
}

// Unshare is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - deckID uuid.UUID
func (_e *MockDeckServicer_Expecter) Unshare(ctx interface{}, userID interface{}, deckID interface{}) *MockDeckServicer_Unshare_Call {
	return &MockDeckServicer_Unshare_Call{Call: _e.mock.On("Unshare", ctx, userID, deckID)}
}

func (_c *MockDeckServicer_Unshare_Call) Run(run func(ctx context.Context, userID uuid.UUID, deckID uuid.UUID)) *MockDeckServicer_Unshare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockDeckServicer_Unshare_Call) Return(_a0 error) *MockDeckServicer_Unshare_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDeckServicer_Unshare_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockDeckServicer_Unshare_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, userID, deckID, req
func (_m *MockDeckServicer) Update(ctx context.Context, userID uuid.UUID, deckID uuid.UUID, req dto.UpdateDeckRequest) (*domain.Deck, error) {
	ret := _m.Called(ctx, userID, deckID, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.Deck
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, dto.UpdateDeckRequest) (*domain.Deck, error)); ok {
		return rf(ctx, userID, deckID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, dto.UpdateDeckRequest) *domain.Deck); ok {
		r0 = rf(ctx, userID, deckID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Deck)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, dto.UpdateDeckRequest) error); ok {
		r1 = rf(ctx, userID, deckID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDeckServicer_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockDeckServicer_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - deckID uuid.UUID
//   - req dto.UpdateDeckRequest
func (_e *MockDeckServicer_Expecter) Update(ctx interface{}, userID interface{}, deckID interface{}, req interface{}) *MockDeckServicer_Update_Call {
	return &MockDeckServicer_Update_Call{Call: _e.mock.On("Update", ctx, userID, deckID, req)}
}

func (_c *MockDeckServicer_Update_Call) Run(run func(ctx context.Context, userID uuid.UUID, deckID uuid.UUID, req dto.UpdateDeckRequest)) *MockDeckServicer_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(dto.UpdateDeckRequest))
	})
	return _c
}

func (_c *MockDeckServicer_Update_Call) Return(_a0 *domain.Deck, _a1 error) *MockDeckServicer_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDeckServicer_Update_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, dto.UpdateDeckRequest) (*domain.Deck, error)) *MockDeckServicer_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDeckServicer creates a new instance of MockDeckServicer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeckServicer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeckServicer {
	mock := &MockDeckServicer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
