// Code generated by mockery v2.53.6. DO NOT EDIT.

package mockport

import (
	context "context"

	domain "github.com/rekanesiads/backend-quiz/internal/domain"
	dto "github.com/rekanesiads/backend-quiz/internal/dto"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockGoalServicer is an autogenerated mock type for the GoalServicer type
type MockGoalServicer struct {
	mock.Mock
}

type MockGoalServicer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGoalServicer) EXPECT() *MockGoalServicer_Expecter {
	return &MockGoalServicer_Expecter{mock: &_m.Mock}
}

// DeleteGoal provides a mock function with given fields: ctx, userID, goalID
func (_m *MockGoalServicer) DeleteGoal(ctx context.Context, userID uuid.UUID, goalID uuid.UUID) error {
	ret := _m.Called(ctx, userID, goalID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteGoal")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, userID, goalID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGoalServicer_DeleteGoal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteGoal'
type MockGoalServicer_DeleteGoal_Call struct {
	*mock.Call
}

// DeleteGoal is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - goalID uuid.UUID
func (_e *MockGoalServicer_Expecter) DeleteGoal(ctx interface{}, userID interface{}, goalID interface{}) *MockGoalServicer_DeleteGoal_Call {
	return &MockGoalServicer_DeleteGoal_Call{Call: _e.mock.On("DeleteGoal", ctx, userID, goalID)}
}

func (_c *MockGoalServicer_DeleteGoal_Call) Run(run func(ctx context.Context, userID uuid.UUID, goalID uuid.UUID)) *MockGoalServicer_DeleteGoal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockGoalServicer_DeleteGoal_Call) Return(_a0 error) *MockGoalServicer_DeleteGoal_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGoalServicer_DeleteGoal_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockGoalServicer_DeleteGoal_Call {
	_c.Call.Return(run)
	return _c
}

// ListWithProgress provides a mock function with given fields: ctx, userID
func (_m *MockGoalServicer) ListWithProgress(ctx context.Context, userID uuid.UUID) ([]dto.GoalProgress, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListWithProgress")
	}

	var r0 []dto.GoalProgress
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]dto.GoalProgress, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []dto.GoalProgress); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.GoalProgress)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoalServicer_ListWithProgress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWithProgress'
type MockGoalServicer_ListWithProgress_Call struct {
	*mock.Call
}

// ListWithProgress is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockGoalServicer_Expecter) ListWithProgress(ctx interface{}, userID interface{}) *MockGoalServicer_ListWithProgress_Call {
	return &MockGoalServicer_ListWithProgress_Call{Call: _e.mock.On("ListWithProgress", ctx, userID)}
}

func (_c *MockGoalServicer_ListWithProgress_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockGoalServicer_ListWithProgress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockGoalServicer_ListWithProgress_Call) Return(_a0 []dto.GoalProgress, _a1 error) *MockGoalServicer_ListWithProgress_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoalServicer_ListWithProgress_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]dto.GoalProgress, error)) *MockGoalServicer_ListWithProgress_Call {
	_c.Call.Return(run)
	return _c
}

// SetGoal provides a mock function with given fields: ctx, userID, req
func (_m *MockGoalServicer) SetGoal(ctx context.Context, userID uuid.UUID, req dto.SetGoalRequest) (*domain.StudyGoal, error) {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for SetGoal")
	}

	var r0 *domain.StudyGoal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.SetGoalRequest) (*domain.StudyGoal, error)); ok {
		return rf(ctx, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.SetGoalRequest) *domain.StudyGoal); ok {
		r0 = rf(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.StudyGoal)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, dto.SetGoalRequest) error); ok {
		r1 = rf(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoalServicer_SetGoal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetGoal'
type MockGoalServicer_SetGoal_Call struct {
	*mock.Call
}

// SetGoal is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - req dto.SetGoalRequest
func (_e *MockGoalServicer_Expecter) SetGoal(ctx interface{}, userID interface{}, req interface{}) *MockGoalServicer_SetGoal_Call {
	return &MockGoalServicer_SetGoal_Call{Call: _e.mock.On("SetGoal", ctx, userID, req)}
}

func (_c *MockGoalServicer_SetGoal_Call) Run(run func(ctx context.Context, userID uuid.UUID, req dto.SetGoalRequest)) *MockGoalServicer_SetGoal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(dto.SetGoalRequest))
	})
	return _c
}

func (_c *MockGoalServicer_SetGoal_Call) Return(_a0 *domain.StudyGoal, _a1 error) *MockGoalServicer_SetGoal_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoalServicer_SetGoal_Call) RunAndReturn(run func(context.Context, uuid.UUID, dto.SetGoalRequest) (*domain.StudyGoal, error)) *MockGoalServicer_SetGoal_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGoalServicer creates a new instance of MockGoalServicer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGoalServicer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGoalServicer {
	mock := &MockGoalServicer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
