// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cards.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countCardsByDeckID = `-- name: CountCardsByDeckID :one
SELECT COUNT(*)::int FROM cards
WHERE deck_id = $1
    AND ($2::smallint IS NULL OR state = $2)
    AND ($3::text IS NULL OR $3 = ANY(tags))
    AND ($4::text IS NULL OR front ILIKE '%' || $4 || '%' OR back ILIKE '%' || $4 || '%')
`

type CountCardsByDeckIDParams struct {
	DeckID uuid.UUID   `json:"deck_id"`
	State  pgtype.Int2 `json:"state"`
	Tag    pgtype.Text `json:"tag"`
	Query  pgtype.Text `json:"query"`
}

func (q *Queries) CountCardsByDeckID(ctx context.Context, arg CountCardsByDeckIDParams) (int32, error) {
	row := q.db.QueryRow(ctx, countCardsByDeckID,
		arg.DeckID,
		arg.State,
		arg.Tag,
		arg.Query,
	)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countCardsByState = `-- name: CountCardsByState :many
SELECT state, COUNT(*)::int AS count FROM cards
WHERE deck_id = $1 AND NOT is_suspended
GROUP BY state
`

type CountCardsByStateRow struct {
	State int16 `json:"state"`
	Count int32 `json:"count"`
}

func (q *Queries) CountCardsByState(ctx context.Context, deckID uuid.UUID) ([]CountCardsByStateRow, error) {
	rows, err := q.db.Query(ctx, countCardsByState, deckID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountCardsByStateRow{}
	for rows.Next() {
		var i CountCardsByStateRow
		if err := rows.Scan(&i.State, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countDueCards = `-- name: CountDueCards :one
SELECT COUNT(*)::int FROM cards
WHERE deck_id = $1
    AND NOT is_suspended
    AND state IN (1, 2, 3)
    AND due <= $2
`

type CountDueCardsParams struct {
	DeckID uuid.UUID `json:"deck_id"`
	Due    time.Time `json:"due"`
}

func (q *Queries) CountDueCards(ctx context.Context, arg CountDueCardsParams) (int32, error) {
	row := q.db.QueryRow(ctx, countDueCards, arg.DeckID, arg.Due)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createCard = `-- name: CreateCard :one
INSERT INTO cards (deck_id, front, back, content_type, tags, position)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, deck_id, front, back, tags, due, stability, difficulty, elapsed_days, scheduled_days, reps, lapses, state, last_review, is_suspended, position, created_at, updated_at, content_type
`

type CreateCardParams struct {
	DeckID      uuid.UUID `json:"deck_id"`
	Front       string    `json:"front"`
	Back        string    `json:"back"`
	ContentType string    `json:"content_type"`
	Tags        []string  `json:"tags"`
	Position    int32     `json:"position"`
}

func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) (Card, error) {
	row := q.db.QueryRow(ctx, createCard,
		arg.DeckID,
		arg.Front,
		arg.Back,
		arg.ContentType,
		arg.Tags,
		arg.Position,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.DeckID,
		&i.Front,
		&i.Back,
		&i.Tags,
		&i.Due,
		&i.Stability,
		&i.Difficulty,
		&i.ElapsedDays,
		&i.ScheduledDays,
		&i.Reps,
		&i.Lapses,
		&i.State,
		&i.LastReview,
		&i.IsSuspended,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContentType,
	)
	return i, err
}

const deleteCard = `-- name: DeleteCard :exec
DELETE FROM cards WHERE id = $1
`

func (q *Queries) DeleteCard(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCard, id)
	return err
}

const getCardByID = `-- name: GetCardByID :one
SELECT id, deck_id, front, back, tags, due, stability, difficulty, elapsed_days, scheduled_days, reps, lapses, state, last_review, is_suspended, position, created_at, updated_at, content_type FROM cards WHERE id = $1
`

func (q *Queries) GetCardByID(ctx context.Context, id uuid.UUID) (Card, error) {
	row := q.db.QueryRow(ctx, getCardByID, id)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.DeckID,
		&i.Front,
		&i.Back,
		&i.Tags,
		&i.Due,
		&i.Stability,
		&i.Difficulty,
		&i.ElapsedDays,
		&i.ScheduledDays,
		&i.Reps,
		&i.Lapses,
		&i.State,
		&i.LastReview,
		&i.IsSuspended,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContentType,
	)
	return i, err
}

const getDeckMasteryStats = `-- name: GetDeckMasteryStats :one
SELECT
    COUNT(*)::int AS total_cards,
    COUNT(*) FILTER (WHERE state = 2)::int AS mature_cards,
    COALESCE(AVG(stability), 0)::real AS avg_stability
FROM cards
WHERE deck_id = $1 AND NOT is_suspended
`

type GetDeckMasteryStatsRow struct {
	TotalCards   int32   `json:"total_cards"`
	MatureCards  int32   `json:"mature_cards"`
	AvgStability float32 `json:"avg_stability"`
}

func (q *Queries) GetDeckMasteryStats(ctx context.Context, deckID uuid.UUID) (GetDeckMasteryStatsRow, error) {
	row := q.db.QueryRow(ctx, getDeckMasteryStats, deckID)
	var i GetDeckMasteryStatsRow
	err := row.Scan(&i.TotalCards, &i.MatureCards, &i.AvgStability)
	return i, err
}

const getDueCards = `-- name: GetDueCards :many
SELECT id, deck_id, front, back, tags, due, stability, difficulty, elapsed_days, scheduled_days, reps, lapses, state, last_review, is_suspended, position, created_at, updated_at, content_type FROM cards
WHERE deck_id = $1
    AND NOT is_suspended
    AND (
        (state = 0)
        OR (state IN (1, 3) AND due <= $2)
        OR (state = 2 AND due <= $2)
    )
ORDER BY
    CASE WHEN state IN (1, 3) THEN 0
         WHEN state = 2 THEN 1
         WHEN state = 0 THEN 2
    END,
    due ASC
LIMIT $3
`

type GetDueCardsParams struct {
	DeckID uuid.UUID `json:"deck_id"`
	Due    time.Time `json:"due"`
	Limit  int32     `json:"limit"`
}

func (q *Queries) GetDueCards(ctx context.Context, arg GetDueCardsParams) ([]Card, error) {
	rows, err := q.db.Query(ctx, getDueCards, arg.DeckID, arg.Due, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Card{}
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.ID,
			&i.DeckID,
			&i.Front,
			&i.Back,
			&i.Tags,
			&i.Due,
			&i.Stability,
			&i.Difficulty,
			&i.ElapsedDays,
			&i.ScheduledDays,
			&i.Reps,
			&i.Lapses,
			&i.State,
			&i.LastReview,
			&i.IsSuspended,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContentType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNextDueAt = `-- name: GetNextDueAt :one
SELECT MIN(due) AS next_due
FROM cards c
JOIN decks d ON d.id = c.deck_id
WHERE d.user_id = $1
    AND NOT c.is_suspended
    AND NOT d.is_archived
    AND c.state IN (1, 2, 3)
    AND c.due > $2
`

type GetNextDueAtParams struct {
	UserID uuid.UUID `json:"user_id"`
	Due    time.Time `json:"due"`
}

func (q *Queries) GetNextDueAt(ctx context.Context, arg GetNextDueAtParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, getNextDueAt, arg.UserID, arg.Due)
	var next_due interface{}
	err := row.Scan(&next_due)
	return next_due, err
}

const getUpcomingDueSummary = `-- name: GetUpcomingDueSummary :many
SELECT
    d.id AS deck_id,
    d.name AS deck_name,
    COUNT(*) FILTER (WHERE c.state = 0)::int AS new_count,
    COUNT(*) FILTER (WHERE c.state IN (1, 2, 3) AND c.due <= $2)::int AS due_now,
    COUNT(*) FILTER (WHERE c.state IN (1, 2, 3) AND c.due > $2 AND c.due <= $3)::int AS due_soon
FROM cards c
JOIN decks d ON d.id = c.deck_id
WHERE d.user_id = $1
    AND NOT c.is_suspended
    AND NOT d.is_archived
GROUP BY d.id, d.name
HAVING COUNT(*) FILTER (WHERE c.state = 0) > 0
    OR COUNT(*) FILTER (WHERE c.state IN (1, 2, 3) AND c.due <= $3) > 0
ORDER BY
    COUNT(*) FILTER (WHERE c.state IN (1, 2, 3) AND c.due <= $2) DESC,
    d.name
`

type GetUpcomingDueSummaryParams struct {
	UserID uuid.UUID `json:"user_id"`
	Due    time.Time `json:"due"`
	Due_2  time.Time `json:"due_2"`
}

type GetUpcomingDueSummaryRow struct {
	DeckID   uuid.UUID `json:"deck_id"`
	DeckName string    `json:"deck_name"`
	NewCount int32     `json:"new_count"`
	DueNow   int32     `json:"due_now"`
	DueSoon  int32     `json:"due_soon"`
}

func (q *Queries) GetUpcomingDueSummary(ctx context.Context, arg GetUpcomingDueSummaryParams) ([]GetUpcomingDueSummaryRow, error) {
	rows, err := q.db.Query(ctx, getUpcomingDueSummary, arg.UserID, arg.Due, arg.Due_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUpcomingDueSummaryRow{}
	for rows.Next() {
		var i GetUpcomingDueSummaryRow
		if err := rows.Scan(
			&i.DeckID,
			&i.DeckName,
			&i.NewCount,
			&i.DueNow,
			&i.DueSoon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWeakCards = `-- name: GetWeakCards :many
SELECT c.id, c.deck_id, c.front, c.back, c.tags, c.due, c.stability, c.difficulty, c.elapsed_days, c.scheduled_days, c.reps, c.lapses, c.state, c.last_review, c.is_suspended, c.position, c.created_at, c.updated_at, c.content_type FROM cards c
JOIN decks d ON d.id = c.deck_id
WHERE d.user_id = $1 AND NOT c.is_suspended
    AND (c.lapses > 2 OR (c.stability < 5 AND c.reps > 0))
ORDER BY c.lapses DESC, c.stability ASC
LIMIT $2
`

type GetWeakCardsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
}

func (q *Queries) GetWeakCards(ctx context.Context, arg GetWeakCardsParams) ([]Card, error) {
	rows, err := q.db.Query(ctx, getWeakCards, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Card{}
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.ID,
			&i.DeckID,
			&i.Front,
			&i.Back,
			&i.Tags,
			&i.Due,
			&i.Stability,
			&i.Difficulty,
			&i.ElapsedDays,
			&i.ScheduledDays,
			&i.Reps,
			&i.Lapses,
			&i.State,
			&i.LastReview,
			&i.IsSuspended,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContentType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCardsByDeckID = `-- name: ListCardsByDeckID :many
SELECT id, deck_id, front, back, tags, due, stability, difficulty, elapsed_days, scheduled_days, reps, lapses, state, last_review, is_suspended, position, created_at, updated_at, content_type FROM cards
WHERE deck_id = $1
    AND ($2::smallint IS NULL OR state = $2)
    AND ($3::text IS NULL OR $3 = ANY(tags))
    AND ($4::text IS NULL OR front ILIKE '%' || $4 || '%' OR back ILIKE '%' || $4 || '%')
ORDER BY position, created_at
LIMIT $6 OFFSET $5
`

type ListCardsByDeckIDParams struct {
	DeckID    uuid.UUID   `json:"deck_id"`
	State     pgtype.Int2 `json:"state"`
	Tag       pgtype.Text `json:"tag"`
	Query     pgtype.Text `json:"query"`
	RowOffset int32       `json:"row_offset"`
	RowLimit  int32       `json:"row_limit"`
}

func (q *Queries) ListCardsByDeckID(ctx context.Context, arg ListCardsByDeckIDParams) ([]Card, error) {
	rows, err := q.db.Query(ctx, listCardsByDeckID,
		arg.DeckID,
		arg.State,
		arg.Tag,
		arg.Query,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Card{}
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.ID,
			&i.DeckID,
			&i.Front,
			&i.Back,
			&i.Tags,
			&i.Due,
			&i.Stability,
			&i.Difficulty,
			&i.ElapsedDays,
			&i.ScheduledDays,
			&i.Reps,
			&i.Lapses,
			&i.State,
			&i.LastReview,
			&i.IsSuspended,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContentType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetCardFSRS = `-- name: ResetCardFSRS :exec
UPDATE cards SET
    due = now(), stability = 0, difficulty = 0,
    elapsed_days = 0, scheduled_days = 0, reps = 0, lapses = 0,
    state = 0, last_review = NULL, updated_at = now()
WHERE id = $1
`

func (q *Queries) ResetCardFSRS(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, resetCardFSRS, id)
	return err
}

const setCardSuspended = `-- name: SetCardSuspended :exec
UPDATE cards SET is_suspended = $2, updated_at = now() WHERE id = $1
`

type SetCardSuspendedParams struct {
	ID          uuid.UUID `json:"id"`
	IsSuspended bool      `json:"is_suspended"`
}

func (q *Queries) SetCardSuspended(ctx context.Context, arg SetCardSuspendedParams) error {
	_, err := q.db.Exec(ctx, setCardSuspended, arg.ID, arg.IsSuspended)
	return err
}

const updateCard = `-- name: UpdateCard :exec
UPDATE cards SET
    front = $2,
    back = $3,
    content_type = $4,
    tags = $5,
    updated_at = now()
WHERE id = $1
`

type UpdateCardParams struct {
	ID          uuid.UUID `json:"id"`
	Front       string    `json:"front"`
	Back        string    `json:"back"`
	ContentType string    `json:"content_type"`
	Tags        []string  `json:"tags"`
}

func (q *Queries) UpdateCard(ctx context.Context, arg UpdateCardParams) error {
	_, err := q.db.Exec(ctx, updateCard,
		arg.ID,
		arg.Front,
		arg.Back,
		arg.ContentType,
		arg.Tags,
	)
	return err
}

const updateCardFSRS = `-- name: UpdateCardFSRS :exec
UPDATE cards SET
    due = $2,
    stability = $3,
    difficulty = $4,
    elapsed_days = $5,
    scheduled_days = $6,
    reps = $7,
    lapses = $8,
    state = $9,
    last_review = $10,
    updated_at = now()
WHERE id = $1
`

type UpdateCardFSRSParams struct {
	ID            uuid.UUID          `json:"id"`
	Due           time.Time          `json:"due"`
	Stability     float32            `json:"stability"`
	Difficulty    float32            `json:"difficulty"`
	ElapsedDays   int32              `json:"elapsed_days"`
	ScheduledDays int32              `json:"scheduled_days"`
	Reps          int32              `json:"reps"`
	Lapses        int32              `json:"lapses"`
	State         int16              `json:"state"`
	LastReview    pgtype.Timestamptz `json:"last_review"`
}

func (q *Queries) UpdateCardFSRS(ctx context.Context, arg UpdateCardFSRSParams) error {
	_, err := q.db.Exec(ctx, updateCardFSRS,
		arg.ID,
		arg.Due,
		arg.Stability,
		arg.Difficulty,
		arg.ElapsedDays,
		arg.ScheduledDays,
		arg.Reps,
		arg.Lapses,
		arg.State,
		arg.LastReview,
	)
	return err
}
