// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: decks.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countDecksByUserID = `-- name: CountDecksByUserID :one
SELECT COUNT(*)::int FROM decks WHERE user_id = $1
`

func (q *Queries) CountDecksByUserID(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countDecksByUserID, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countPublicDecks = `-- name: CountPublicDecks :one
SELECT COUNT(*)::int
FROM decks d
INNER JOIN deck_shares ds ON ds.deck_id = d.id AND ds.is_public = true
WHERE ($1::text = '' OR d.name ILIKE '%' || $1 || '%')
`

func (q *Queries) CountPublicDecks(ctx context.Context, dollar_1 string) (int32, error) {
	row := q.db.QueryRow(ctx, countPublicDecks, dollar_1)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createDeck = `-- name: CreateDeck :one
INSERT INTO decks (user_id, name, description, new_cards_per_day, position)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, description, is_archived, new_cards_per_day, position, created_at, updated_at
`

type CreateDeckParams struct {
	UserID         uuid.UUID   `json:"user_id"`
	Name           string      `json:"name"`
	Description    string      `json:"description"`
	NewCardsPerDay pgtype.Int4 `json:"new_cards_per_day"`
	Position       int32       `json:"position"`
}

func (q *Queries) CreateDeck(ctx context.Context, arg CreateDeckParams) (Deck, error) {
	row := q.db.QueryRow(ctx, createDeck,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.NewCardsPerDay,
		arg.Position,
	)
	var i Deck
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.IsArchived,
		&i.NewCardsPerDay,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDeckShare = `-- name: CreateDeckShare :one
INSERT INTO deck_shares (deck_id, share_code, is_public)
VALUES ($1, $2, $3)
RETURNING id, deck_id, share_code, is_public, created_at
`

type CreateDeckShareParams struct {
	DeckID    uuid.UUID `json:"deck_id"`
	ShareCode string    `json:"share_code"`
	IsPublic  bool      `json:"is_public"`
}

func (q *Queries) CreateDeckShare(ctx context.Context, arg CreateDeckShareParams) (DeckShare, error) {
	row := q.db.QueryRow(ctx, createDeckShare, arg.DeckID, arg.ShareCode, arg.IsPublic)
	var i DeckShare
	err := row.Scan(
		&i.ID,
		&i.DeckID,
		&i.ShareCode,
		&i.IsPublic,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDeck = `-- name: DeleteDeck :exec
DELETE FROM decks WHERE id = $1
`

func (q *Queries) DeleteDeck(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDeck, id)
	return err
}

const deleteDeckShare = `-- name: DeleteDeckShare :exec
DELETE FROM deck_shares WHERE deck_id = $1
`

func (q *Queries) DeleteDeckShare(ctx context.Context, deckID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDeckShare, deckID)
	return err
}

const getDeckByID = `-- name: GetDeckByID :one
SELECT id, user_id, name, description, is_archived, new_cards_per_day, position, created_at, updated_at FROM decks WHERE id = $1
`

func (q *Queries) GetDeckByID(ctx context.Context, id uuid.UUID) (Deck, error) {
	row := q.db.QueryRow(ctx, getDeckByID, id)
	var i Deck
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.IsArchived,
		&i.NewCardsPerDay,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeckShareByCode = `-- name: GetDeckShareByCode :one
SELECT id, deck_id, share_code, is_public, created_at FROM deck_shares WHERE share_code = $1
`

func (q *Queries) GetDeckShareByCode(ctx context.Context, shareCode string) (DeckShare, error) {
	row := q.db.QueryRow(ctx, getDeckShareByCode, shareCode)
	var i DeckShare
	err := row.Scan(
		&i.ID,
		&i.DeckID,
		&i.ShareCode,
		&i.IsPublic,
		&i.CreatedAt,
	)
	return i, err
}

const getDeckShareByDeckID = `-- name: GetDeckShareByDeckID :one
SELECT id, deck_id, share_code, is_public, created_at FROM deck_shares WHERE deck_id = $1
`

func (q *Queries) GetDeckShareByDeckID(ctx context.Context, deckID uuid.UUID) (DeckShare, error) {
	row := q.db.QueryRow(ctx, getDeckShareByDeckID, deckID)
	var i DeckShare
	err := row.Scan(
		&i.ID,
		&i.DeckID,
		&i.ShareCode,
		&i.IsPublic,
		&i.CreatedAt,
	)
	return i, err
}

const listDecksByUserID = `-- name: ListDecksByUserID :many
SELECT d.id, d.user_id, d.name, d.description, d.is_archived, d.new_cards_per_day, d.position, d.created_at, d.updated_at,
    COALESCE(card_counts.total, 0)::int AS card_count,
    COALESCE(card_counts.new_count, 0)::int AS new_count,
    COALESCE(card_counts.due_count, 0)::int AS due_count,
    COALESCE(card_counts.learn_count, 0)::int AS learn_count,
    COALESCE(card_counts.relearn_count, 0)::int AS relearn_count
FROM decks d
LEFT JOIN LATERAL (
    SELECT
        COUNT(*)::int AS total,
        COUNT(*) FILTER (WHERE c.state = 0 AND NOT c.is_suspended)::int AS new_count,
        COUNT(*) FILTER (WHERE c.state = 2 AND c.due <= now() AND NOT c.is_suspended)::int AS due_count,
        COUNT(*) FILTER (WHERE c.state = 1 AND NOT c.is_suspended)::int AS learn_count,
        COUNT(*) FILTER (WHERE c.state = 3 AND NOT c.is_suspended)::int AS relearn_count
    FROM cards c WHERE c.deck_id = d.id
) card_counts ON true
WHERE d.user_id = $1
ORDER BY d.position, d.created_at
LIMIT $2 OFFSET $3
`

type ListDecksByUserIDParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type ListDecksByUserIDRow struct {
	ID             uuid.UUID   `json:"id"`
	UserID         uuid.UUID   `json:"user_id"`
	Name           string      `json:"name"`
	Description    string      `json:"description"`
	IsArchived     bool        `json:"is_archived"`
	NewCardsPerDay pgtype.Int4 `json:"new_cards_per_day"`
	Position       int32       `json:"position"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
	CardCount      int32       `json:"card_count"`
	NewCount       int32       `json:"new_count"`
	DueCount       int32       `json:"due_count"`
	LearnCount     int32       `json:"learn_count"`
	RelearnCount   int32       `json:"relearn_count"`
}

func (q *Queries) ListDecksByUserID(ctx context.Context, arg ListDecksByUserIDParams) ([]ListDecksByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listDecksByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDecksByUserIDRow{}
	for rows.Next() {
		var i ListDecksByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.IsArchived,
			&i.NewCardsPerDay,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CardCount,
			&i.NewCount,
			&i.DueCount,
			&i.LearnCount,
			&i.RelearnCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicDecks = `-- name: ListPublicDecks :many
SELECT d.id, d.user_id, d.name, d.description, d.is_archived, d.new_cards_per_day, d.position, d.created_at, d.updated_at,
    COALESCE(card_counts.total, 0)::int AS card_count,
    0::int AS new_count,
    0::int AS due_count,
    0::int AS learn_count,
    0::int AS relearn_count
FROM decks d
INNER JOIN deck_shares ds ON ds.deck_id = d.id AND ds.is_public = true
LEFT JOIN LATERAL (
    SELECT COUNT(*)::int AS total
    FROM cards c WHERE c.deck_id = d.id
) card_counts ON true
WHERE ($1::text = '' OR d.name ILIKE '%' || $1 || '%')
ORDER BY d.created_at DESC
LIMIT $2 OFFSET $3
`

type ListPublicDecksParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type ListPublicDecksRow struct {
	ID             uuid.UUID   `json:"id"`
	UserID         uuid.UUID   `json:"user_id"`
	Name           string      `json:"name"`
	Description    string      `json:"description"`
	IsArchived     bool        `json:"is_archived"`
	NewCardsPerDay pgtype.Int4 `json:"new_cards_per_day"`
	Position       int32       `json:"position"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
	CardCount      int32       `json:"card_count"`
	NewCount       int32       `json:"new_count"`
	DueCount       int32       `json:"due_count"`
	LearnCount     int32       `json:"learn_count"`
	RelearnCount   int32       `json:"relearn_count"`
}

func (q *Queries) ListPublicDecks(ctx context.Context, arg ListPublicDecksParams) ([]ListPublicDecksRow, error) {
	rows, err := q.db.Query(ctx, listPublicDecks, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicDecksRow{}
	for rows.Next() {
		var i ListPublicDecksRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.IsArchived,
			&i.NewCardsPerDay,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CardCount,
			&i.NewCount,
			&i.DueCount,
			&i.LearnCount,
			&i.RelearnCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeck = `-- name: UpdateDeck :one
UPDATE decks SET
    name = COALESCE($2, name),
    description = COALESCE($3, description),
    is_archived = COALESCE($4, is_archived),
    new_cards_per_day = COALESCE($5, new_cards_per_day),
    position = COALESCE($6, position),
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, name, description, is_archived, new_cards_per_day, position, created_at, updated_at
`

type UpdateDeckParams struct {
	ID             uuid.UUID   `json:"id"`
	Name           pgtype.Text `json:"name"`
	Description    pgtype.Text `json:"description"`
	IsArchived     pgtype.Bool `json:"is_archived"`
	NewCardsPerDay pgtype.Int4 `json:"new_cards_per_day"`
	Position       pgtype.Int4 `json:"position"`
}

func (q *Queries) UpdateDeck(ctx context.Context, arg UpdateDeckParams) (Deck, error) {
	row := q.db.QueryRow(ctx, updateDeck,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.IsArchived,
		arg.NewCardsPerDay,
		arg.Position,
	)
	var i Deck
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.IsArchived,
		&i.NewCardsPerDay,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
