// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: media.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMedia = `-- name: CreateMedia :one
INSERT INTO media (user_id, card_id, file_name, file_size, mime_type, r2_key, url)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, card_id, file_name, file_size, mime_type, r2_key, url, created_at
`

type CreateMediaParams struct {
	UserID   uuid.UUID   `json:"user_id"`
	CardID   pgtype.UUID `json:"card_id"`
	FileName string      `json:"file_name"`
	FileSize int32       `json:"file_size"`
	MimeType string      `json:"mime_type"`
	R2Key    string      `json:"r2_key"`
	Url      string      `json:"url"`
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error) {
	row := q.db.QueryRow(ctx, createMedia,
		arg.UserID,
		arg.CardID,
		arg.FileName,
		arg.FileSize,
		arg.MimeType,
		arg.R2Key,
		arg.Url,
	)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CardID,
		&i.FileName,
		&i.FileSize,
		&i.MimeType,
		&i.R2Key,
		&i.Url,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMedia = `-- name: DeleteMedia :exec
DELETE FROM media WHERE id = $1
`

func (q *Queries) DeleteMedia(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMedia, id)
	return err
}

const getMediaByID = `-- name: GetMediaByID :one
SELECT id, user_id, card_id, file_name, file_size, mime_type, r2_key, url, created_at FROM media WHERE id = $1
`

func (q *Queries) GetMediaByID(ctx context.Context, id uuid.UUID) (Medium, error) {
	row := q.db.QueryRow(ctx, getMediaByID, id)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CardID,
		&i.FileName,
		&i.FileSize,
		&i.MimeType,
		&i.R2Key,
		&i.Url,
		&i.CreatedAt,
	)
	return i, err
}

const listMediaByCardID = `-- name: ListMediaByCardID :many
SELECT id, user_id, card_id, file_name, file_size, mime_type, r2_key, url, created_at FROM media WHERE card_id = $1 ORDER BY created_at
`

func (q *Queries) ListMediaByCardID(ctx context.Context, cardID pgtype.UUID) ([]Medium, error) {
	rows, err := q.db.Query(ctx, listMediaByCardID, cardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Medium{}
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CardID,
			&i.FileName,
			&i.FileSize,
			&i.MimeType,
			&i.R2Key,
			&i.Url,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaByUserID = `-- name: ListMediaByUserID :many
SELECT id, user_id, card_id, file_name, file_size, mime_type, r2_key, url, created_at FROM media WHERE user_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListMediaByUserIDParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListMediaByUserID(ctx context.Context, arg ListMediaByUserIDParams) ([]Medium, error) {
	rows, err := q.db.Query(ctx, listMediaByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Medium{}
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CardID,
			&i.FileName,
			&i.FileSize,
			&i.MimeType,
			&i.R2Key,
			&i.Url,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
