// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Card struct {
	ID            uuid.UUID          `json:"id"`
	DeckID        uuid.UUID          `json:"deck_id"`
	Front         string             `json:"front"`
	Back          string             `json:"back"`
	Tags          []string           `json:"tags"`
	Due           time.Time          `json:"due"`
	Stability     float32            `json:"stability"`
	Difficulty    float32            `json:"difficulty"`
	ElapsedDays   int32              `json:"elapsed_days"`
	ScheduledDays int32              `json:"scheduled_days"`
	Reps          int32              `json:"reps"`
	Lapses        int32              `json:"lapses"`
	State         int16              `json:"state"`
	LastReview    pgtype.Timestamptz `json:"last_review"`
	IsSuspended   bool               `json:"is_suspended"`
	Position      int32              `json:"position"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
	ContentType   string             `json:"content_type"`
}

type DailyStat struct {
	ID              uuid.UUID     `json:"id"`
	UserID          uuid.UUID     `json:"user_id"`
	Date            pgtype.Date   `json:"date"`
	NewCards        int32         `json:"new_cards"`
	Reviews         int32         `json:"reviews"`
	Relearns        int32         `json:"relearns"`
	TotalDurationMs int32         `json:"total_duration_ms"`
	RetentionRate   pgtype.Float4 `json:"retention_rate"`
}

type Deck struct {
	ID             uuid.UUID   `json:"id"`
	UserID         uuid.UUID   `json:"user_id"`
	Name           string      `json:"name"`
	Description    string      `json:"description"`
	IsArchived     bool        `json:"is_archived"`
	NewCardsPerDay pgtype.Int4 `json:"new_cards_per_day"`
	Position       int32       `json:"position"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
}

type DeckShare struct {
	ID        uuid.UUID `json:"id"`
	DeckID    uuid.UUID `json:"deck_id"`
	ShareCode string    `json:"share_code"`
	IsPublic  bool      `json:"is_public"`
	CreatedAt time.Time `json:"created_at"`
}

type Medium struct {
	ID        uuid.UUID   `json:"id"`
	UserID    uuid.UUID   `json:"user_id"`
	CardID    pgtype.UUID `json:"card_id"`
	FileName  string      `json:"file_name"`
	FileSize  int32       `json:"file_size"`
	MimeType  string      `json:"mime_type"`
	R2Key     string      `json:"r2_key"`
	Url       string      `json:"url"`
	CreatedAt time.Time   `json:"created_at"`
}

type OauthAccount struct {
	ID         uuid.UUID   `json:"id"`
	UserID     uuid.UUID   `json:"user_id"`
	Provider   string      `json:"provider"`
	ProviderID string      `json:"provider_id"`
	Email      string      `json:"email"`
	AvatarUrl  pgtype.Text `json:"avatar_url"`
	CreatedAt  time.Time   `json:"created_at"`
}

type Quiz struct {
	ID               uuid.UUID   `json:"id"`
	UserID           uuid.UUID   `json:"user_id"`
	DeckID           pgtype.UUID `json:"deck_id"`
	Title            string      `json:"title"`
	Description      string      `json:"description"`
	QuizType         string      `json:"quiz_type"`
	TimeLimitSeconds pgtype.Int4 `json:"time_limit_seconds"`
	ShuffleQuestions bool        `json:"shuffle_questions"`
	IsPublished      bool        `json:"is_published"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
}

type QuizAnswer struct {
	ID           uuid.UUID `json:"id"`
	AttemptID    uuid.UUID `json:"attempt_id"`
	QuestionID   uuid.UUID `json:"question_id"`
	UserAnswer   string    `json:"user_answer"`
	IsCorrect    bool      `json:"is_correct"`
	PointsEarned int32     `json:"points_earned"`
	DurationMs   int32     `json:"duration_ms"`
	AnsweredAt   time.Time `json:"answered_at"`
}

type QuizAttempt struct {
	ID             uuid.UUID          `json:"id"`
	QuizID         uuid.UUID          `json:"quiz_id"`
	UserID         uuid.UUID          `json:"user_id"`
	StartedAt      time.Time          `json:"started_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	Score          int32              `json:"score"`
	TotalPoints    int32              `json:"total_points"`
	TotalQuestions int32              `json:"total_questions"`
	CorrectCount   int32              `json:"correct_count"`
	DurationMs     int32              `json:"duration_ms"`
	CreatedAt      time.Time          `json:"created_at"`
}

type QuizQuestion struct {
	ID            uuid.UUID   `json:"id"`
	QuizID        uuid.UUID   `json:"quiz_id"`
	CardID        pgtype.UUID `json:"card_id"`
	QuestionType  string      `json:"question_type"`
	QuestionText  string      `json:"question_text"`
	Options       []byte      `json:"options"`
	CorrectAnswer string      `json:"correct_answer"`
	Explanation   string      `json:"explanation"`
	Position      int32       `json:"position"`
	Points        int32       `json:"points"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
}

type ReviewLog struct {
	ID            uuid.UUID `json:"id"`
	CardID        uuid.UUID `json:"card_id"`
	UserID        uuid.UUID `json:"user_id"`
	Rating        int16     `json:"rating"`
	State         int16     `json:"state"`
	ScheduledDays int32     `json:"scheduled_days"`
	ElapsedDays   int32     `json:"elapsed_days"`
	Stability     float32   `json:"stability"`
	Difficulty    float32   `json:"difficulty"`
	DurationMs    int32     `json:"duration_ms"`
	ReviewedAt    time.Time `json:"reviewed_at"`
	Source        string    `json:"source"`
}

type StudyGoal struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	GoalType    string    `json:"goal_type"`
	TargetValue int32     `json:"target_value"`
	IsActive    bool      `json:"is_active"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type StudySession struct {
	ID              uuid.UUID          `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	DeckID          pgtype.UUID        `json:"deck_id"`
	StartedAt       time.Time          `json:"started_at"`
	EndedAt         pgtype.Timestamptz `json:"ended_at"`
	NewCount        int32              `json:"new_count"`
	ReviewCount     int32              `json:"review_count"`
	RelearnCount    int32              `json:"relearn_count"`
	TotalDurationMs int32              `json:"total_duration_ms"`
}

type User struct {
	ID               uuid.UUID `json:"id"`
	Email            string    `json:"email"`
	PasswordHash     string    `json:"password_hash"`
	DisplayName      string    `json:"display_name"`
	Timezone         string    `json:"timezone"`
	DesiredRetention float32   `json:"desired_retention"`
	DailyNewLimit    int32     `json:"daily_new_limit"`
	DailyReviewLimit int32     `json:"daily_review_limit"`
	FsrsWeights      []float32 `json:"fsrs_weights"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}
