// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountCardsByDeckID(ctx context.Context, arg CountCardsByDeckIDParams) (int32, error)
	CountCardsByState(ctx context.Context, deckID uuid.UUID) ([]CountCardsByStateRow, error)
	CountDecksByUserID(ctx context.Context, userID uuid.UUID) (int32, error)
	CountDueCards(ctx context.Context, arg CountDueCardsParams) (int32, error)
	CountPublicDecks(ctx context.Context, dollar_1 string) (int32, error)
	CountQuizAttemptsByQuizID(ctx context.Context, quizID uuid.UUID) (int32, error)
	CountQuizAttemptsByUserID(ctx context.Context, userID uuid.UUID) (int32, error)
	CountQuizQuestionsByQuizID(ctx context.Context, quizID uuid.UUID) (int32, error)
	CountQuizzesByUserID(ctx context.Context, userID uuid.UUID) (int32, error)
	CountReviewLogsByUserID(ctx context.Context, arg CountReviewLogsByUserIDParams) (int32, error)
	CountReviewsByUserAndDate(ctx context.Context, arg CountReviewsByUserAndDateParams) (int32, error)
	CountStudySessionsByUserID(ctx context.Context, userID uuid.UUID) (int32, error)
	CreateCard(ctx context.Context, arg CreateCardParams) (Card, error)
	CreateDeck(ctx context.Context, arg CreateDeckParams) (Deck, error)
	CreateDeckShare(ctx context.Context, arg CreateDeckShareParams) (DeckShare, error)
	CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error)
	CreateOAuthAccount(ctx context.Context, arg CreateOAuthAccountParams) (OauthAccount, error)
	CreateQuiz(ctx context.Context, arg CreateQuizParams) (Quiz, error)
	CreateQuizAnswer(ctx context.Context, arg CreateQuizAnswerParams) (QuizAnswer, error)
	CreateQuizAttempt(ctx context.Context, arg CreateQuizAttemptParams) (QuizAttempt, error)
	CreateQuizQuestion(ctx context.Context, arg CreateQuizQuestionParams) (QuizQuestion, error)
	CreateReviewLog(ctx context.Context, arg CreateReviewLogParams) (ReviewLog, error)
	CreateStudySession(ctx context.Context, arg CreateStudySessionParams) (StudySession, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCard(ctx context.Context, id uuid.UUID) error
	DeleteDeck(ctx context.Context, id uuid.UUID) error
	DeleteDeckShare(ctx context.Context, deckID uuid.UUID) error
	DeleteMedia(ctx context.Context, id uuid.UUID) error
	DeleteQuiz(ctx context.Context, id uuid.UUID) error
	DeleteQuizQuestion(ctx context.Context, id uuid.UUID) error
	DeleteStudyGoal(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	EndStudySession(ctx context.Context, id uuid.UUID) (StudySession, error)
	GetBestAttemptByQuizID(ctx context.Context, quizID uuid.UUID) (QuizAttempt, error)
	GetCardByID(ctx context.Context, id uuid.UUID) (Card, error)
	GetDailyStats(ctx context.Context, arg GetDailyStatsParams) ([]DailyStat, error)
	GetDeckByID(ctx context.Context, id uuid.UUID) (Deck, error)
	GetDeckMasteryStats(ctx context.Context, deckID uuid.UUID) (GetDeckMasteryStatsRow, error)
	GetDeckShareByCode(ctx context.Context, shareCode string) (DeckShare, error)
	GetDeckShareByDeckID(ctx context.Context, deckID uuid.UUID) (DeckShare, error)
	GetDueCards(ctx context.Context, arg GetDueCardsParams) ([]Card, error)
	GetGlobalLeaderboard(ctx context.Context, limit int32) ([]GetGlobalLeaderboardRow, error)
	GetMediaByID(ctx context.Context, id uuid.UUID) (Medium, error)
	GetNextDueAt(ctx context.Context, arg GetNextDueAtParams) (interface{}, error)
	GetOAuthAccount(ctx context.Context, arg GetOAuthAccountParams) (OauthAccount, error)
	GetOAuthAccountsByUserID(ctx context.Context, userID uuid.UUID) ([]OauthAccount, error)
	GetQuizAnswerByAttemptAndQuestion(ctx context.Context, arg GetQuizAnswerByAttemptAndQuestionParams) (QuizAnswer, error)
	GetQuizAttemptByID(ctx context.Context, id uuid.UUID) (QuizAttempt, error)
	GetQuizByID(ctx context.Context, id uuid.UUID) (Quiz, error)
	GetQuizQuestionByID(ctx context.Context, id uuid.UUID) (QuizQuestion, error)
	GetReviewCountsPerDay(ctx context.Context, arg GetReviewCountsPerDayParams) ([]GetReviewCountsPerDayRow, error)
	GetStreak(ctx context.Context, userID uuid.UUID) (interface{}, error)
	GetStudyGoalByID(ctx context.Context, id uuid.UUID) (StudyGoal, error)
	GetStudySessionByID(ctx context.Context, id uuid.UUID) (StudySession, error)
	GetUpcomingDueSummary(ctx context.Context, arg GetUpcomingDueSummaryParams) ([]GetUpcomingDueSummaryRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetWeakCards(ctx context.Context, arg GetWeakCardsParams) ([]Card, error)
	IncrementSessionCounters(ctx context.Context, arg IncrementSessionCountersParams) error
	ListCardsByDeckID(ctx context.Context, arg ListCardsByDeckIDParams) ([]Card, error)
	ListDecksByUserID(ctx context.Context, arg ListDecksByUserIDParams) ([]ListDecksByUserIDRow, error)
	ListMediaByCardID(ctx context.Context, cardID pgtype.UUID) ([]Medium, error)
	ListMediaByUserID(ctx context.Context, arg ListMediaByUserIDParams) ([]Medium, error)
	ListPublicDecks(ctx context.Context, arg ListPublicDecksParams) ([]ListPublicDecksRow, error)
	ListQuizAnswersByAttemptID(ctx context.Context, attemptID uuid.UUID) ([]QuizAnswer, error)
	ListQuizAttemptsByQuizID(ctx context.Context, arg ListQuizAttemptsByQuizIDParams) ([]QuizAttempt, error)
	ListQuizAttemptsByUserID(ctx context.Context, arg ListQuizAttemptsByUserIDParams) ([]QuizAttempt, error)
	ListQuizQuestionsByQuizID(ctx context.Context, quizID uuid.UUID) ([]QuizQuestion, error)
	ListQuizzesByDeckAndType(ctx context.Context, arg ListQuizzesByDeckAndTypeParams) ([]Quiz, error)
	ListQuizzesByUserID(ctx context.Context, arg ListQuizzesByUserIDParams) ([]ListQuizzesByUserIDRow, error)
	ListReviewLogsByCardID(ctx context.Context, cardID uuid.UUID) ([]ReviewLog, error)
	ListReviewLogsByUserID(ctx context.Context, arg ListReviewLogsByUserIDParams) ([]ReviewLog, error)
	ListStudyGoalsByUserID(ctx context.Context, userID uuid.UUID) ([]StudyGoal, error)
	ListStudySessionsByUserID(ctx context.Context, arg ListStudySessionsByUserIDParams) ([]StudySession, error)
	ResetCardFSRS(ctx context.Context, id uuid.UUID) error
	SetCardSuspended(ctx context.Context, arg SetCardSuspendedParams) error
	UpdateCard(ctx context.Context, arg UpdateCardParams) error
	UpdateCardFSRS(ctx context.Context, arg UpdateCardFSRSParams) error
	UpdateDeck(ctx context.Context, arg UpdateDeckParams) (Deck, error)
	UpdateQuiz(ctx context.Context, arg UpdateQuizParams) error
	UpdateQuizAttempt(ctx context.Context, arg UpdateQuizAttemptParams) error
	UpdateQuizQuestion(ctx context.Context, arg UpdateQuizQuestionParams) error
	UpdateStudySession(ctx context.Context, arg UpdateStudySessionParams) (StudySession, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpsertDailyStats(ctx context.Context, arg UpsertDailyStatsParams) (DailyStat, error)
	UpsertStudyGoal(ctx context.Context, arg UpsertStudyGoalParams) (StudyGoal, error)
}

var _ Querier = (*Queries)(nil)
