// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: quizzes.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countQuizQuestionsByQuizID = `-- name: CountQuizQuestionsByQuizID :one
SELECT COUNT(*)::int FROM quiz_questions WHERE quiz_id = $1
`

func (q *Queries) CountQuizQuestionsByQuizID(ctx context.Context, quizID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countQuizQuestionsByQuizID, quizID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countQuizzesByUserID = `-- name: CountQuizzesByUserID :one
SELECT COUNT(*)::int FROM quizzes WHERE user_id = $1
`

func (q *Queries) CountQuizzesByUserID(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countQuizzesByUserID, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createQuiz = `-- name: CreateQuiz :one
INSERT INTO quizzes (user_id, deck_id, title, description, quiz_type, time_limit_seconds, shuffle_questions)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, deck_id, title, description, quiz_type, time_limit_seconds, shuffle_questions, is_published, created_at, updated_at
`

type CreateQuizParams struct {
	UserID           uuid.UUID   `json:"user_id"`
	DeckID           pgtype.UUID `json:"deck_id"`
	Title            string      `json:"title"`
	Description      string      `json:"description"`
	QuizType         string      `json:"quiz_type"`
	TimeLimitSeconds pgtype.Int4 `json:"time_limit_seconds"`
	ShuffleQuestions bool        `json:"shuffle_questions"`
}

func (q *Queries) CreateQuiz(ctx context.Context, arg CreateQuizParams) (Quiz, error) {
	row := q.db.QueryRow(ctx, createQuiz,
		arg.UserID,
		arg.DeckID,
		arg.Title,
		arg.Description,
		arg.QuizType,
		arg.TimeLimitSeconds,
		arg.ShuffleQuestions,
	)
	var i Quiz
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeckID,
		&i.Title,
		&i.Description,
		&i.QuizType,
		&i.TimeLimitSeconds,
		&i.ShuffleQuestions,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createQuizQuestion = `-- name: CreateQuizQuestion :one
INSERT INTO quiz_questions (quiz_id, card_id, question_type, question_text, options, correct_answer, explanation, position, points)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, quiz_id, card_id, question_type, question_text, options, correct_answer, explanation, position, points, created_at, updated_at
`

type CreateQuizQuestionParams struct {
	QuizID        uuid.UUID   `json:"quiz_id"`
	CardID        pgtype.UUID `json:"card_id"`
	QuestionType  string      `json:"question_type"`
	QuestionText  string      `json:"question_text"`
	Options       []byte      `json:"options"`
	CorrectAnswer string      `json:"correct_answer"`
	Explanation   string      `json:"explanation"`
	Position      int32       `json:"position"`
	Points        int32       `json:"points"`
}

func (q *Queries) CreateQuizQuestion(ctx context.Context, arg CreateQuizQuestionParams) (QuizQuestion, error) {
	row := q.db.QueryRow(ctx, createQuizQuestion,
		arg.QuizID,
		arg.CardID,
		arg.QuestionType,
		arg.QuestionText,
		arg.Options,
		arg.CorrectAnswer,
		arg.Explanation,
		arg.Position,
		arg.Points,
	)
	var i QuizQuestion
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.CardID,
		&i.QuestionType,
		&i.QuestionText,
		&i.Options,
		&i.CorrectAnswer,
		&i.Explanation,
		&i.Position,
		&i.Points,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteQuiz = `-- name: DeleteQuiz :exec
DELETE FROM quizzes WHERE id = $1
`

func (q *Queries) DeleteQuiz(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteQuiz, id)
	return err
}

const deleteQuizQuestion = `-- name: DeleteQuizQuestion :exec
DELETE FROM quiz_questions WHERE id = $1
`

func (q *Queries) DeleteQuizQuestion(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteQuizQuestion, id)
	return err
}

const getQuizByID = `-- name: GetQuizByID :one
SELECT id, user_id, deck_id, title, description, quiz_type, time_limit_seconds, shuffle_questions, is_published, created_at, updated_at FROM quizzes WHERE id = $1
`

func (q *Queries) GetQuizByID(ctx context.Context, id uuid.UUID) (Quiz, error) {
	row := q.db.QueryRow(ctx, getQuizByID, id)
	var i Quiz
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeckID,
		&i.Title,
		&i.Description,
		&i.QuizType,
		&i.TimeLimitSeconds,
		&i.ShuffleQuestions,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQuizQuestionByID = `-- name: GetQuizQuestionByID :one
SELECT id, quiz_id, card_id, question_type, question_text, options, correct_answer, explanation, position, points, created_at, updated_at FROM quiz_questions WHERE id = $1
`

func (q *Queries) GetQuizQuestionByID(ctx context.Context, id uuid.UUID) (QuizQuestion, error) {
	row := q.db.QueryRow(ctx, getQuizQuestionByID, id)
	var i QuizQuestion
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.CardID,
		&i.QuestionType,
		&i.QuestionText,
		&i.Options,
		&i.CorrectAnswer,
		&i.Explanation,
		&i.Position,
		&i.Points,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listQuizQuestionsByQuizID = `-- name: ListQuizQuestionsByQuizID :many
SELECT id, quiz_id, card_id, question_type, question_text, options, correct_answer, explanation, position, points, created_at, updated_at FROM quiz_questions WHERE quiz_id = $1
ORDER BY position, created_at
`

func (q *Queries) ListQuizQuestionsByQuizID(ctx context.Context, quizID uuid.UUID) ([]QuizQuestion, error) {
	rows, err := q.db.Query(ctx, listQuizQuestionsByQuizID, quizID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QuizQuestion{}
	for rows.Next() {
		var i QuizQuestion
		if err := rows.Scan(
			&i.ID,
			&i.QuizID,
			&i.CardID,
			&i.QuestionType,
			&i.QuestionText,
			&i.Options,
			&i.CorrectAnswer,
			&i.Explanation,
			&i.Position,
			&i.Points,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuizzesByDeckAndType = `-- name: ListQuizzesByDeckAndType :many
SELECT id, user_id, deck_id, title, description, quiz_type, time_limit_seconds, shuffle_questions, is_published, created_at, updated_at FROM quizzes
WHERE deck_id = $1 AND quiz_type = $2
ORDER BY created_at
`

type ListQuizzesByDeckAndTypeParams struct {
	DeckID   pgtype.UUID `json:"deck_id"`
	QuizType string      `json:"quiz_type"`
}

func (q *Queries) ListQuizzesByDeckAndType(ctx context.Context, arg ListQuizzesByDeckAndTypeParams) ([]Quiz, error) {
	rows, err := q.db.Query(ctx, listQuizzesByDeckAndType, arg.DeckID, arg.QuizType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Quiz{}
	for rows.Next() {
		var i Quiz
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeckID,
			&i.Title,
			&i.Description,
			&i.QuizType,
			&i.TimeLimitSeconds,
			&i.ShuffleQuestions,
			&i.IsPublished,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuizzesByUserID = `-- name: ListQuizzesByUserID :many
SELECT q.id, q.user_id, q.deck_id, q.title, q.description, q.quiz_type, q.time_limit_seconds, q.shuffle_questions, q.is_published, q.created_at, q.updated_at,
    COALESCE(qc.cnt, 0)::int AS question_count,
    COALESCE(ac.cnt, 0)::int AS attempt_count
FROM quizzes q
LEFT JOIN LATERAL (SELECT COUNT(*) AS cnt FROM quiz_questions WHERE quiz_id = q.id) qc ON true
LEFT JOIN LATERAL (SELECT COUNT(*) AS cnt FROM quiz_attempts WHERE quiz_id = q.id) ac ON true
WHERE q.user_id = $1
ORDER BY q.created_at DESC
LIMIT $2 OFFSET $3
`

type ListQuizzesByUserIDParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type ListQuizzesByUserIDRow struct {
	ID               uuid.UUID   `json:"id"`
	UserID           uuid.UUID   `json:"user_id"`
	DeckID           pgtype.UUID `json:"deck_id"`
	Title            string      `json:"title"`
	Description      string      `json:"description"`
	QuizType         string      `json:"quiz_type"`
	TimeLimitSeconds pgtype.Int4 `json:"time_limit_seconds"`
	ShuffleQuestions bool        `json:"shuffle_questions"`
	IsPublished      bool        `json:"is_published"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
	QuestionCount    int32       `json:"question_count"`
	AttemptCount     int32       `json:"attempt_count"`
}

func (q *Queries) ListQuizzesByUserID(ctx context.Context, arg ListQuizzesByUserIDParams) ([]ListQuizzesByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listQuizzesByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQuizzesByUserIDRow{}
	for rows.Next() {
		var i ListQuizzesByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeckID,
			&i.Title,
			&i.Description,
			&i.QuizType,
			&i.TimeLimitSeconds,
			&i.ShuffleQuestions,
			&i.IsPublished,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.QuestionCount,
			&i.AttemptCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQuiz = `-- name: UpdateQuiz :exec
UPDATE quizzes SET
    title = $2,
    description = $3,
    quiz_type = $4,
    time_limit_seconds = $5,
    shuffle_questions = $6,
    is_published = $7,
    updated_at = now()
WHERE id = $1
`

type UpdateQuizParams struct {
	ID               uuid.UUID   `json:"id"`
	Title            string      `json:"title"`
	Description      string      `json:"description"`
	QuizType         string      `json:"quiz_type"`
	TimeLimitSeconds pgtype.Int4 `json:"time_limit_seconds"`
	ShuffleQuestions bool        `json:"shuffle_questions"`
	IsPublished      bool        `json:"is_published"`
}

func (q *Queries) UpdateQuiz(ctx context.Context, arg UpdateQuizParams) error {
	_, err := q.db.Exec(ctx, updateQuiz,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.QuizType,
		arg.TimeLimitSeconds,
		arg.ShuffleQuestions,
		arg.IsPublished,
	)
	return err
}

const updateQuizQuestion = `-- name: UpdateQuizQuestion :exec
UPDATE quiz_questions SET
    question_type = $2,
    question_text = $3,
    options = $4,
    correct_answer = $5,
    explanation = $6,
    position = $7,
    points = $8,
    updated_at = now()
WHERE id = $1
`

type UpdateQuizQuestionParams struct {
	ID            uuid.UUID `json:"id"`
	QuestionType  string    `json:"question_type"`
	QuestionText  string    `json:"question_text"`
	Options       []byte    `json:"options"`
	CorrectAnswer string    `json:"correct_answer"`
	Explanation   string    `json:"explanation"`
	Position      int32     `json:"position"`
	Points        int32     `json:"points"`
}

func (q *Queries) UpdateQuizQuestion(ctx context.Context, arg UpdateQuizQuestionParams) error {
	_, err := q.db.Exec(ctx, updateQuizQuestion,
		arg.ID,
		arg.QuestionType,
		arg.QuestionText,
		arg.Options,
		arg.CorrectAnswer,
		arg.Explanation,
		arg.Position,
		arg.Points,
	)
	return err
}
