// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: quiz_attempts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countQuizAttemptsByQuizID = `-- name: CountQuizAttemptsByQuizID :one
SELECT COUNT(*)::int FROM quiz_attempts WHERE quiz_id = $1
`

func (q *Queries) CountQuizAttemptsByQuizID(ctx context.Context, quizID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countQuizAttemptsByQuizID, quizID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countQuizAttemptsByUserID = `-- name: CountQuizAttemptsByUserID :one
SELECT COUNT(*)::int FROM quiz_attempts WHERE user_id = $1
`

func (q *Queries) CountQuizAttemptsByUserID(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countQuizAttemptsByUserID, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createQuizAnswer = `-- name: CreateQuizAnswer :one
INSERT INTO quiz_answers (attempt_id, question_id, user_answer, is_correct, points_earned, duration_ms)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, attempt_id, question_id, user_answer, is_correct, points_earned, duration_ms, answered_at
`

type CreateQuizAnswerParams struct {
	AttemptID    uuid.UUID `json:"attempt_id"`
	QuestionID   uuid.UUID `json:"question_id"`
	UserAnswer   string    `json:"user_answer"`
	IsCorrect    bool      `json:"is_correct"`
	PointsEarned int32     `json:"points_earned"`
	DurationMs   int32     `json:"duration_ms"`
}

func (q *Queries) CreateQuizAnswer(ctx context.Context, arg CreateQuizAnswerParams) (QuizAnswer, error) {
	row := q.db.QueryRow(ctx, createQuizAnswer,
		arg.AttemptID,
		arg.QuestionID,
		arg.UserAnswer,
		arg.IsCorrect,
		arg.PointsEarned,
		arg.DurationMs,
	)
	var i QuizAnswer
	err := row.Scan(
		&i.ID,
		&i.AttemptID,
		&i.QuestionID,
		&i.UserAnswer,
		&i.IsCorrect,
		&i.PointsEarned,
		&i.DurationMs,
		&i.AnsweredAt,
	)
	return i, err
}

const createQuizAttempt = `-- name: CreateQuizAttempt :one
INSERT INTO quiz_attempts (quiz_id, user_id, total_points, total_questions)
VALUES ($1, $2, $3, $4)
RETURNING id, quiz_id, user_id, started_at, completed_at, score, total_points, total_questions, correct_count, duration_ms, created_at
`

type CreateQuizAttemptParams struct {
	QuizID         uuid.UUID `json:"quiz_id"`
	UserID         uuid.UUID `json:"user_id"`
	TotalPoints    int32     `json:"total_points"`
	TotalQuestions int32     `json:"total_questions"`
}

func (q *Queries) CreateQuizAttempt(ctx context.Context, arg CreateQuizAttemptParams) (QuizAttempt, error) {
	row := q.db.QueryRow(ctx, createQuizAttempt,
		arg.QuizID,
		arg.UserID,
		arg.TotalPoints,
		arg.TotalQuestions,
	)
	var i QuizAttempt
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.UserID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Score,
		&i.TotalPoints,
		&i.TotalQuestions,
		&i.CorrectCount,
		&i.DurationMs,
		&i.CreatedAt,
	)
	return i, err
}

const getBestAttemptByQuizID = `-- name: GetBestAttemptByQuizID :one
SELECT id, quiz_id, user_id, started_at, completed_at, score, total_points, total_questions, correct_count, duration_ms, created_at FROM quiz_attempts
WHERE quiz_id = $1 AND completed_at IS NOT NULL
ORDER BY score DESC
LIMIT 1
`

func (q *Queries) GetBestAttemptByQuizID(ctx context.Context, quizID uuid.UUID) (QuizAttempt, error) {
	row := q.db.QueryRow(ctx, getBestAttemptByQuizID, quizID)
	var i QuizAttempt
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.UserID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Score,
		&i.TotalPoints,
		&i.TotalQuestions,
		&i.CorrectCount,
		&i.DurationMs,
		&i.CreatedAt,
	)
	return i, err
}

const getQuizAnswerByAttemptAndQuestion = `-- name: GetQuizAnswerByAttemptAndQuestion :one
SELECT id, attempt_id, question_id, user_answer, is_correct, points_earned, duration_ms, answered_at FROM quiz_answers
WHERE attempt_id = $1 AND question_id = $2
`

type GetQuizAnswerByAttemptAndQuestionParams struct {
	AttemptID  uuid.UUID `json:"attempt_id"`
	QuestionID uuid.UUID `json:"question_id"`
}

func (q *Queries) GetQuizAnswerByAttemptAndQuestion(ctx context.Context, arg GetQuizAnswerByAttemptAndQuestionParams) (QuizAnswer, error) {
	row := q.db.QueryRow(ctx, getQuizAnswerByAttemptAndQuestion, arg.AttemptID, arg.QuestionID)
	var i QuizAnswer
	err := row.Scan(
		&i.ID,
		&i.AttemptID,
		&i.QuestionID,
		&i.UserAnswer,
		&i.IsCorrect,
		&i.PointsEarned,
		&i.DurationMs,
		&i.AnsweredAt,
	)
	return i, err
}

const getQuizAttemptByID = `-- name: GetQuizAttemptByID :one
SELECT id, quiz_id, user_id, started_at, completed_at, score, total_points, total_questions, correct_count, duration_ms, created_at FROM quiz_attempts WHERE id = $1
`

func (q *Queries) GetQuizAttemptByID(ctx context.Context, id uuid.UUID) (QuizAttempt, error) {
	row := q.db.QueryRow(ctx, getQuizAttemptByID, id)
	var i QuizAttempt
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.UserID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Score,
		&i.TotalPoints,
		&i.TotalQuestions,
		&i.CorrectCount,
		&i.DurationMs,
		&i.CreatedAt,
	)
	return i, err
}

const listQuizAnswersByAttemptID = `-- name: ListQuizAnswersByAttemptID :many
SELECT id, attempt_id, question_id, user_answer, is_correct, points_earned, duration_ms, answered_at FROM quiz_answers WHERE attempt_id = $1
ORDER BY answered_at
`

func (q *Queries) ListQuizAnswersByAttemptID(ctx context.Context, attemptID uuid.UUID) ([]QuizAnswer, error) {
	rows, err := q.db.Query(ctx, listQuizAnswersByAttemptID, attemptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QuizAnswer{}
	for rows.Next() {
		var i QuizAnswer
		if err := rows.Scan(
			&i.ID,
			&i.AttemptID,
			&i.QuestionID,
			&i.UserAnswer,
			&i.IsCorrect,
			&i.PointsEarned,
			&i.DurationMs,
			&i.AnsweredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuizAttemptsByQuizID = `-- name: ListQuizAttemptsByQuizID :many
SELECT id, quiz_id, user_id, started_at, completed_at, score, total_points, total_questions, correct_count, duration_ms, created_at FROM quiz_attempts WHERE quiz_id = $1
ORDER BY started_at DESC
LIMIT $2 OFFSET $3
`

type ListQuizAttemptsByQuizIDParams struct {
	QuizID uuid.UUID `json:"quiz_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListQuizAttemptsByQuizID(ctx context.Context, arg ListQuizAttemptsByQuizIDParams) ([]QuizAttempt, error) {
	rows, err := q.db.Query(ctx, listQuizAttemptsByQuizID, arg.QuizID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QuizAttempt{}
	for rows.Next() {
		var i QuizAttempt
		if err := rows.Scan(
			&i.ID,
			&i.QuizID,
			&i.UserID,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Score,
			&i.TotalPoints,
			&i.TotalQuestions,
			&i.CorrectCount,
			&i.DurationMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuizAttemptsByUserID = `-- name: ListQuizAttemptsByUserID :many
SELECT id, quiz_id, user_id, started_at, completed_at, score, total_points, total_questions, correct_count, duration_ms, created_at FROM quiz_attempts WHERE user_id = $1
ORDER BY started_at DESC
LIMIT $2 OFFSET $3
`

type ListQuizAttemptsByUserIDParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListQuizAttemptsByUserID(ctx context.Context, arg ListQuizAttemptsByUserIDParams) ([]QuizAttempt, error) {
	rows, err := q.db.Query(ctx, listQuizAttemptsByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QuizAttempt{}
	for rows.Next() {
		var i QuizAttempt
		if err := rows.Scan(
			&i.ID,
			&i.QuizID,
			&i.UserID,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Score,
			&i.TotalPoints,
			&i.TotalQuestions,
			&i.CorrectCount,
			&i.DurationMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQuizAttempt = `-- name: UpdateQuizAttempt :exec
UPDATE quiz_attempts SET
    completed_at = $2,
    score = $3,
    correct_count = $4,
    duration_ms = $5
WHERE id = $1
`

type UpdateQuizAttemptParams struct {
	ID           uuid.UUID          `json:"id"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	Score        int32              `json:"score"`
	CorrectCount int32              `json:"correct_count"`
	DurationMs   int32              `json:"duration_ms"`
}

func (q *Queries) UpdateQuizAttempt(ctx context.Context, arg UpdateQuizAttemptParams) error {
	_, err := q.db.Exec(ctx, updateQuizAttempt,
		arg.ID,
		arg.CompletedAt,
		arg.Score,
		arg.CorrectCount,
		arg.DurationMs,
	)
	return err
}
