// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: review_logs.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countReviewLogsByUserID = `-- name: CountReviewLogsByUserID :one
SELECT COUNT(*)::int FROM review_logs
WHERE user_id = $1 AND reviewed_at >= $2 AND reviewed_at < $3
`

type CountReviewLogsByUserIDParams struct {
	UserID       uuid.UUID `json:"user_id"`
	ReviewedAt   time.Time `json:"reviewed_at"`
	ReviewedAt_2 time.Time `json:"reviewed_at_2"`
}

func (q *Queries) CountReviewLogsByUserID(ctx context.Context, arg CountReviewLogsByUserIDParams) (int32, error) {
	row := q.db.QueryRow(ctx, countReviewLogsByUserID, arg.UserID, arg.ReviewedAt, arg.ReviewedAt_2)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countReviewsByUserAndDate = `-- name: CountReviewsByUserAndDate :one
SELECT COUNT(*)::int FROM review_logs
WHERE user_id = $1 AND reviewed_at::date = $2::date
`

type CountReviewsByUserAndDateParams struct {
	UserID uuid.UUID   `json:"user_id"`
	Date   pgtype.Date `json:"date"`
}

func (q *Queries) CountReviewsByUserAndDate(ctx context.Context, arg CountReviewsByUserAndDateParams) (int32, error) {
	row := q.db.QueryRow(ctx, countReviewsByUserAndDate, arg.UserID, arg.Date)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createReviewLog = `-- name: CreateReviewLog :one
INSERT INTO review_logs (card_id, user_id, rating, state, scheduled_days, elapsed_days, stability, difficulty, duration_ms, source, reviewed_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, card_id, user_id, rating, state, scheduled_days, elapsed_days, stability, difficulty, duration_ms, reviewed_at, source
`

type CreateReviewLogParams struct {
	CardID        uuid.UUID `json:"card_id"`
	UserID        uuid.UUID `json:"user_id"`
	Rating        int16     `json:"rating"`
	State         int16     `json:"state"`
	ScheduledDays int32     `json:"scheduled_days"`
	ElapsedDays   int32     `json:"elapsed_days"`
	Stability     float32   `json:"stability"`
	Difficulty    float32   `json:"difficulty"`
	DurationMs    int32     `json:"duration_ms"`
	Source        string    `json:"source"`
	ReviewedAt    time.Time `json:"reviewed_at"`
}

func (q *Queries) CreateReviewLog(ctx context.Context, arg CreateReviewLogParams) (ReviewLog, error) {
	row := q.db.QueryRow(ctx, createReviewLog,
		arg.CardID,
		arg.UserID,
		arg.Rating,
		arg.State,
		arg.ScheduledDays,
		arg.ElapsedDays,
		arg.Stability,
		arg.Difficulty,
		arg.DurationMs,
		arg.Source,
		arg.ReviewedAt,
	)
	var i ReviewLog
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.UserID,
		&i.Rating,
		&i.State,
		&i.ScheduledDays,
		&i.ElapsedDays,
		&i.Stability,
		&i.Difficulty,
		&i.DurationMs,
		&i.ReviewedAt,
		&i.Source,
	)
	return i, err
}

const getReviewCountsPerDay = `-- name: GetReviewCountsPerDay :many
SELECT
    reviewed_at::date AS date,
    COUNT(*)::int AS count,
    COUNT(*) FILTER (WHERE rating >= 3)::int AS correct
FROM review_logs
WHERE user_id = $1 AND reviewed_at >= $2 AND reviewed_at < $3
GROUP BY reviewed_at::date
ORDER BY date
`

type GetReviewCountsPerDayParams struct {
	UserID       uuid.UUID `json:"user_id"`
	ReviewedAt   time.Time `json:"reviewed_at"`
	ReviewedAt_2 time.Time `json:"reviewed_at_2"`
}

type GetReviewCountsPerDayRow struct {
	Date    pgtype.Date `json:"date"`
	Count   int32       `json:"count"`
	Correct int32       `json:"correct"`
}

func (q *Queries) GetReviewCountsPerDay(ctx context.Context, arg GetReviewCountsPerDayParams) ([]GetReviewCountsPerDayRow, error) {
	rows, err := q.db.Query(ctx, getReviewCountsPerDay, arg.UserID, arg.ReviewedAt, arg.ReviewedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetReviewCountsPerDayRow{}
	for rows.Next() {
		var i GetReviewCountsPerDayRow
		if err := rows.Scan(&i.Date, &i.Count, &i.Correct); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewLogsByCardID = `-- name: ListReviewLogsByCardID :many
SELECT id, card_id, user_id, rating, state, scheduled_days, elapsed_days, stability, difficulty, duration_ms, reviewed_at, source FROM review_logs WHERE card_id = $1 ORDER BY reviewed_at DESC
`

func (q *Queries) ListReviewLogsByCardID(ctx context.Context, cardID uuid.UUID) ([]ReviewLog, error) {
	rows, err := q.db.Query(ctx, listReviewLogsByCardID, cardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReviewLog{}
	for rows.Next() {
		var i ReviewLog
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.UserID,
			&i.Rating,
			&i.State,
			&i.ScheduledDays,
			&i.ElapsedDays,
			&i.Stability,
			&i.Difficulty,
			&i.DurationMs,
			&i.ReviewedAt,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewLogsByUserID = `-- name: ListReviewLogsByUserID :many
SELECT id, card_id, user_id, rating, state, scheduled_days, elapsed_days, stability, difficulty, duration_ms, reviewed_at, source FROM review_logs
WHERE user_id = $1 AND reviewed_at >= $2 AND reviewed_at < $3
ORDER BY reviewed_at DESC
LIMIT $4 OFFSET $5
`

type ListReviewLogsByUserIDParams struct {
	UserID       uuid.UUID `json:"user_id"`
	ReviewedAt   time.Time `json:"reviewed_at"`
	ReviewedAt_2 time.Time `json:"reviewed_at_2"`
	Limit        int32     `json:"limit"`
	Offset       int32     `json:"offset"`
}

func (q *Queries) ListReviewLogsByUserID(ctx context.Context, arg ListReviewLogsByUserIDParams) ([]ReviewLog, error) {
	rows, err := q.db.Query(ctx, listReviewLogsByUserID,
		arg.UserID,
		arg.ReviewedAt,
		arg.ReviewedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReviewLog{}
	for rows.Next() {
		var i ReviewLog
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.UserID,
			&i.Rating,
			&i.State,
			&i.ScheduledDays,
			&i.ElapsedDays,
			&i.Stability,
			&i.Difficulty,
			&i.DurationMs,
			&i.ReviewedAt,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
