// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getDailyStats = `-- name: GetDailyStats :many
SELECT id, user_id, date, new_cards, reviews, relearns, total_duration_ms, retention_rate FROM daily_stats
WHERE user_id = $1 AND date >= $2 AND date <= $3
ORDER BY date
`

type GetDailyStatsParams struct {
	UserID uuid.UUID   `json:"user_id"`
	Date   pgtype.Date `json:"date"`
	Date_2 pgtype.Date `json:"date_2"`
}

func (q *Queries) GetDailyStats(ctx context.Context, arg GetDailyStatsParams) ([]DailyStat, error) {
	rows, err := q.db.Query(ctx, getDailyStats, arg.UserID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DailyStat{}
	for rows.Next() {
		var i DailyStat
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Date,
			&i.NewCards,
			&i.Reviews,
			&i.Relearns,
			&i.TotalDurationMs,
			&i.RetentionRate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGlobalLeaderboard = `-- name: GetGlobalLeaderboard :many
WITH user_streaks AS (
    SELECT user_id,
        date,
        date - (ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY date DESC))::int * INTERVAL '1 day' AS grp
    FROM daily_stats
    WHERE reviews > 0
),
current_streaks AS (
    SELECT user_id, COUNT(*)::int AS streak
    FROM user_streaks
    WHERE grp = (
        SELECT grp FROM user_streaks us2
        WHERE us2.user_id = user_streaks.user_id
        ORDER BY date DESC LIMIT 1
    )
    GROUP BY user_id
)
SELECT cs.user_id, u.display_name, cs.streak
FROM current_streaks cs
JOIN users u ON u.id = cs.user_id
WHERE cs.streak > 0
ORDER BY cs.streak DESC, u.display_name
LIMIT $1
`

type GetGlobalLeaderboardRow struct {
	UserID      uuid.UUID `json:"user_id"`
	DisplayName string    `json:"display_name"`
	Streak      int32     `json:"streak"`
}

func (q *Queries) GetGlobalLeaderboard(ctx context.Context, limit int32) ([]GetGlobalLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, getGlobalLeaderboard, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetGlobalLeaderboardRow{}
	for rows.Next() {
		var i GetGlobalLeaderboardRow
		if err := rows.Scan(&i.UserID, &i.DisplayName, &i.Streak); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStreak = `-- name: GetStreak :one
WITH streak AS (
    SELECT date,
        date - (ROW_NUMBER() OVER (ORDER BY date DESC))::int * INTERVAL '1 day' AS grp
    FROM daily_stats
    WHERE user_id = $1 AND reviews > 0
)
SELECT COALESCE(COUNT(*)::int, 0) AS streak
FROM streak
WHERE grp = (SELECT grp FROM streak LIMIT 1)
`

func (q *Queries) GetStreak(ctx context.Context, userID uuid.UUID) (interface{}, error) {
	row := q.db.QueryRow(ctx, getStreak, userID)
	var streak interface{}
	err := row.Scan(&streak)
	return streak, err
}

const upsertDailyStats = `-- name: UpsertDailyStats :one
INSERT INTO daily_stats (user_id, date, new_cards, reviews, relearns, total_duration_ms, retention_rate)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (user_id, date) DO UPDATE SET
    new_cards = EXCLUDED.new_cards,
    reviews = EXCLUDED.reviews,
    relearns = EXCLUDED.relearns,
    total_duration_ms = EXCLUDED.total_duration_ms,
    retention_rate = EXCLUDED.retention_rate
RETURNING id, user_id, date, new_cards, reviews, relearns, total_duration_ms, retention_rate
`

type UpsertDailyStatsParams struct {
	UserID          uuid.UUID     `json:"user_id"`
	Date            pgtype.Date   `json:"date"`
	NewCards        int32         `json:"new_cards"`
	Reviews         int32         `json:"reviews"`
	Relearns        int32         `json:"relearns"`
	TotalDurationMs int32         `json:"total_duration_ms"`
	RetentionRate   pgtype.Float4 `json:"retention_rate"`
}

func (q *Queries) UpsertDailyStats(ctx context.Context, arg UpsertDailyStatsParams) (DailyStat, error) {
	row := q.db.QueryRow(ctx, upsertDailyStats,
		arg.UserID,
		arg.Date,
		arg.NewCards,
		arg.Reviews,
		arg.Relearns,
		arg.TotalDurationMs,
		arg.RetentionRate,
	)
	var i DailyStat
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.NewCards,
		&i.Reviews,
		&i.Relearns,
		&i.TotalDurationMs,
		&i.RetentionRate,
	)
	return i, err
}
