// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: study_sessions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countStudySessionsByUserID = `-- name: CountStudySessionsByUserID :one
SELECT COUNT(*)::int FROM study_sessions WHERE user_id = $1
`

func (q *Queries) CountStudySessionsByUserID(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countStudySessionsByUserID, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createStudySession = `-- name: CreateStudySession :one
INSERT INTO study_sessions (user_id, deck_id)
VALUES ($1, $2)
RETURNING id, user_id, deck_id, started_at, ended_at, new_count, review_count, relearn_count, total_duration_ms
`

type CreateStudySessionParams struct {
	UserID uuid.UUID   `json:"user_id"`
	DeckID pgtype.UUID `json:"deck_id"`
}

func (q *Queries) CreateStudySession(ctx context.Context, arg CreateStudySessionParams) (StudySession, error) {
	row := q.db.QueryRow(ctx, createStudySession, arg.UserID, arg.DeckID)
	var i StudySession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeckID,
		&i.StartedAt,
		&i.EndedAt,
		&i.NewCount,
		&i.ReviewCount,
		&i.RelearnCount,
		&i.TotalDurationMs,
	)
	return i, err
}

const endStudySession = `-- name: EndStudySession :one
UPDATE study_sessions SET ended_at = now() WHERE id = $1 RETURNING id, user_id, deck_id, started_at, ended_at, new_count, review_count, relearn_count, total_duration_ms
`

func (q *Queries) EndStudySession(ctx context.Context, id uuid.UUID) (StudySession, error) {
	row := q.db.QueryRow(ctx, endStudySession, id)
	var i StudySession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeckID,
		&i.StartedAt,
		&i.EndedAt,
		&i.NewCount,
		&i.ReviewCount,
		&i.RelearnCount,
		&i.TotalDurationMs,
	)
	return i, err
}

const getStudySessionByID = `-- name: GetStudySessionByID :one
SELECT id, user_id, deck_id, started_at, ended_at, new_count, review_count, relearn_count, total_duration_ms FROM study_sessions WHERE id = $1
`

func (q *Queries) GetStudySessionByID(ctx context.Context, id uuid.UUID) (StudySession, error) {
	row := q.db.QueryRow(ctx, getStudySessionByID, id)
	var i StudySession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeckID,
		&i.StartedAt,
		&i.EndedAt,
		&i.NewCount,
		&i.ReviewCount,
		&i.RelearnCount,
		&i.TotalDurationMs,
	)
	return i, err
}

const incrementSessionCounters = `-- name: IncrementSessionCounters :exec
UPDATE study_sessions SET
    new_count = new_count + $2,
    review_count = review_count + $3,
    relearn_count = relearn_count + $4,
    total_duration_ms = total_duration_ms + $5
WHERE id = $1
`

type IncrementSessionCountersParams struct {
	ID              uuid.UUID `json:"id"`
	NewCount        int32     `json:"new_count"`
	ReviewCount     int32     `json:"review_count"`
	RelearnCount    int32     `json:"relearn_count"`
	TotalDurationMs int32     `json:"total_duration_ms"`
}

func (q *Queries) IncrementSessionCounters(ctx context.Context, arg IncrementSessionCountersParams) error {
	_, err := q.db.Exec(ctx, incrementSessionCounters,
		arg.ID,
		arg.NewCount,
		arg.ReviewCount,
		arg.RelearnCount,
		arg.TotalDurationMs,
	)
	return err
}

const listStudySessionsByUserID = `-- name: ListStudySessionsByUserID :many
SELECT id, user_id, deck_id, started_at, ended_at, new_count, review_count, relearn_count, total_duration_ms FROM study_sessions
WHERE user_id = $1
ORDER BY started_at DESC
LIMIT $2 OFFSET $3
`

type ListStudySessionsByUserIDParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListStudySessionsByUserID(ctx context.Context, arg ListStudySessionsByUserIDParams) ([]StudySession, error) {
	rows, err := q.db.Query(ctx, listStudySessionsByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StudySession{}
	for rows.Next() {
		var i StudySession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeckID,
			&i.StartedAt,
			&i.EndedAt,
			&i.NewCount,
			&i.ReviewCount,
			&i.RelearnCount,
			&i.TotalDurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStudySession = `-- name: UpdateStudySession :one
UPDATE study_sessions SET
    ended_at = COALESCE($2, ended_at),
    new_count = COALESCE($3, new_count),
    review_count = COALESCE($4, review_count),
    relearn_count = COALESCE($5, relearn_count),
    total_duration_ms = COALESCE($6, total_duration_ms)
WHERE id = $1
RETURNING id, user_id, deck_id, started_at, ended_at, new_count, review_count, relearn_count, total_duration_ms
`

type UpdateStudySessionParams struct {
	ID              uuid.UUID          `json:"id"`
	EndedAt         pgtype.Timestamptz `json:"ended_at"`
	NewCount        pgtype.Int4        `json:"new_count"`
	ReviewCount     pgtype.Int4        `json:"review_count"`
	RelearnCount    pgtype.Int4        `json:"relearn_count"`
	TotalDurationMs pgtype.Int4        `json:"total_duration_ms"`
}

func (q *Queries) UpdateStudySession(ctx context.Context, arg UpdateStudySessionParams) (StudySession, error) {
	row := q.db.QueryRow(ctx, updateStudySession,
		arg.ID,
		arg.EndedAt,
		arg.NewCount,
		arg.ReviewCount,
		arg.RelearnCount,
		arg.TotalDurationMs,
	)
	var i StudySession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeckID,
		&i.StartedAt,
		&i.EndedAt,
		&i.NewCount,
		&i.ReviewCount,
		&i.RelearnCount,
		&i.TotalDurationMs,
	)
	return i, err
}
