// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: study_goals.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const deleteStudyGoal = `-- name: DeleteStudyGoal :exec
DELETE FROM study_goals WHERE id = $1
`

func (q *Queries) DeleteStudyGoal(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteStudyGoal, id)
	return err
}

const getStudyGoalByID = `-- name: GetStudyGoalByID :one
SELECT id, user_id, goal_type, target_value, is_active, created_at, updated_at FROM study_goals WHERE id = $1
`

func (q *Queries) GetStudyGoalByID(ctx context.Context, id uuid.UUID) (StudyGoal, error) {
	row := q.db.QueryRow(ctx, getStudyGoalByID, id)
	var i StudyGoal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GoalType,
		&i.TargetValue,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStudyGoalsByUserID = `-- name: ListStudyGoalsByUserID :many
SELECT id, user_id, goal_type, target_value, is_active, created_at, updated_at FROM study_goals
WHERE user_id = $1 AND is_active = true
ORDER BY created_at
`

func (q *Queries) ListStudyGoalsByUserID(ctx context.Context, userID uuid.UUID) ([]StudyGoal, error) {
	rows, err := q.db.Query(ctx, listStudyGoalsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StudyGoal{}
	for rows.Next() {
		var i StudyGoal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GoalType,
			&i.TargetValue,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertStudyGoal = `-- name: UpsertStudyGoal :one
INSERT INTO study_goals (user_id, goal_type, target_value, is_active)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, goal_type) DO UPDATE SET
    target_value = EXCLUDED.target_value,
    is_active = EXCLUDED.is_active,
    updated_at = now()
RETURNING id, user_id, goal_type, target_value, is_active, created_at, updated_at
`

type UpsertStudyGoalParams struct {
	UserID      uuid.UUID `json:"user_id"`
	GoalType    string    `json:"goal_type"`
	TargetValue int32     `json:"target_value"`
	IsActive    bool      `json:"is_active"`
}

func (q *Queries) UpsertStudyGoal(ctx context.Context, arg UpsertStudyGoalParams) (StudyGoal, error) {
	row := q.db.QueryRow(ctx, upsertStudyGoal,
		arg.UserID,
		arg.GoalType,
		arg.TargetValue,
		arg.IsActive,
	)
	var i StudyGoal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GoalType,
		&i.TargetValue,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
