// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOAuthAccount = `-- name: CreateOAuthAccount :one
INSERT INTO oauth_accounts (user_id, provider, provider_id, email, avatar_url)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, provider, provider_id, email, avatar_url, created_at
`

type CreateOAuthAccountParams struct {
	UserID     uuid.UUID   `json:"user_id"`
	Provider   string      `json:"provider"`
	ProviderID string      `json:"provider_id"`
	Email      string      `json:"email"`
	AvatarUrl  pgtype.Text `json:"avatar_url"`
}

func (q *Queries) CreateOAuthAccount(ctx context.Context, arg CreateOAuthAccountParams) (OauthAccount, error) {
	row := q.db.QueryRow(ctx, createOAuthAccount,
		arg.UserID,
		arg.Provider,
		arg.ProviderID,
		arg.Email,
		arg.AvatarUrl,
	)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderID,
		&i.Email,
		&i.AvatarUrl,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, display_name, timezone, desired_retention, daily_new_limit, daily_review_limit)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, email, password_hash, display_name, timezone, desired_retention, daily_new_limit, daily_review_limit, fsrs_weights, created_at, updated_at, reminder_enabled, reminder_time
`

type CreateUserParams struct {
	Email            string  `json:"email"`
	PasswordHash     string  `json:"password_hash"`
	DisplayName      string  `json:"display_name"`
	Timezone         string  `json:"timezone"`
	DesiredRetention float32 `json:"desired_retention"`
	DailyNewLimit    int32   `json:"daily_new_limit"`
	DailyReviewLimit int32   `json:"daily_review_limit"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
		arg.Timezone,
		arg.DesiredRetention,
		arg.DailyNewLimit,
		arg.DailyReviewLimit,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Timezone,
		&i.DesiredRetention,
		&i.DailyNewLimit,
		&i.DailyReviewLimit,
		&i.FsrsWeights,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReminderEnabled,
		&i.ReminderTime,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getOAuthAccount = `-- name: GetOAuthAccount :one
SELECT id, user_id, provider, provider_id, email, avatar_url, created_at FROM oauth_accounts WHERE provider = $1 AND provider_id = $2
`

type GetOAuthAccountParams struct {
	Provider   string `json:"provider"`
	ProviderID string `json:"provider_id"`
}

func (q *Queries) GetOAuthAccount(ctx context.Context, arg GetOAuthAccountParams) (OauthAccount, error) {
	row := q.db.QueryRow(ctx, getOAuthAccount, arg.Provider, arg.ProviderID)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderID,
		&i.Email,
		&i.AvatarUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getOAuthAccountsByUserID = `-- name: GetOAuthAccountsByUserID :many
SELECT id, user_id, provider, provider_id, email, avatar_url, created_at FROM oauth_accounts WHERE user_id = $1
`

func (q *Queries) GetOAuthAccountsByUserID(ctx context.Context, userID uuid.UUID) ([]OauthAccount, error) {
	rows, err := q.db.Query(ctx, getOAuthAccountsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OauthAccount{}
	for rows.Next() {
		var i OauthAccount
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ProviderID,
			&i.Email,
			&i.AvatarUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, display_name, timezone, desired_retention, daily_new_limit, daily_review_limit, fsrs_weights, created_at, updated_at, reminder_enabled, reminder_time FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Timezone,
		&i.DesiredRetention,
		&i.DailyNewLimit,
		&i.DailyReviewLimit,
		&i.FsrsWeights,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReminderEnabled,
		&i.ReminderTime,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, display_name, timezone, desired_retention, daily_new_limit, daily_review_limit, fsrs_weights, created_at, updated_at, reminder_enabled, reminder_time FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Timezone,
		&i.DesiredRetention,
		&i.DailyNewLimit,
		&i.DailyReviewLimit,
		&i.FsrsWeights,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReminderEnabled,
		&i.ReminderTime,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
    display_name = COALESCE($2, display_name),
    timezone = COALESCE($3, timezone),
    desired_retention = COALESCE($4, desired_retention),
    daily_new_limit = COALESCE($5, daily_new_limit),
    daily_review_limit = COALESCE($6, daily_review_limit),
    fsrs_weights = COALESCE($7, fsrs_weights),
    reminder_enabled = COALESCE($8, reminder_enabled),
    reminder_time = COALESCE($9, reminder_time),
    updated_at = now()
WHERE id = $1
RETURNING id, email, password_hash, display_name, timezone, desired_retention, daily_new_limit, daily_review_limit, fsrs_weights, created_at, updated_at, reminder_enabled, reminder_time
`

type UpdateUserParams struct {
	ID               uuid.UUID     `json:"id"`
	DisplayName      pgtype.Text   `json:"display_name"`
	Timezone         pgtype.Text   `json:"timezone"`
	DesiredRetention pgtype.Float4 `json:"desired_retention"`
	DailyNewLimit    pgtype.Int4   `json:"daily_new_limit"`
	DailyReviewLimit pgtype.Int4   `json:"daily_review_limit"`
	FsrsWeights      []float32     `json:"fsrs_weights"`
	ReminderEnabled  pgtype.Bool   `json:"reminder_enabled"`
	ReminderTime     pgtype.Time   `json:"reminder_time"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.DisplayName,
		arg.Timezone,
		arg.DesiredRetention,
		arg.DailyNewLimit,
		arg.DailyReviewLimit,
		arg.FsrsWeights,
		arg.ReminderEnabled,
		arg.ReminderTime,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Timezone,
		&i.DesiredRetention,
		&i.DailyNewLimit,
		&i.DailyReviewLimit,
		&i.FsrsWeights,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReminderEnabled,
		&i.ReminderTime,
	)
	return i, err
}
